### ISSUE TITLE
Metric Cannot be Queried

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#1009]
## 🐛 Bug

I have many metrics, some of them don't appear when they are queried. The metric surely exists, just doesn't appear on the "Metrics" page.

### Environment

- Aim Version  3.0.6
- Python version 3.6.10
- pip version 21.3.1
- OS Linux

### Additional context

Doesn't appear:
![image](https://user-images.githubusercontent.com/22674819/142297906-6366fba0-c1b3-49b7-81be-acd26599eac0.png)

Only 1 out of 2 metrics appear:
![image](https://user-images.githubusercontent.com/22674819/142297963-cae8acd3-2968-45e1-8f57-b51e0c528ff5.png)

The metric surely exists:
![image](https://user-images.githubusercontent.com/22674819/142297983-729b6017-3393-4a4c-abe1-d8771a8f0e75.png)

**Comment by gorarakelyan** [comment]
@MohdElgaar this PR(#1006) will probably resolve the issue. The patch will be released within an hour.

**Comment by gorarakelyan** [comment]
@MohdElgaar the fix has been shipped! Could you please check it out? The current version is 3.0.7. `pip install aim --upgrade`.

**Comment by MohdElgaar** [comment]
@gorarakelyan I just updated and the issue was immediately fixed! Thank you.
