### ISSUE TITLE
Support tensor as an argument for aim.Image

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1028]
Currently `aim.Image` allows to construct Image objects from `PIL.Image`. 
Need to add tensor as a data-source for `aim.Image`. Image size (width, height) and mode (greyscale, RGB, RGBA, etc.) should be deduced from tensor dimensions.
Throw a `ValueError` if cannot convert tensor to `aim.Image`

**Comment by AminSlk** [comment]
Hi! I'd like to work on this issue. Can I?

**Comment by alberttorosyan** [comment]
Hi @AminSlk!

Great to know you would like to contribute. Unfortunately, this issue is already in progress, since we need it to be fixed by the upcoming release (planned in 1-2 days).
We have a similar [issue](https://github.com/aimhubio/aim/issues/1033) opened for tracking numeric values (metrics). Would you like to take that one?

**Comment by AminSlk** [comment]
Of Course. I'll try #1033.
