### ISSUE TITLE
Ability to sort runs by date on the runs page

### ISSUE THREAD

**Issue by ManeSah** [aimhubio/aim#1071]
## 🚀 Feature
Ability to sort runs by date on the runs page - the default view should be newest to oldest (now it's the opposite)

### Motivation
Always frustrating to scroll down to be able to see the latest runs.

### Pitch
Need to sort runs based on the run date and time. The default view should be newest to oldest (now it's the opposite)

**Comment by mihran113** [comment]
hey @ManeSah :) so we've fixed the default ordering of the runs in runs' dashboard, I'll open a new issue for the ordering selection functionality (maybe not only with date and time), and close this issue :)
