### ISSUE TITLE
Add guide on how to serve Aim on K8S cluster

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#1074]
## 📚 Documentation

Add a short guide/tutorial to Aim docs on how to serve Aim on K8S to facilitate adoption.

It also would be great to mention diffs between deploying on GCP, AWS and Azure platforms.

**Comment by flaviuvadan** [comment]
I will take up the GCP part and contribute it on December 15th 🙂

**Comment by gorarakelyan** [comment]
@flaviuvadan awesome, let me know if you need any help :)
