### ISSUE TITLE
After window resize, the runs scroll list results in incomplete viewable area.

### ISSUE THREAD

**Issue by krstp** [aimhubio/aim#1092]
## 🐛 Bug

When window is resized from the - I assume - the default size (of the screen?), meaning narrower in height, the scroll of runs under Runs Explorer will not allow to view full list of runs not allowing user to see very last runs. I assume this is related to window scaling.

### To reproduce

Resize window in height and try to scroll the list of multiple runs under Runs Explorer. The list will be cut off - in the sense, the runs are still there, but user will not be able to scroll to very bottom as the viewable portion is cut off.

### Expected behavior

User should be able to scroll from very top to bottom without trouble.

### Environment

- Aim Version: `3.2.0`
- Python version: `3.9.9`
- pip version: `21.3.1`
- OS: MacOS Monterey

### Additional context

Feel free if the issue is not clear. Originally the issue has been reported in slack `#general` channel and recommended for reporting here.

**Comment by gorarakelyan** [comment]
@krstp this bug should be resolved in Aim v3.2.1. Could you please try it out and confirm if it works as expected?

**Comment by krstp** [comment]
Thanks Gor for the follow up. Functionality tested with positive outcome.
