### ISSUE TITLE
Ability to add custom param to the AimHuggingface Callback

### ISSUE THREAD

**Issue by SSamDav** [aimhubio/aim#1116]
## 🚀 Feature

I would like to add custom params to the hugging face callback.

### Motivation

For instance if I want to track the number of parameters of each model, this number is not a hparam nor a thing that should be computed using a metric. As such, I would like to add custom params to the AimCallback constructor.

### Pitch

As I told above, I would like to add custom params to the AimCallback constructor that would appear in the run parameters.

**Comment by gorarakelyan** [comment]
@SSamDav Aim v3.3.0 was release yesterday which includes your contribution as well! 🙌
