### ISSUE TITLE
Show contexts listed in alphabetical order

### ISSUE THREAD

**Issue by rubenaprikyan** [aimhubio/aim#1122]
## 🚀 Feature

Show contexts listed in alphabetical order

### Motivation
It would be convenient to see alphabetically ordered  lists for the values in Metric, Params, Images dropdown's in the  corresponding explorers

![Screen Shot 2021-12-10 at 11 47 44 PM](https://user-images.githubusercontent.com/21033329/145633528-37433861-7e0d-4067-b527-4a482e75d96a.png)
ing explorers.

![Screen Shot 2021-12-10 at 11 47 55 PM](https://user-images.githubusercontent.com/21033329/145633381-fb9e4a78-bf72-447c-8ea0-e24ebec8bde4.png)
20-a707683071e1.png

### Pitch
Show contexts, params, metrics lists in alphabetical order

**Comment by mahnerak** [comment]
🙏
