### ISSUE TITLE
[UI][feature] ability to remove runs

### ISSUE THREAD

**Issue by mglowacki100** [aimhubio/aim#1170]
## 🚀 Feature
In "Runs" for every row (run) there could be trash icon to remove run from db.

### Motivation
- easy removal of failed experiments 
- stop-gap solution for distributed setting for which I didn't figure out yet, how to log results only from single GPU instead of four (it clutters interface)

### Alternative
- provide info how to do it directly on db

**Comment by gorarakelyan** [comment]
hey @mglowacki100, development of the feature of hard-deleting runs via SDK is already in progress. Once it is done, will definitely add an option of deleting runs from UI as well. Thanks for the feedback 🙏

**Comment by gloryVine** [comment]
@gorarakelyan Imo, this should have really high priority. I have been 'using' aim for a few months now, but essentially I end up wiping my database daily because its cluttered by runs which for some reason or another have no value to me: Sometimes it is because I had an error in the code which I only catched after the run was already over, at other times it's just because some runs were more informative than others, and I want to only focus on the latter ones. Since the aim interface is super cluttered by the uninformative runs, I copy the informative runs' values on paper and wipe the database. I think this is defeating the entire purpose of using an experiment tracking tool, but I don't know what else to do. Can you please at least explain how to delete runs in the database for now.

**Comment by alberttorosyan** [comment]
@gloryVine is the disk space an issue for you? If no and the problem is that you don't want to see some runs in the UI, there's a soft-delete functionality in aim. It is available from Run Details page "Settings" tab.

**Comment by gloryVine** [comment]
Hey @alberttorosyan. No, disk space is not an issue for me at the moment. Could you tell me in more detail where to look for the soft-delete functionality. By 'Run Details' page do you mean the 'Runs' tab which by default is on the left? If so, I don't see a 'Settings' tab there, even though I have the latest version of aim.

**Comment by SGevorg** [comment]
Hi @gloryVine pls check out this [link](http://play.aimstack.io:10001/runs/7eac8cf) of a single run page on the demo site.
It has a settings tab where you can archive the run.
If you want to query archived runs, you can search in the Runs Explorer by `run.archived == True`. Like [this](http://play.aimstack.io:10001/runs?select=GbSfpH1QDBjWVLXWb9MhZ5XebubWFHtGKS8snCPyDcE2ry4Dni6CjUggPETnkXVwUMRpjfNkNZudSaQbzWquiiAgL7ZbEu1AwGWnzcJUNqZSsEDwrzMzWSzeaTwDP9LfzVTYdCbwLBcvyth886oGV)

Hope this helps 🙌

**Comment by roubkar** [comment]
> Hi @SGevorg, thank you, this works! Two suggestions for the maintainers:
> 
> 1. The option to hard-delete **from the Run Explorer** would still be very much appreciated.
> 2. From a usability perspective, it wasn't clear to me how to get to the single-run tab @SGevorg  linked above, including the settings. Intuitively, I tried right-clicking on the run's corresponding row in the Runs Explorer, and I also tried left-clicking on the row. It took me a long while to figure out that I had to click on the blue timestamp in the Run column. Maybe it would be possible to enable one of the other options I mentioned above, I think this would make the UI more accessible and intuitive for new users.

Hey @gloryVine, thanks for the feedback.
Sharing the details of the implementation we're currently working on:
- Implementing table rows/runs multi-select in explorer pages (Runs, Metrics, Params, Images, Scatters)
- Adding the ability to Archive/Unarchive or Delete the selected runs
- Adding an option for hard delete in runs single page (the same settings tab)

**Comment by roubkar** [comment]
Hey all, this feature has been shipped with `v.3.4.0`.
Sharing the screens of new UI:
- Archive/delete runs that are selected from table in `Explorer` pages:
<img width="410" alt="Screen Shot 2022-01-23 at 12 35 54" src="https://user-images.githubusercontent.com/9951653/150670824-6ef9b730-1e65-4993-80a3-ce0865f20086.png">

- Archive/delete run from the `Settings` tab of `Run` page:
<img width="1471" alt="Screen Shot 2022-01-23 at 12 39 06" src="https://user-images.githubusercontent.com/9951653/150670919-f3dc022f-ff83-49af-a22b-ed6fe9702211.png">

**Comment by gloryVine** [comment]
@roubkar Awesome!
