### ISSUE TITLE
Ability to hide system metrics from table

### ISSUE THREAD

**Issue by roubkar** [aimhubio/aim#1198]
## 🚀 Feature

Add ability to toggle all system metrics columns visibility from table

### Motivation

When you don't want to see system metrics columns in runs/params/scatters tables there is no easy way to hide them, it would be great to have an option for hiding the system metrics column.

### Pitch

Add a toggle action to the `Manage Columns` popover which will hide/show system metrics columns.

### Additional context

Discussion: https://github.com/aimhubio/aim/discussions/1023

**Comment by gloryVine** [comment]
@arsengit This looks great, it will remove a lot of clutter!

On a related note, currently my issue is that I have a lot of parameters which each appear as their own column so I can compare better across runs.
- In practice, I only ever need to see certain subgroups of these parameters, and I think it would be of great help if one were able to have something like 'meta columns' which when collapsed would collapse the multiple columns belonging to that meta column.
- For some reason, it is possible to increase column width arbitrarily, whereas it is not possible to minimize column size beyond the point where this would mean cutting off the column name. Again, in practice, it would be extremely helpful to be able to arbitrarily resize column widths. For example, I tend to have very long run-names, but at any given moment I might not be interested in seeing those completely.

It would be great if you could let me know whether any of these two features is already available / planned, or whether I should start a new feature request.

Thanks a lot again for the possibility to hide system metrics.

**Comment by arsengit** [comment]
Hey @gloryVine, thanks a lot for sharing your experience!

So one feature is the ability to manage columns by their group (e.g. hide all params columns, hide all metrics columns)
Another feature request can come out from here: Add ability to group table columns.

As for minimizing column width: this is a bug.

It would be super helpful if you could open feature request/bug report for these items with additional context 🙏

We also have `Show table diff` action button in `Manage Columns` popover which will hide all the columns where each row has the same value.

<img width="756" alt="Screen Shot 2022-01-28 at 16 10 28" src="https://user-images.githubusercontent.com/44676488/151544755-22090ff0-5e7b-4d9d-b5d9-88f833985cd1.png">

Would love to invite you to join [Aim community slack](https://slack.aimstack.io) where you can ask questions, suggest ideas, share your experience and provide feedback 🙂
