### ISSUE TITLE
include UI packaging in `aim` python package build

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1204]
For dev. environment, when running `pip install -e .` from aim source directory, UI sources are not packaged. Need to include UI packaging in `setup.py build` command instead of executing manually.

**Comment by alberttorosyan** [comment]
For dev. environment, when running `pip install -e .` from aim source directory, UI sources are not packaged. Need to include UI packaging in `setup.py build` command instead of executing manually.

**Comment by gorarakelyan** [comment]
related to #1111. closing as duplicate
