### ISSUE TITLE
Creating `aim.Image` from 2D torch tensor raises an exception

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1234]

**Comment by alberttorosyan** [comment]
The following test case fails:

```python
import time

from tests.base import TestBase
from tests.utils import remove_test_data

from aim.sdk import Image

class TestImageConstruction(TestBase):

    def test_image_from_torch_tensor(self):
        try:
            import torch
        except:
            return
        
        # ===> SUCCESS
        try:
            # 2d image - dims = (2,2,1)
            t = torch.tensor([[[1.0], [0.0]], [[0.0], [1.0]]])
            i = Image(t)
        except:
            self.fail()

        # ===> FAIL
        try:
            # 2d image - dims = (2,2)
            t = torch.tensor([[1.0, 0.0], [0.0, 1.0]])
            i = Image(t)
        except:
            self.fail()
```

due to incorrect handling of 2D tensors in `aim.Image`.

Expected behavior would be creating a grayscale Image.

**Comment by avkudr** [comment]
@alberttorosyan 

Please note that in pytorch, image-tensors are defined with the shape `[1,64,64]` for a grayscale image of size 64x64 pixels, and not `[64,64,1]` as in the example above. So, the first test is expected to fail as `aim` processes images with either no channels (grayscale), 1 channel (still grayscale) or 3 channels (RGB). `2` is an invalid number of channels.

Hope that helps

**Comment by alberttorosyan** [comment]
hey @avkudr! thanks for your comment. will change the example accordingly.
