### ISSUE TITLE
need easy way to move a run in repo to another

### ISSUE THREAD

**Issue by ptaejoon** [aimhubio/aim#1246]
## 🚀 Feature

If there's two repo with different directory, it will be helpful if there's easy way to move one's repo to another.

### Motivation
This request is concerned with question below:
https://app.slack.com/client/T015QFY3ZNZ/C01DK8FM2P3/thread/C01DK8FM2P3-1642569350.057200

Currently, if you want to change experiment's repo, you need to:
    1. move experiment data to another repo.
    
``` python
    # $hash is hashed valued of the experiment
    mv /aim/.aim/seqs/progress/$hash /another_aim_repo/.aim/seqs/progress/
    mv /aim/.aim/seqs/locks/$hash another_aim_repo/.aim/seqs/locks/ 
    mv /aim/.aim/seqs/chunks/$hash another_aim_repo/.aim/seqs/chunks/ 
    mv /aim/.aim/meta/chunks/$hash another_aim_repo/.aim/meta/chunks/ 
    mv /aim/.aim/meta/locks/$hash another_aim_repo/.aim/meta/locks/ 
```

    2. add index through the code below

``` python
    from aim import Run, Repo
    repo = Repo.from_path("another_aim_repo")
    run = Run(run_hash=$hash, repo=repo, system_tracking_interval=None)
    # however, there also problem if you don't add experiment in above line, all migrated experiment will set their name to 'default'
    # run = Run(run_hash=$hash, repo=repo, system_tracking_interval=None,experiment='migrated_experiemnt')
```
### Pitch

```python
A = repo.from_path("a") # have runs named "run_a,run_b,run_c"
B = repo.from_path("b") # have runs named "run_d,run_e,run_f"


A.migrate(B, experiment="run_d")
# now repo A have runs "run_a,run_b,run_c,run_d"

A.migrate(B)
# now repo A  have runs "run_a,run_b,run_c,run_d,run_e,run_f"


```

### Additional context

This issue were driven by thoughts to merge all experiments from multiple repos to one
It would be much easy if all experiment were executed in one repo. I tried to host aim through k8s, in a way guided here:
https://aimstack.readthedocs.io/en/latest/guides/integrations/basic_k8s_deployment.html
However, nfs I used did not support writing on sqlite, so this configuration didn't work for me.
It would not be needed if I could change database but I found that all system were hard-coded to use sqlite.
Maybe support to use various database system can be another solution

**Comment by alberttorosyan** [comment]
Hi @ptaejoon! Thanks for opening the issue. Moving runs/merging repos is a feature worth adding. A couple of thoughts on alternative solutions:

1. CLI for moving runs from repo to repo.
    _Lets explore how the interface should be_

2. For the particular use-case you mentioned, remote tracking server will remove necessity to move runs. We released experimental version available in aim `v3.4.0`. It is easy to setup, the full guide is available [here](https://aimstack.readthedocs.io/en/stable/guides/aim_remote_tracking.html)

**Comment by mihran113** [comment]
Hey @ptaejoon. The feature you've requested is shipped with aim v.3.5.0.
There are now options to copy/move runs from one repo to another with either CLI or SDK.

1. Using CLI:
```aim runs --repo=<source_repo_path> mv --destination=<destination_repo_path> run_hash_1, run_hash_2 ...```
```aim runs --repo=<source_repo_path> cp --destination=<destination_repo_path> run_hash_1, run_hash_2 ...```
Source repo path defaults to current working directory. 
Destination repo path and at least one run hash are required.

2. Using SDK:
```
from aim import repo
A = repo.from_path("a")
B = repo.from_path("b")

A.copy_runs([run_hash_1, run_hash2], B)
# A.copy_runs([run_hash_1, run_hash2], B)
```

**Comment by ptaejoon** [comment]
Hi @mihran113 and @alberttorosyan ! Thanks for so fast update on this feature!
I have one question in condition:
  Destination repo path and at least one run hash are required.
Is it problem if command not listing hashed values move all hashed values into destination repo?
In the case hundreds of experiments need to move, copying repo by typing all hashed value is sounds inefficient.
Maybe codes in cli/runs/commands can be altered like :
`python
def copy_runs(ctx, destination, hashes):    
    source = ctx.obj['repo']
    source_repo = Repo.from_path(source)
    destination_repo = Repo.from_path(destination)
    chunks_dir = os.path.join(source, '.aim', 'meta', 'chunks')
    run_hashes = os.listdir(chunks_dir)
    if len(hashes) == 0:
        success, remaining_runs = source_repo.copy_runs(run_hashes, destination_repo)

    success, remaining_runs = source_repo.copy_runs(hashes, destination_repo)
    if success:
        click.echo(f'Successfully copied {len(hashes)} runs.')
    else:
        click.echo('Something went wrong while copying runs. Remaining runs are:', err=True)
        click.secho('\t'.join(remaining_runs), fg='yellow')
`
some codes were copied from function list_runs

**Comment by alberttorosyan** [comment]
Hi @ptaejoon.
Agree, it totally makes sense to have an easy way to copy all runs...
I'm just a bit concerned about implicit behavior. What if one accidentally forgets to specify run hash? Maybe supporting a wildcard syntax would provide better UX? CLI might look like this:
```
aim runs --repo ./ cp * --destination <dest_repo>
```
Let me know what do you think

**Comment by ptaejoon** [comment]
Sounds much reasonable @alberttorosyan !

**Comment by mihran113** [comment]
hey @ptaejoon, we've released the `*` support for `aim runs rm/cp/mv` commands with `v3.6.0`. Please have a look and let us know if everything works as expected :)

**Comment by vakker** [comment]
This is giving me an error. 
If I run from the `.aim` parent dir `aim runs  cp bfb90fe96d284a07b5334e3e --destination ../aim` then it gives me:
```
Error while trying to copy run 'bfb90fe96d284a07b5334e3e'. 'No key () is present.'.
Something went wrong while copying runs. Remaining runs are:
bfb90fe96d284a07b5334e3e
```

If I use `*`, then it just goes through all of the hashes:
```
$ aim runs cp '*' --destination ../aim
Error while trying to copy run 'bfb90fe96d284a07b5334e3e'. 'No key () is present.'.
Error while trying to copy run 'e6d285dfc4f146fb8561fb54'. 'No key () is present.'.
Error while trying to copy run 'dc5358d0254a41cd8bf79041'. 'No key () is present.'.
Error while trying to copy run '34338c65e82a42e3bd454147'. 'No key () is present.'.
Error while trying to copy run 'cc0b79624eb34c1e90d3e781'. 'No key () is present.'.
Error while trying to copy run 'f0f567701e99455e93250e19'. 'No key () is present.'.
Error while trying to copy run '98b7c31867aa4546b3dcb1c1'. 'No key () is present.'.
Error while trying to copy run 'f55f31cbfca147ecb4553101'. 'No key () is present.'.
Error while trying to copy run '7f3855e44e2f4831a726a9bb'. 'No key () is present.'.
Error while trying to copy run 'b9b6338ef9d343be9314233c'. 'No key () is present.'.
...
```

**Comment by alberttorosyan** [comment]
Hey @vakker! The dev version containing multiple fixes for `aim runs cp` command has been released. May I ask you to
`pip install aim==3.14.2.dev1` and try out the fix?

**Comment by Pyrestone** [comment]
@alberttorosyan looks good, haven't run into any issues when tracking a run in one repo in 3.14.2.dev1 and copying and opening it in another. Will have to check with older repos.

Is the storage format compatible with older versions? 
i.e. is it safe to upgrade a repo on a server from an older aim version to this one without losing data?
also, are there any steps necessary for updating the repo files?

**Comment by alberttorosyan** [comment]
> @alberttorosyan looks good, haven't run into any issues when tracking a run in one repo in 3.14.2.dev1 and copying and opening it in another. Will have to check with older repos.
> 
> Is the storage format compatible with older versions? i.e. is it safe to upgrade a repo on a server from an older aim version to this one without losing data? also, are there any steps necessary for updating the repo files?

Normally you do not have to run any upgrade script/command. There's a data format change in Aim 3.11 but it's backwards compatible. However, it is highly recommended to do the upgrade, especially if there are long metric sequences (i.e. 100K+ steps) to avoid negative performance implications. As you correctly noted in other comment, the CLI for upgrading runs is:
`aim storage upgrade 3.11+ ...`
