### ISSUE TITLE
`from aim import Run` fails

### ISSUE THREAD

**Issue by mikel-brostrom** [aimhubio/aim#1267]
## 🐛 Bug

I created a new pip environment installed aim by `pip3 install aim` but

`from aim import Run` fails

```bash
Traceback (most recent call last):
  File "aim.py", line 1, in <module>
    from aim import Run, Image, Distribution
  File "/xxx/aim.py", line 1, in <module>
    from aim import Run, Image, Distribution
ImportError: cannot import name 'Run'
```

### To reproduce

`from aim import Run`

### Environment

- Aim Version: 3.4.1
- Python version: 3.7.9
- pip version: 22.0.2
- OS: 18.04

**Comment by alberttorosyan** [comment]
Hey @mikel-brostrom. Thank you for reporting this. Will try to reproduce and get back to you.

**Comment by alberttorosyan** [comment]
OK, just tried the same setup with docker, and it works...
<img width="613" alt="Screen Shot 2022-02-01 at 17 11 58" src="https://user-images.githubusercontent.com/32957250/151975073-df73fd3b-5c44-407a-8e45-fb4b960faf8c.png">

@mikel-brostrom may I ask you to try the following things:

- `import aim` instead of `from aim import Run`
- `pip install aim==3.3.5` and `from aim import Run`

Thanks in advance!

**Comment by mikel-brostrom** [comment]
- `import aim` instead of `from aim import Run`

works, no error there

- `pip install aim==3.3.5` and `from aim import Run`

still the same error

**Comment by mikel-brostrom** [comment]
I tried this piece of code on my usual machine. No problem there what so ever. Could be some issues with the multi-python environment on the machine I am on. Will explore it further

**Comment by alberttorosyan** [comment]
Thanks @mikel-brostrom! This might help to identify the issue. 
Do you mind to share some details about the environment you use? Are you using `pyenv` or something else to manage multiple versions? Is there anything possibly breaking the isolation fo different environments?
Would be glad to help you with this.

**Comment by mahnerak** [comment]
@mikel-brostrom It looks like you're trying to `import aim` from a file named `aim.py`. 

In python (roughly), if you `import something` it will:
* first look at `something.py` and `something/__init__.py` in your working directory,
* then in `PYTHONPATH` for files with such pattern,
* and only then to your pip-installed packages.

So basically you're trying cyclic import. `import aim` prepares an module with only contents in your `aim.py`.
There should be no error. But when you `from aim import something` it can't find any symbol named `something` in your `aim.py`.

So renaming `aim.py` to `any_other_name.py` will do the trick. It's always better to avoid having conflicting python script names with the installed modules. 
 
I hope this was helpful!
