### ISSUE TITLE
Run class creates weird folder for remote tracking

### ISSUE THREAD

**Issue by aramaim** [aimhubio/aim#1282]
## 🐛 Bug

Run object creates weird (0.0.0.0:53800) folder in the running directory. 

### To reproduce

```
from aim import Run
aim_run = Run(repo='aim://0.0.0.0:53800/')
```
### Expected behavior

Should not be any new fold or file in the running directory. 

### Environment

- Aim v3.5.0
- Python 3.8.9

**Comment by krstp** [comment]
FYI: At least on my side with python `3.9.9` I do not see this error again. `3.7` still yields it.

**Comment by alberttorosyan** [comment]
@krstp can we consider this issue as resolved? You might still see the wrong directories for existing setup, but working from scratch should be OK.

**Comment by krstp** [comment]
Yes, we can close. Thanks for checking.
