### ISSUE TITLE
[Bug] Aim UI not opening on Sagemaker Notebook

### ISSUE THREAD

**Issue by ashutoshsaboo** [aimhubio/aim#1336]
## 🐛 Bug

First of all, really thanks for building this! :) I tried to use Aim on a sagemaker notebook but the full page UI doesn't seem to open up fine. I initialized Aim in one of my already existing project dirs. And when I use `aim up` in one of the Jupyterlab terminals this is what I get: 
```
aim up
Running Aim UI on repo `<Repo#-8308802422050181745 path=/home/ec2-user/SageMaker/test_root/testing/cola-sentence-acceptability/.aim read_only=None>`
Open http://127.0.0.1:43800
Press Ctrl+C to exit
```

Usually sagemaker notebooks provide a proxy to access such localhost ports by going to `https://<notebook_name>.notebook.us-east-1.sagemaker.aws/proxy/43800/`. When I open this URL clearly, there are few network requests made in order to attempt loading the UI, but it doesn't load up and a blank page is shown. When I kill the aim up command, and reload the above link Sagemaker clearly shows a `500 : Internal Server Error` which means there's no process running at this port. So this atleast verifies that, once `aim up` is run the url i mentioned above tries to load the correct UI. 

I've tried setting up mlflow as well as tensorboard similarly on my sagemaker notebook, and can confirm they work perfectly (i.e, their full page UIs can load seamlessly using the same proxy url that I mentioned above). Please note the objective here is to not load the aim ui using the jupyter notebook method which Aim already provides (https://aimstack.readthedocs.io/en/latest/guides/integrations/basic_aim_jupyter_notebook.html) but to actually load the UI full screen to analyze results better (since i've a bunch of experiments so would be much more convenient/useful to load the entire UI to analyze all of them easily, especially given the full page UI for tensorboard and mlflow load seamlessly). 

The only failed request that I see in Network tab is - a GET request to: `https://console.aws.amazon.com/sagemaker/home?region=us-east-1&notebookState=L3N0YXRpYy1maWxlcy9tYW5pZmVzdC5qc29u` which fails due to CORS error. I'm not sure from the URL what this request is actually trying to load, but is there any request for loading Aim UI that could fail due to this CORS error? If so, can this be fixed please? Also, after I got this suspicious error I verified by spawning tensorboard and mlflow, and there's no CORS error when I actually try to load their full page urls through a similar proxy url as to what I mentioned above.

The best alternative that I'm using is mlflow, and I'd really like to move to Aim. My primary use-case is for seamless experiment tracking which clearly from the documentation looks like Aim provides better functionality for than mlflow.

Reference: See this for reference on how to open tensorboard on sagemaker notebook - https://levelup.gitconnected.com/how-to-use-tensorboard-in-an-amazon-sagemaker-notebook-instance-a41ce2fd973f . There are some answers on StackOverflow too regarding this proxy url of sagemaker notebook.

### To reproduce

See details above

### Expected behavior

Full page UI should open up correctly. 

### Environment

- Aim Version (e.g., 3.0.1) - Aim v3.5.3
- Python version - Python 3.7.12
- pip version - pip 21.3.1
- OS (e.g., Linux) - Linux on Sagemaker notebook
- Any other relevant information - See blog linked above on how to spawn tensorboard full page ui on sagemaker notebook's jupyter lab based terminal

### Additional context

NA

**Comment by ashutoshsaboo** [comment]
I just checked the `%aim up` command documented here - https://aimstack.readthedocs.io/en/latest/guides/integrations/basic_aim_jupyter_notebook.html also doesn't work in the jupyerlab cells and doesn't load anything. I'm not sure though if this loading incorrectly (inside the cell) is related to Aim or Sagemaker notebooks, since Tensorboard also didn't render anything with the in-cell command of jupyterlab (https://levelup.gitconnected.com/how-to-use-tensorboard-in-an-amazon-sagemaker-notebook-instance-a41ce2fd973f). 

But the full page UI worked seamlessly for Tensorboard/Mlflow so requesting your help here. I'm at dead ends now as I can't use Aim at all even via the jupyter lab in-cell command. Ideally, i'd like the full page UI to be working as that's more useful and important for me. 

Requesting your help on this please! Thanks in advance! :)

**Comment by ashutoshsaboo** [comment]
Came across these - https://stackoverflow.com/questions/55593128/how-to-run-the-mlflow-web-based-user-interface-from-amazon-sagemaker , https://github.com/mlflow/mlflow/issues/1120 . There were some non relative AJAX requests in mlflow earlier which were causing issues with sagemaker notebook. I came across these links and thought they might be relevant as they were related to working of mlflow with sagemaker notebook, but I'm not sure if this could be related/helpful for this issue with Aim specifically? @rubenaprikyan

**Comment by rubenaprikyan** [comment]
@ashutoshsaboo Thanks for reporting.
It seems the problem comes from, we are not proxying the  aim server url in `jupyter` notebook as we do in `colab`.
We are exploring the solution and the integration with `sagemaker notebook` without problems. I will provide the exploration result in a short while.

You can join to our [slack community](https://slack.aimstack.io/) to make further discussion on this topic.

**Comment by SGevorg** [comment]
@ashutoshsaboo thanks for reporting the issue. is this a blocker for you?

**Comment by ashutoshsaboo** [comment]
Yes it's blocking me completely @SGevorg , i'm not able to use aim anyhow at all currently. Would really love to get aim ui up and running on sagemaker notebook. 
@rubenaprikyan , sure will join the Slack community. Would be really great if either one of you could help get this fixed. :)

**Comment by rubenaprikyan** [comment]
Usage Guide https://aimstack.readthedocs.io/en/stable/guides/integrations/sagemaker_notebook_ui.html

**Comment by SGevorg** [comment]
@ashutoshsaboo can you confirm this issue been fixed? if so please close it too if you get a chance 🙏

**Comment by gorarakelyan** [comment]
closing this issue as it is not related to Aim. Once the third party bugfix is resolved, will update Aim docs 🙌
