### ISSUE TITLE
Fix Autocomplete state issue in grouping popover

### ISSUE THREAD

**Issue by arsengit** [aimhubio/aim#1361]
## 🐛 Bug

After selecting suggested option in `Autocomplete` component the input state was wrong and after deleting text the previous 
tag was also deleted.

### To reproduce

https://user-images.githubusercontent.com/44676488/154534969-b0b76629-3917-4f12-b40b-9fdd50fb82c8.mov

**Comment by rubenaprikyan** [comment]
@arsengit The same issue in ControlPopovers(Tooltip Popover)
