### ISSUE TITLE
Aim behind a proxy server

### ISSUE THREAD

**Issue by dshakey** [aimhubio/aim#1422]
similar to issues #1366 when using the base-path the static files still resolve to the root path. the path is working, but not the static files.

` aim up --base-path <instance>/proxy/43800/ --dev` 
this is using jupyterlab or from the terminal

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/34676590/156056671-2a9e4096-9af2-4ebe-af66-e2e842a43aa7.png">

**Comment by mihran113** [comment]
Hi @dshakey. Thanks for the report. I guess this has something to do with base-path containing slashes, as we didn't account for that in the first iteration. @Hamik25 can provide a better explanation I guess. We'll have a look at it and get back to you with further updates :)

**Comment by rubenaprikyan** [comment]
Hi @dshakey could you please share the version of aim you are using?

**Comment by dshakey** [comment]
`Aim v3.6.1`

plotly dash uses two types url base that work well

#     #'url_base_pathname': '/showtemperature1/',
#     # as the proxy server will remove the prefix
#     'routes_pathname_prefix': '/showtemperature2/', 

#     # the front-end will prefix this string to the requests
#     # that are made to the proxy server
#     'requests_pathname_prefix': '/pompidom3/'
# })

**Comment by rubenaprikyan** [comment]
Please use this form and let me know if you have  a problem

```shell
$ aim up --base-path  <notebook-base>/proxy/absolute/43800
```
If your notebook hasn't base,  just ignore `<notebook-base>` part.

By running this command, you will be able to open Aim UI with `<instance>/proxy/absolute/43800/` url.
I hope your `jupyter-server-proxy` has higher version.

**Comment by dshakey** [comment]
yes this worked, convinced i had tried this already. thank you.
