### ISSUE TITLE
The UI doesn't render properly on colab

### ISSUE THREAD

**Issue by rubenaprikyan** [aimhubio/aim#1455]
## 🐛 Bug

The UI doesn't render properly on colab.
After `%aim up` command it shows empty cell instead of Aim UI.

### To reproduce

Open colab notebook.
- pip install aim
- %load_ext aim
- %aim up

### Expected behavior

Colab should render aim ui by running `%aim up` command

### Environment

- Aim version 3.6.2

**Comment by rubenaprikyan** [comment]
@SGevorg the fix released with v3.6.3, please try it out and let me know if it works for you

**Comment by SGevorg** [comment]
tested, can confirm it works.
