### ISSUE TITLE
Add ability to search , filter and compare runs in /figures section using common search mechanism 

### ISSUE THREAD

**Issue by gerardsolutions** [aimhubio/aim#1509]
## 🚀 Feature

Add ability to search and filter in /figures section using common search mechanism with ability to show results for all runs, not only one (also add bookmarks for those filters)

### Motivation

cross experimental /figures section - something like figure explorer 

### Pitch

I want to compare figures across selected runs

### Alternatives

Add ability to upload and display plotly traces (as part of plotly.graph_object) against of figures, it would be convenient to compare different runs with plotly custom plots

**Comment by hendriks73** [comment]
+ audios, i.e. search by context, name, etc.

**Comment by gorarakelyan** [comment]
@hendriks73 thanks, audios explorer will be the next after figures :)

**Comment by gorarakelyan** [comment]
@hendriks73 could you please open a separate issue with more context and some use cases? that would help us a lot! 🙌

**Comment by gorarakelyan** [comment]
Hey @gerardsolutions! The Figures Explorer has been shipped with Aim v3.13.0. It enables querying and comparing plotly figures across runs side-by-side – roc curves, confusion matrices, etc.

Here is a quick glimpse of how it looks like:
![short_figures](https://user-images.githubusercontent.com/13848158/186951070-d2e34ce0-b294-42b4-9fcd-6dc4745d8fd1.gif)

**Comment by gorarakelyan** [comment]
Closing this issue. If there are any issues/questions/requests please feel free to submit separate issues.
