### ISSUE TITLE
Add more descriptive Colours/Legend to runs list

### ISSUE THREAD

**Issue by gerardsolutions** [aimhubio/aim#1510]
## 🚀 Feature

Add more descriptive coloring to runs list - for example fill Grouping column with whole color and/or add more descriptive legend to /metrics section. Legend could be configurable through templating, for example python string formatting like '{metric.name}:{hparams.ds}'.format(**run)

### Motivation
Very hard to link a specific run in the Run table and the metric plot when comparing many runs in a single plot (>10)

### Pitch

I would like to have a more descriptive legend so I can easily see which curve on a plot belongs to which run

**Comment by piojanu** [comment]
+1
However, I'd love to see an overlayed legend on the graph that shows the group params (matching the colors). Something like this:
![image](https://user-images.githubusercontent.com/23562932/170263188-dbb713c8-bfae-42c2-a469-c9859051d8af.png)

**Comment by vakker** [comment]
@piojanu definitely +1 for your example.
Currently I need to go down to the list to see the legends, and it's really hard to map them back:
![group](https://user-images.githubusercontent.com/3268882/194322207-97f6b2e4-6abf-45b9-be02-76f14533849e.png)

It would be amazing if there was a legend that showed the colour and linestyle for the different groups.

**Comment by KaroMourad** [comment]
Hey @gerardsolutions ,

Added chart legends to Metrics explorer.

Have been shipped with the v3.15.0 release.
To upgrade please run `pip install aim --upgrade`.

**Comment by gorarakelyan** [comment]
@gerardsolutions @vakker @piojanu the feature has been released with Aim v3.15. Closing this issue. Please feel free to reopen or submit a new one if it works not as expected.
