### ISSUE TITLE
Add Notes tab in single run page

### ISSUE THREAD

**Issue by arsengit** [aimhubio/aim#1515]
## 🚀 Feature

Provide users ability to attach, remove and edit notes for the run

<img width="1099" alt="Screen Shot 2022-03-14 at 19 50 55" src="https://user-images.githubusercontent.com/44676488/158210080-3b6c73d5-0c43-488a-ab1a-265181b92189.png">

**Comment by ashutoshsaboo** [comment]
Hi @arsengit , I had a similar request here: https://github.com/aimhubio/aim/issues/291#issuecomment-1055407962. Are you going to provide a markdown wysiwyg based editor for adding a new note from ui or what sort of an editor is it going to be?

**Comment by SGevorg** [comment]
@arsengit @gorarakelyan we should not close the issue unless it's solved.
There needs to be a `duplicate` label and a main thread for the issue if there are duplicates (like in this situation).
In this case the main thread is on #291.
With that in mind, this issue shouldn't have been opened in the first place.

**Comment by SGevorg** [comment]
@arsengit I suggest to reopen this and mark as duplicate with the main thread on #291 .
We can pitch the UI looks to @ashutoshsaboo and other users there under that thread and once it makes sense, go ahead and do it.

**Comment by arsengit** [comment]
Makes sense @sgevorg, reopening this issue. The main thread is #291. Please track the progress there too.

**Comment by arsengit** [comment]
Makes sense @sgevorg, reopening this issue. The main thread is #291. Please track the progress there too.

**Comment by ashutoshsaboo** [comment]
Posted some ideas over here: https://github.com/aimhubio/aim/issues/291 .
