### ISSUE TITLE
[Bug] Plotly Figures don't render to correct scale in Aim

### ISSUE THREAD

**Issue by ashutoshsaboo** [aimhubio/aim#1525]
## 🐛 Bug

Figures created with plotly and when logged with Aim.figure are producing weird results and not rendered correctly on Aim ui as well as not zooming in/out/exporting in correct scale. 

See screenshots below: 

* As rendered on Aim UI (below x axis title is redacted): ![Screenshot 2022-03-15 at 9 29 13 PM](https://user-images.githubusercontent.com/9900945/158419977-25e126f1-2869-4dc2-8a80-feda7f1cc825.png)
* Exported image from plot (below x axis title is redacted): ![newplot](https://user-images.githubusercontent.com/9900945/158419904-24fa7c6e-df20-491b-bcc5-017003e6d906.png)
* As rendered on Aim UI with zoom out (Title legends go all over the place): ![Screenshot 2022-03-15 at 9 29 21 PM](https://user-images.githubusercontent.com/9900945/158419970-8fda7210-178d-4440-ab24-8bad19060b99.png)
* As rendered on Aim UI with zoom in (Title legends go all over the place): ![Screenshot 2022-03-15 at 9 29 32 PM](https://user-images.githubusercontent.com/9900945/158419961-17b23c80-5664-467b-b2e4-701a0a3c8641.png)

### To reproduce

Use same code from here - https://stackoverflow.com/a/60863044/4402874 to plot a confusion matrix with plotly and log with Aim.figure. 

### Expected behavior

Figured must have rendered correctly as expected. 

### Additional context

cc: @SGevorg

**Comment by ashutoshsaboo** [comment]
If there's anything wrong with the code in the stackoverflow link (https://stackoverflow.com/a/60863044/4402874) that I pasted above, please feel free to post the correct snippet to correct for this behaviour.

**Comment by Hamik25** [comment]
Hi @ashutoshsaboo thanks for reporting this!

At first could you please look at example @devfox-se

**Comment by devfox-se** [comment]
I think this is plotly renderer issue that we cannot handle, I have exported HTML content right from the plotly object and it still behaves the same way as described in this issue.

[untitled.html.zip](https://github.com/aimhubio/aim/files/8255929/untitled.html.zip)

**Comment by ashutoshsaboo** [comment]
Thanks, but in that case is there any workaround i can do to not cause the weird scaling issue on Aim? @devfox-se If yes, and if you could please any code snippet for the same?

**Comment by devfox-se** [comment]
I don't think there is any workaround for this, it's completely out of Aim scope, @roubkar thoughts?

**Comment by ashutoshsaboo** [comment]
I mean any workaround to log it differently from plotly? Or are you saying plotly figures are completely not supported by Aim at all, and i will have to move to matplotlib?

**Comment by arsengit** [comment]
Hey @ashutoshsaboo, I just opened a draft pr to fix plotly figures rendering issue.

**Comment by ashutoshsaboo** [comment]
Thanks so much! Will the same code (from the above stackoverflow link - https://stackoverflow.com/a/60863044/4402874) work as-is with Aim now, or should I make any changes to log figures differently from plotly? In case if you were able to reproduce the same with your fix in place @arsengit ?
