### ISSUE TITLE
Add profiler to have insight on api performance

### ISSUE THREAD

**Issue by devfox-se** [aimhubio/aim#1526]
## 🚀 Feature

To have better understanding about performance and bottlenecks of our apis <-> storage communication we need to embed a profiler that will log performance of the system on the go

### Motivation

The logs will help us to troubleshoot users complains about api performance

**Comment by ashutoshsaboo** [comment]
Hi @devfox-se, Will this introduce telemetry to Aim's servers or any third party servers of any sort? If yes, please add support to completely disable it for users who don't prefer for remote logging of any sort. Or will it run completely locally?

**Comment by devfox-se** [comment]
@ashutoshsaboo nothing is logged to anywhere, all data will be stored locally and only be accesable by the end user. Also the profiler is disabled by deafult, we might ask the end user to enable it and provide the results for troubleshooting the issue he/she is facing
