### ISSUE TITLE
Incorrect Query for reserved words?

### ISSUE THREAD

**Issue by uduse** [aimhubio/aim#1527]
## 🐛 Bug

Querying `run.problem.class == 'BeamSearch'` gives `Incorrect Query`. Other kinds of queries are fine. I guess this is because `class` is a python keyword?

**Comment by alberttorosyan** [comment]
@uduse thanks for reporting this. does the following query (should yield same results) also fail?
`run['problem', 'class'] == 'BeamSearch'`

**Comment by uduse** [comment]
> `run['problem', 'class'] == 'BeamSearch'`

This works. Maybe we should have a better error reported for cases like this.
