### ISSUE TITLE
Add base explorer

### ISSUE THREAD

**Issue by Hamik25** [aimhubio/aim#1537]
## 🚀 Feature

Create new explorer using base explorer instead of duplicating code on each new explorer component.

### Motivation

Currently, we have 5 different explorers. Many of these explorers have the same UI component compositions and the same logic. The issue is all these explorers have been implemented in different ways there are no shared logic and UI components. The motivation is to avoid code duplications and implement the same logic in different ways.

### Pitch

Creating a new explorer should become an easy and faster process for each contributor. It will become easy to avoid code duplication, implement the same logic in different ways, bug fixing, redesign, new feature shipping will become faster and will be solved performance issues in data processing and rendering blocks.

**Comment by gorarakelyan** [comment]
related to #1730. closing as a duplicate
