### ISSUE TITLE
Sequence name is missing from the text tracking example

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#1567]
## 📚 Documentation

Sequence name is missing from the text tracking code example.

https://aimstack.readthedocs.io/en/latest/quick_start/supported_types.html#text-tracking-with-aim

<img width="381" alt="image" src="https://user-images.githubusercontent.com/13848158/159881266-08909d78-8926-44b7-ac75-1c630cc1519b.png">

**Comment by Arvind644** [comment]
Please assign me this task

**Comment by gorarakelyan** [comment]
marking as resolved ✅
