### ISSUE TITLE
Run name not visible in delete runs popover and longer names need to have text warping to see full names easily (along with the current hover to see full name)

### ISSUE THREAD

**Issue by ashutoshsaboo** [aimhubio/aim#1593]
## 🚀 Feature

In the delete runs popup, the run time is shown but the run name isn't shown making it difficult to infer which run exactly is being deleted. Can both run name and run timestamp (which is already present along with expt name) in the same?

Also, I noticed for longer expt/run names - the delete runs popup doesn't show the full name (I know it's visible on hover). If possible, can there be some sort of text warping (i.e, have fixed width, but make height dynamic based on amount of text content like Excel does) in the delete runs popup to see the full expt name/run name in the same along with the show full text on hover (please don't remove this) that is in place currently? Same is also happening in the experiments popover (screenshot that I had attached above), if possible please do it there too.

The reasoning is simple: It makes it much easier to see full names in one go while scrolling rather than hovering over each one-by-one.

### Additional context

More context: https://github.com/aimhubio/aim/issues/1426#issuecomment-1080409150 : @VkoHov

**Comment by VkoHov** [comment]
Hey @ashutoshsaboo, thanks for opening this issue. Looking into it.

**Comment by VkoHov** [comment]
Hey @ashutoshsaboo, this feature was released with v3.9.0, please try it out and let me know if it works as expected.
