### ISSUE TITLE
Params Y-axis Labels

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#1594]
## 🚀 Feature

Better params y-ticks.

### Motivation

Plotting each point makes it laggy and hard to read.

### Pitch

The numeric y-axis of params should have a limited number of ticks that are easy to read, instead of plotting every single data point.

### Alternatives

If the params values range from 0.5 to 1.2, just have a few ticks within this range, and the points can fall between those ticks. 

### Additional context

![image](https://user-images.githubusercontent.com/22674819/160454744-7f5ee112-846b-4be4-83ce-ee330403bc06.png)

**Comment by KaroMourad** [comment]
Hey @MohdElgaar,
Thank you for reporting the issue. Working on it.

**Comment by KaroMourad** [comment]
Hey @MohdElgaar,

The fix for this issue has been shipped with v3.9.0
To upgrade please run `pip install aim --upgrade`
