### ISSUE TITLE
Params grouping affects sort

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#1595]
## 🚀 Feature

Params grouping should not over-ride sort when plotting.

### Motivation

Some params need to be sorted globally, despite groupings, like final accuracy.

### Pitch

Sorted plotted points are sorted globally, not in groups.

### Alternatives

N/A

### Additional context

You see here, items are grouped by "curr", so, the "acc" is not sorted properly, it's only sorted in groups.
![image](https://user-images.githubusercontent.com/22674819/160455395-872fcace-1b4a-4166-8a8b-b2ead6127269.png)

**Comment by KaroMourad** [comment]
Hey @MohdElgaar, 
Thank you for reporting the issue, working on it.

**Comment by KaroMourad** [comment]
Hey @MohdElgaar,

The fix for this issue has been shipped with v3.9.0
To upgrade please run `pip install aim --upgrade`
