### ISSUE TITLE
[Bug] Runs table not loading after 2-3 pages of results

### ISSUE THREAD

**Issue by ashutoshsaboo** [aimhubio/aim#1605]
## 🐛 Bug

Runs table not loading after 2-3 pages of results (45 runs in each pagination call).

### To reproduce

Described above log large number of runs try to scroll down on runs table page.

### Expected behavior

All runs should load as expected.

**Comment by rubenaprikyan** [comment]
@ashutoshsaboo is the fix validated ? let's close this issue if yes.

**Comment by ashutoshsaboo** [comment]
@rubenaprikyan yes opens up fine for now, will re-open and report if I see a similar issue again. Thanks so much for a prompt fix! :D
