### ISSUE TITLE
The RUNS EXPLORER shows nothing

### ISSUE THREAD

**Issue by svmsunny** [aimhubio/aim#1617]
## 
I installed the AIM on Ubuntu with the guide https://aimstack.readthedocs.io/en/stable/quick_start/setup.html, and run the script of the Demo.

The statics page shows like this, there are two Experiments and one Run.
<img width="1138" alt="截屏2022-04-02 下午6 45 36" src="https://user-images.githubusercontent.com/22258550/161379734-a2d1ecd4-d4e0-4887-a5c8-7b71aabe76b6.png">

But the RUNS EXPLORER page shows nothing, I do not know what happened.
<img width="1143" alt="截屏2022-04-02 下午6 45 46" src="https://user-images.githubusercontent.com/22258550/161379747-669cf772-d397-42e1-a83e-a082ac414a2a.png">

But I can successfully use AIM on the Mac.  Is there anyone who can help me? Thanks!

**Comment by roubkar** [comment]
Hey @svmsunny , thanks for reporting this.
Can you please check whether there are some error logs in terminal?

**Comment by svmsunny** [comment]
Thanks for your reply.

I ran the aim up in debug mode, and the logs in the terminal are shown below, no error logs can be seen.

<img width="1151" alt="截屏2022-04-07 上午11 06 30" src="https://user-images.githubusercontent.com/22258550/162112464-84872e27-964d-4302-9eb0-1291a4d04d5f.png">
<img width="853" alt="截屏2022-04-07 上午11 06 00" src="https://user-images.githubusercontent.com/22258550/162112476-90ff831f-bdbb-4470-b530-81a56339d668.png">

Whether the IP address is correct?  My host IP is different from IP 172.27.25.151.

**Comment by svmsunny** [comment]
The problem is solved, the version (79.0.3945.117) of Google Chrome on Windows is too low. I updated Chrome to version 100.0.4896, and the RUNS EXPLORER shows the information normally.

**Comment by gorarakelyan** [comment]
closing the issue as it is resolved
