### ISSUE TITLE
Follower?

### ISSUE THREAD

**Issue by RamiSJ12** [aimhubio/aim#1626]
## ❓Question
where and how do let the people on GitHub see my issues? I have posted many issues but no one helping to pull requests. please advice.

**Comment by devfox-se** [comment]
Hi @RamiSJ12 could you please post some of your issues URL's here?

**Comment by RamiSJ12** [comment]
You can find it under my repositories please

**Comment by SGevorg** [comment]
Hi @RamiSJ12,  this seems to be irrelevant in the Aim context. Closing this issue
