### ISSUE TITLE
Handle deprications in Pytorch-Lightning API

### ISSUE THREAD

**Issue by djwessel** [aimhubio/aim#1660]
## Proposed refactoring or deprecation

Rename `AimLogger.close` to `AimLogger.finalize`.

### Motivation

As of PL v1.5.0, the `LightningLoggerBase.close` method has been depreciated in favor of `LightningLoggerBase.finalize`.

https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.loggers.base.html#pytorch_lightning.loggers.base.LightningLoggerBase.close

**Comment by arnauddhaene** [comment]
Fixed yesterday by [this PR](https://github.com/aimhubio/aim/pull/1743).
