### ISSUE TITLE
How to display GIF in Aim ?

### ISSUE THREAD

**Issue by mantle2048** [aimhubio/aim#1675]
## ❓Question
I'm recording an experiment of Reinforcement Learning.

I saved a rendered trajectory (a numpy array) as a GIF image through PIL and saved it locally which can be played normally.

I want to save the GIF to `Aim Run`. Then I convert the GIF to `aim.Image` and track it through the following codes.

``` python
gif_path = './trajectory.gif'
aim_image = aim.Image(image=gif_path, format='gif')
aim_run.track(value=aim_image, name=name, step=step_, context=context)
```

However, in the `Aim UI`, I found that GIF cannot be played normally, that is, it becomes a static picture (but it is still in GIF format)

By viewing the source code,  I found that Aim saved the GIF (type: `PIL.GifImagePlugin.GifImageFile`) to BytesIO and converted it to a [BLOB](https://github.com/aimhubio/aim/blob/main/aim/sdk/objects/image.py#L161) object.

Is this because `BLOB` object may not store GIF properly? Is there any way to save GIF to `Aim Run` and play it normally in `Aim UI`?

**Comment by devfox-se** [comment]
Hey @mantle2048

That's a good question and nice feature to have actually!
Unfortunately we do not support gifs atm, but I would appreciate you to open issue on this so we can deliver it in near future:)

**Comment by mantle2048** [comment]
Thanks for your reply. I have gradually transferred from Tensorboard to Aim and hope to see GIF or video records in the future !

**Comment by devfox-se** [comment]
Hi @mantle2048 

I have some draft ready to support animated GIFs in Aim. Results are represented in the video I shared, do you think it suits your needs and it's something you have been asking for ?

https://user-images.githubusercontent.com/48801049/165620344-364134c3-9b9e-49c6-8556-808ce0aaaff2.mov

**Comment by mantle2048** [comment]
Hi @devfox-se 

Sorry for the late reply. The demo looks very cool ! For me, this demo suits my needs. 

In an experiment, I have to record dozens of GIFs to compare the performance during training, so it would be better if `Aim` could put all GIFs with the same tag together and switch through a slider.  Just like the video below.

https://user-images.githubusercontent.com/37854077/165662295-940c6f55-0865-4f95-bf95-00f7acafc61d.mp4

**Comment by devfox-se** [comment]
Hi @mantle2048 

Thanks for your comment! As for now we do not have the exact sliding capability shown in the video, but it is sure a nice feature to have. You can open a separate issue/feature-request for that :)

As for now I am closing this question and will open a new feature-request to cover the GIF feature.

**Comment by kaimo455** [comment]
> Hi @mantle2048
> 
> I have some draft ready to support animated GIFs in Aim. Results are represented in the video I shared, do you think it suits your needs and it's something you have been asking for ? Could you share your use-cases ?
> 
>  Screen.Recording.2022-04-27.at.23.53.46.mov

He @devfox-se, the video is quit interesting and could you please provide some hints how to implement that? Is that sort of work around and how to do that?
