### ISSUE TITLE
Remote tracking client heartbeat

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#1686]
## 🚀 Feature
Implement heartbeat functionality so the remote tracking server can detect cases when client is disconnected (process killed, spot instance died, network outage, etc.) and separate such cases from one where client doesn't send any request for a long period of time (hours, days). Once such case is detected, server should close/finalize all the resources open for that client connection.

### Motivation
If the remote tracking client doesn't cleanup resources properly, run Containers and other resources might stay occupied for a prolonged period of time. As a result, Run state will not be reflected correctly. This also affects performance since data for Runs in progress cannot be retrieved from index db.

### Pitch
Check if gRPC SDK provides heartbeat functionality and is it possible to use in client applications. Otherwise, implement heartbeat as a "normal" RPC call.

### Alternatives
Look for inspiration to other tools, particularly ones that are used as a transport in distributed systems.

### Additional context
https://github.com/aimhubio/aim/tree/main/aim/ext/transport transport implementation (gRPC-based) for Remote tracking server
https://github.com/aimhubio/aim/blob/main/aim/sdk/run.py Run object, used to track/log data and read it from storage.
https://github.com/aimhubio/aim/blob/main/aim/storage/rockscontainer.pyx implementation of `Container` based on `rocksdb`. manages resources in write-mode.
https://github.com/aimhubio/aim/blob/main/aim/ext/cleanup/__init__.py utility for resource management and graceful shutdown

**Comment by ispequalnp** [comment]
Adding an option in the server `option = [('grpc.keepalive_timeout_ms', ...)]` is a quick find, but need to find how to have it trigger a cleanup (maybe onDone listener)

**Comment by alberttorosyan** [comment]
@ispequalnp this seems to be a possible approach. what the configuration should be to not break the retries implementation?
and is it possible to diff. failure from normal exit? in the future we might want to reflect it as a Run status.
