### ISSUE TITLE
Pylance reports code is unreachable

### ISSUE THREAD

**Issue by uduse** [aimhubio/aim#1702]
## 🐛 Bug

**![image](https://user-images.githubusercontent.com/4717005/165369539-2fa4ea9d-096e-4886-a553-c4171431daf2.png)**

Pylance reports code is unreachable after creating an `Repo` instance. I believe this is due to the incorrect type hints in the `Repo` class.

Pylance sees `read_only` is a `bool`, so the error is always raised and the instantiation is believed to be never successful.

**Comment by gorarakelyan** [comment]
@uduse this was shipped with Aim 3.10.0. Thanks for your contribution 🚀 
Closing the issue accordingly.
