### ISSUE TITLE
Multiple declaration of Run object does not track in remote tracking environment

### ISSUE THREAD

**Issue by ptaejoon** [aimhubio/aim#1725]
## 🐛 Bug

On remote tracking environment, if aim.Run is declared in for loop, script only tracks very first value.
Even the run is declared with same configuration (same run_hash, experiment, repo), it is not recorded (more specifically, it is not 
shown at web page. Didn't check whether the value is saved in sqlite) 

```python
  for data in dataFromStorage:
    run_id = data.extractRunId()
    url = data.extractURL() # url keep change per row
    run_inst = aim.Run(run_hash=run_id, ... , repo=f"aim://{url}"
    run_inst.track( ... )
  #this don't work. only save first row.
  
  somedict = dict()
  for data in dataFromStorage:
    run_id = data.extractRunId()
    url = data.extractURL() # url keep change per row
    if run_id not in somedict.keys():
      somedict[run_id] = aim.Run(run_hash=run_id, ... , repo=f"aim://{url}"
      run_inst = somedict[run_id]
    else:  
      run_inst = somedict[run_id]
    run_inst.track( ... )
  #this work. But I'm worrying about connection lost on dict's value and memory overflow if there are too many connection in dictionary
```
### To reproduce
try this
```python
# this will not save other values
for step in range(10):
    a = aim.Run(run_hash="new3",experiment="ababc",repo="aim://url")
    a.track(random.random(), name='loss', step=step, context={"subset": "train"})



# this work
a = dict()
a["a"] = aim.Run(run_hash="new3",experiment="abab", repo="aim://url")
a["b"] = aim.Run(run_hash="new2",experiment="abab", repo="aim://url")
    
for step in range(10):
    # Log metrics
    
    a["a"]['hparams'] = {
    'learning_rate': 0.01,
    'batch_size': 32,
    }
    a["a"].track(random.random(), name='loss', step=step, context={"subset": "train"})
    a["b"].track(random.random(), name='acc', step=step, context={"subset": "train"})

```
if I run code below:
```python
    for step in range(10):
        c = aim.Run(run_hash="new5",experiment="abab", repo="aim://url")
        c.track(random.random(), name='loss', step=step+10, context={"subset": "train"})
        c.track(random.random(), name='acc', step=step+10, context={"subset": "train"})
```

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/17878758/166629452-3eeccdcd-8538-4817-9c8a-2368e9e5ac04.png">
result will be like this. Even I ran track method 10 times, only first value is saved. (two values saved at first iteration)

### Expected behavior
https://aimstack.slack.com/archives/C02V1DJV2BH/p1651642502822489
I'm wondering is it not recommended to declare aim.Run multiple time (even for same one) or is it just a bug?
To solve this, I created dictionary which save each Run object as value and call it when it is needed. What I'm curious about is if it is okay for remote tracking environment. Maybe there will be connection timeout if too much time has passed out and create an error when I'm trying to reconnect it through same Run object

1. If it is not convention to call Run object outside loop, supporting multiple declaration will be quite useful.
2. If it is convention, I'd like to know whether it is safe against network connection, and it should be safe. Otherwise, it will be good to have connection option per aim.Run Object

### Environment

- Aim Version  3.9.2
- Python version 3.8.10
- pip version 20.3.1
- OS (e.g., Linux) mac monterey
- Any other relevant information

**Comment by gorarakelyan** [comment]
Resolved with 3.9 version. @ptaejoon please feel free to reopen this issue in case of any troubles with logging multiple runs.
