### ISSUE TITLE
PyTorch LightningLoggerBase.close deprecated in v1.5

### ISSUE THREAD

**Issue by arnauddhaene** [aimhubio/aim#1742]
## 🐛 Bug

The PyTorch Ligthning Logger integration still relies on `LightningLoggerBase.close` while it has been deprecated in PL v1.5 and will be completely removed in PL v1.7.

### To reproduce

Run the [example](https://github.com/aimhubio/aim/blob/main/examples/pytorch_lightning_track.py).

### Expected behavior

The following deprecation warning:

> LightningDeprecationWarning: `LightningLoggerBase.close` method is deprecated in v1.5 and will be removed in v1.7. Please use `LightningLoggerBase.finalize` instead.

### Environment

- Aim Version: 3.9.3
- Python version: 3.8
- pip version: 21.2.4
- OS: Linux
- PyTorch version: 1.10.2
- PyTorch Lightning version: 1.6.3

### Additional context

I believe one would simply need to change [this call](https://github.com/aimhubio/aim/blob/2963e9503a2b53883ea95c1fb93db00d06b9aeb0/aim/sdk/adapters/pytorch_lightning.py#L119) to 

```
    @rank_zero_only
    def finalize(self) -> None:
        super().finalize()
        if self._run:
            self._run.finalize()
            del self._run
            self._run = None

    def __del__(self):
        self.finalize()
```

**Comment by mihran113** [comment]
duplicates #1660
