### ISSUE TITLE
Runs with run_hash contraining "::" fail.

### ISSUE THREAD

**Issue by manuel-delverme** [aimhubio/aim#1810]
## 🐛 Bug

Runs with run_hash contraining "::" fail.

**Comment by roubkar** [comment]
Hey @manuel-delverme, thanks for reporting this issue.

I see that the single run page is failing to open. Have you seen any issues other than that?

**Comment by manuel-delverme** [comment]
Nope

**Comment by arsengit** [comment]
Hey @manuel-delverme, thanks for reporting. This fixing has been shipped with v3.10.3.
To upgrade please run pip install aim --upgrade
