### ISSUE TITLE
Delete modal renders off

### ISSUE THREAD

**Issue by manuel-delverme** [aimhubio/aim#1811]
## 🐛 Bug
![image](https://user-images.githubusercontent.com/1309922/170844898-c0768315-c89d-4e7e-92de-b93c518e3a33.png)

### To reproduce

Select a run in the UI:
http://127.0.0.1:43800/runs

### Expected behavior

Text should not overflow

### Environment

Aim v3.10.2

**Comment by roubkar** [comment]
Hey @manuel-delverme, thanks for reporting this issue, looking into it.

**Comment by VkoHov** [comment]
Hey @manuel-delverme, thanks for reporting. This fixing has been shipped with `v3.10.3.`
To upgrade please run `pip install aim --upgrade`
