### ISSUE TITLE
Can not log ints for float metrics.

### ISSUE THREAD

**Issue by manuel-delverme** [aimhubio/aim#1817]
https://github.com/aimhubio/aim/blob/bd20a70091a84e64f065d9bf1336cedeefbb423e/aim/sdk/utils.py#L77-L86

int should be able to implicitly cast to float, see
https://numpy.org/doc/stable/reference/generated/numpy.can_cast.html#numpy-can-cast

**Comment by alberttorosyan** [comment]
@manuel-delverme thanks for reporting this issue. `int` -> `float` casting is definitely should be supported.
It will make sense to also issue a warning when doing such conversion.

**Comment by gorarakelyan** [comment]
@manuel-delverme the issue has been fixed and released with Aim v3.11.1 ✅

**Comment by gorarakelyan** [comment]
Please feel free to reopen this issue if the bug appears again
