### ISSUE TITLE
Deleting runs/experiments in a bulk.

### ISSUE THREAD

**Issue by osoblanco** [aimhubio/aim#188]
Currently, the only way to delete the run(s) is by using the CLI. The thing is that as far as I understand you have to delete the runs 1 by 1, i.e. :

```
 aim experiment rm -n experiment_name
```

It would be very nice to have functionality like 

```
 aim experiment rm -rf *

or

 aim experiment rm -n run1* (For specific batches of runs)
```

Taking regexp like expressions to find the runs and delete/archive them.

It would also be very helpful to have a "delete by date" type of functionality. I think it should also be easy to use AimQL to find experiments and delete them in the same line. I.E.

```
aim experiment rm ("metric-loss" , score_1, l_reg_1 if dataset.dataset_run==FB15K)
```
Of course, I would love to see a simple deletion/archive button in frontend as well.

**Comment by gorarakelyan** [comment]
Hi @osoblanco,

Thanks for feedback. The run soft delete feature has been added (#196) so you can easily archive runs from the [UI](https://github.com/aimhubio/aimde/pull/76). However the soft delete (archive) is not available via CLI - in our pipeline and will be added in near future.
