### ISSUE TITLE
Ability to set y-axis scale for line charts on UI

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#1918]
## 🚀 Feature

Ability to set y-axis range/scale on Metrics Explorer.

### Motivation

When visualizing hundreds of plots it's easy to mistake two similar shapes for the same plots.

For example: `metric_a = [0.1, 0, 0.1]` and `metric_b = [0.9, 0, 0.9]` would initially look the same. Enabling an ability to set y axis range to `[0, 1]` for all the figures would align metrics on the given range and help to easily distinguish the plots from each other.

### Pitch

Adding two inputs to define min and max values of y axis range in Metrics Explorer. Once set, all the plots will be aligned on the given range.

Input form:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/13848158/176129044-92360bbf-f0cc-401e-b5ad-ff9f4648619d.png">

Without fixed y-axis range:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/13848158/176132015-1b6601d4-2302-46b8-aca3-97c6d66e30b2.png">

With fixed y-axis range:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/13848158/176132094-ae001f78-5ff2-4ff2-94dc-34bb7594a32f.png">

**Comment by KaroMourad** [comment]
Added ability to set both x and y axes range manually
