### ISSUE TITLE
Filtering runs by metric values (e.g. run.loss > 0.001)

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#1922]
## 🚀 Feature

Ability to query runs by metric values via SDK and on Aim UI.

### Pitch

Extend Aim query language to enable accessing metrics aggregated/reduced values like `last`, `min`, `max`, etc.

Example:
`run["loss", {"subset": "train"}].last < 0.001`
`run["loss", {"subset": "train"}].max < 0.01`

More options like steps or epochs count can be exposed as well:
`run["loss", {"subset": "train"}].steps > 100`
`run["loss", {"subset": "train"}].epochs < 5`

### Alternatives

Consider enabling more user-friendly interface compared to `run["loss", {"subset": "train"}]`, as it looks a bit complicated and might be hard to be adopted by new users.

**Comment by mihran113** [comment]
The final interface for querying runs by metric values:
```
run.metrics['loss', {'subset': 'test', 'subtask': 'nmt'}].last < 0.1
run.metrics['loss'] == run.metrics['loss', {}]
```
