### ISSUE TITLE
Run Params page hangs when you log very big hyper parameters

### ISSUE THREAD

**Issue by Sharathmk99** [aimhubio/aim#1994]
### To reproduce

Tried logging config dict which is very big, like more than 2000 lines of yaml file and file size of 100KB. Run Params screen hangs and takes more than 10secs to scroll.

### Expected behavior

Expect smooth scroll. 

### Environment

- Aim Version (e.g., 3.0.1)
- Python version
- pip version
- OS (e.g., Linux)
- Any other relevant information

**Comment by Sharathmk99** [comment]
Just to give some more context, `Run Params` under `Overview` work perfect.

**Comment by gorarakelyan** [comment]
@Sharathmk99 we constantly optimize both storage and UI to handle large number of runs, params, metrics, etc. Thanks for raising this issue! Will prioritize it for this week!
@roubkar could you please look into this?

**Comment by roubkar** [comment]
Hey @Sharathmk99, looking into this.

**Comment by roubkar** [comment]
Hey @Sharathmk99, the fix for this issue has been shipped with `v3.13.4`.
To upgrade please run `pip install aim --upgrade`

**Comment by gorarakelyan** [comment]
Closing this issue. @Sharathmk99 pls feel free to reopen this, if there are still any perf issues on the run page.
