### ISSUE TITLE
Long metric name doesn't look good on UI

### ISSUE THREAD

**Issue by Sharathmk99** [aimhubio/aim#1997]
## 🐛 Bug

We have a long metric name which is really long, but UI looks names are overlapping. Possible to handle somehow?

![image](https://user-images.githubusercontent.com/3970340/180880862-36daa2e4-96f2-4903-a7ad-f408611cc427.png)

### To reproduce

Log metrics with long name which is more than 256 char.
### Environment

- Aim Version (e.g., 3.0.1)
- Python version
- pip version
- OS (e.g., Linux)
- Any other relevant information

**Comment by roubkar** [comment]
Hey @Sharathmk99, looking into this and will try to fix it ASAP.

**Comment by Sharathmk99** [comment]
@roubkar Thank you.

**Comment by gorarakelyan** [comment]
@Sharathmk99 the issue has been fixed and released with Aim v3.12.1 🚀

**Comment by Sharathmk99** [comment]
Thank you so much @gorarakelyan!!
