### ISSUE TITLE
Loading metrics takes more time to load around 300 metrics

### ISSUE THREAD

**Issue by Sharathmk99** [aimhubio/aim#1998]
## 🐛 Bug

Converted existing tensorboard log which has more than 300 metrics and loading the all 300 odd metrics for a run took more than 4 seconds, I think it will take more time when we compare two run of same size.

![image](https://user-images.githubusercontent.com/3970340/180881711-8ed3ffe6-89d3-4a7b-b956-aaa6ae3aa81e.png)

### To reproduce

Log large number of metrics more than 300

### Expected behavior
Loading time should be fast

### Environment

- Aim Version (e.g., 3.0.1)
- Python version
- pip version
- OS (e.g., Linux)
- Any other relevant information

**Comment by Sharathmk99** [comment]
One idea to improve speed is to show couple of metrics and paginate and provide search based on metrics name.

**Comment by gorarakelyan** [comment]
Thanks for the feedback @Sharathmk99! 

I wonder whether:
- it happens often when you need to look at **all the metrics** of the runs?
  - What type of insights you seek?
  - Could it be helpful in terms of comparison of several runs or are you exploring just a single run?

**Comment by Sharathmk99** [comment]
@gorarakelyan Our user's normally look into some of the charts, but we are not sure which are those.. If we paginate and provide search that should handle this. Open for your suggestions..

Yes we want to compare across runs, I have opened another ticket to easily select all metrics.

**Comment by roubkar** [comment]
Hey @Sharathmk99, we're going to implement `load on scroll` functionality here, so the performance will be improved as much as for the paginated version, even more, only metrics visible in the viewport will be loaded depending on your screen size.

**Comment by Sharathmk99** [comment]
@roubkar that makes lots of sense. Looking forward to test. Do you plan to add search by metrics name as well?

**Comment by roubkar** [comment]
Hey @Sharathmk99, searching by metrics name seems to be an additional feature request.
Could you open a separate issue for it?

As an alternative, I can suggest that the browser `find` command will be working.

**Comment by roubkar** [comment]
Hey @Sharathmk99, this issue is resolved in v3.12.2.
To upgrade please run `pip install aim --upgrade`

**Comment by gorarakelyan** [comment]
closing the issue, as the fix was shipped with 3.12.2. @Sharathmk99 please feel free to reopen this if there are still performance issues

**Comment by Sharathmk99** [comment]
Thank you so much. I’ll test and let you know the feedback
