### ISSUE TITLE
Run context manager

### ISSUE THREAD

**Issue by JesseFarebro** [aimhubio/aim#2022]
## 🚀 Feature

It would be really nice to have a context manager on Run to cleanup all allocated resources. Something like:
```py
class Run:
    def __enter__(self) -> "Run":
        return self

    def __exit__(self) -> None:
        # Perform some other cleanup
        self.close()
```
which would allow for:
```py
with Run(...) as run:
    ...
```

### Motivation

Most objects that need to do some kind of cleanup will provide a context manager-like API. Currently, the Run object doesn't provide this.

**Comment by gorarakelyan** [comment]
@JesseFarebro good call!
@mihran113 I remember we had a discussion on this a while ago, were there any blockers? If no, I guess this could be quickly added, right?

**Comment by mihran113** [comment]
@gorarakelyan that was one of the initial thoughts when implementing the 3rd version of `aim`. But we abandoned that idea to  have a more user-friendly interface with resource auto-cleanup.
@JesseFarebro can you please describe your use case a little more? 
If the concern is to release the unnecessary resources `run.close()` will do the trick in that case. In any other cases (e. g. exceptions, `ctrl-c`, etc.) auto-cleanup will handle those.

**Comment by JesseFarebro** [comment]
@mihran113 I see. I wasn't aware of auto-cleanup. When the docs didn't suggest using a context manager I was assuming I had to do some kind of cleanup myself. I also misunderstood what `run.close()` is doing.

I'll go ahead and close this, thanks!
