### ISSUE TITLE
Installation of aim with pip fails 

### ISSUE THREAD

**Issue by MichalZnalezniak** [aimhubio/aim#2024]
## 🐛 Bug

Installation of aim with pip fails `pip3 install aim`

![image](https://user-images.githubusercontent.com/80767000/182208096-a85b53ea-3101-4f0a-9ce6-3d93a69f2d21.png)
![image](https://user-images.githubusercontent.com/80767000/182208186-2c8448ae-b27a-45d3-9498-ed9f9d727db6.png)
![image](https://user-images.githubusercontent.com/80767000/182208227-11f1d9e6-b70c-46ae-afc1-51fe70ba4272.png)

### To reproduce
'pip3 install aim'

### Environment

- Aim Version : any
- Python 3.7
- pip version 20.1.1
- OS (e.g., Linux) Linux

**Comment by mihran113** [comment]
Hey @MichalZnalezniak. Thanks for the report, there is already an open issue for this one:
https://github.com/aimhubio/aim/issues/2019

Anyways there are binary wheels uploaded in `pypi`, in order to avoid an installation from source distribution, can I ask you upgrade your `pip` version?

**Comment by MichalZnalezniak** [comment]
@mihran113 Thanks for the quick reply. After the pip upgrade, the problem was resolved. Thanks.
