### ISSUE TITLE
Adding and removing tags directly on the Single Run page

### ISSUE THREAD

**Issue by djwessel** [aimhubio/aim#2053]
## 🚀 Feature

Currently, the workflow for adding/editing tags for a run is by finding it on one of the Explorer pages (e.g. the Metrics Explorer) and either adding/removing the tags in the tooltip. It would be beneficial to also be able to add/remove tags in the Single Run page.

### Motivation

The current workflow is rather un-intuitive and limiting.

### Pitch

Just like we can edit other aspects about the run in the Single Run page, we should be able to select which tags to associate with the run.

**Comment by roubkar** [comment]
Hey @djwessel, this feature has been shipped with `v3.14.0`.
Upgrade aim to use it: `pip install aim --upgrade`

<img width="474" alt="Screen Shot 2022-10-06 at 23 35 25" src="https://user-images.githubusercontent.com/9951653/194403571-2ed5f6e3-e60b-4a19-a0db-13212237d6d8.png">
