### ISSUE TITLE
Add column for tags in Runs Explorer

### ISSUE THREAD

**Issue by djwessel** [aimhubio/aim#2054]
## 🚀 Feature

Add a column in the Runs Explorer which shows which tags (if any) are associated with each run.

### Motivation

I want a very quick overview of which tags are associated with which runs while exploring the results of my experiments. You can go to the tags page to see the list of runs associated with a given tag, but this is out of the way and doesn't provide the overview information that you would get from including them in the Runs Explorer.

### Pitch

Add a new column called run.tags (as you can already filter by run.tags in the search bar) which visualizes all the associated tags.

**Comment by VkoHov** [comment]
Hey @djwessel. The PR has been submitted - [#2120](https://github.com/aimhubio/aim/pull/2120). It is planned to be released in the 3.14.0 version. I will make sure to let you know once it is shipped.

**Comment by VkoHov** [comment]
Hey @djwessel, this feature was released with v3.14.0, please try it out and let me know if it works as expected.

**Comment by gorarakelyan** [comment]
@djwessel closing this issue as the enhancement has been shipped. Please feel free to reopen it in case of any issues. 🙌
