### ISSUE TITLE
A like button for the run explorer

### ISSUE THREAD

**Issue by ilisparrow** [aimhubio/aim#2060]
## 🚀 Feature

A like column to be able to highligh a specific model

### Motivation
When I run multiple experiments, Sometimes it's hard to know which run was selected as the one being deployed or the best without looking into notes.

### Pitch

Get a new column in the run explorer with a start or heart button that would be associated to a run

### Alternatives

be able to display notes in the run explorer

THank you very much in advance.

**Comment by gorarakelyan** [comment]
@ilisparrow sounds great, what about displaying run tags in the runs explorer and enabling editing right from the table? Thus, an associated run may be tagged with `deployed` tag. Thoughts?

**Comment by ilisparrow** [comment]
Hello, 
Thanks, This seems faire and would solve the problem. 
Best regards, 
Ilias.

**Comment by VkoHov** [comment]
Hey @ilisparrow, this feature was released with v3.14.0, please try it out and let me know if it works as expected.

**Comment by gorarakelyan** [comment]
@ilisparrow closing this issue as the enhancement has been shipped. Please feel free to reopen it in case of any issues. 🙌
