### ISSUE TITLE
Installing aim from sources fails if required version of Cython is not installed

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#2072]
## 🐛 Bug
Unable to install aim from sources if `Cython` is not installed or installed version is different from `3.0.0a9`

### To reproduce
- Create a clean environment

```
pip install git+https://github.com/aimhubio/aim.git
```

### Expected behavior

Successfully installed aim package

### Environment

- Aim Version: src 
- Python version: any
- pip version: any
- OS: any
- Any other relevant information

**Comment by mihran113** [comment]
The reason source installation fails is that python sets paths in incorrect order, and the system path is set before the build installation path:
Output of `sys.path` during installation
```
['/root/aim', '/tmp', '/tmp/pip-build-env-ynf54h3h/site', '/usr/lib/python38.zip', '/usr/lib/python3.8', 
'/usr/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/dist-packages', 
'/tmp/pip-build-env-ynf54h3h/overlay/lib/python3.8/site-packages', 
'/tmp/pip-build-env-ynf54h3h/normal/lib/python3.8/site-packages']
```
Nothing to do here on our end.

**Comment by mihran113** [comment]
If source installation fails with a following error(due to `Cython` version): 
```
ValueError: got unknown compilation option, please remove: show_all_warnings
```

Please uninstall the existing `Cython` version, try the installation once again, and after success re-install the `Cython` version that was previously used, as `aim` uses `Cython==3.0.0.a9` as only build time requirement.
