### ISSUE TITLE
Some small features

### ISSUE THREAD

**Issue by muellerzr** [aimhubio/aim#2082]
## 🚀 Feature

Here's a list of small features I'd love to see out of Aim as I've gone through using it. Either by expectation of "I should be able to do this?" or things I'd love to be able to do

## CLI

To be able to do `-h` or `--help`. Many CLI programs work this way, and I expected aim to be quite similar, so this would be good for consistency!

## Logging:

A way for you to log multiple values in a dictionary. Prime example are metrics, e.g I currently do:

```python
for met, value in eval_metrics.items():
    run.track(value, name=met, epoch=epoch, context={"subset":"validation"})
```
But it'd be nice to just pass in `eval_metrics` (which is a k/v dict of str:value) and have all of them be logged on a single context.

I may edit this as I go along, but these were two small QOL things that I think would be nice :)

**Comment by alberttorosyan** [comment]
Hey @muellerzr!
--help should be supported out-of-box for both top-level and subcommands. What happens when you run `aim --help`?

As for the passing dict as an argument to the `track()`; this is a hood feature which we'd like to implement. Will think about UX to make sure it is consistent with the other interfaces and come back to you shortly.

**Comment by muellerzr** [comment]
--help works, I should specified just the -h part 😄

**Comment by alberttorosyan** [comment]
@muellerzr adding `-h` as a help message flag is easy. The only blocker is that for some commands we already have it used.  For example, `aim up` has `-h | --host` option.
I can add `-h` for a top-level command, but unfortunately not for sub-commands. Do you think it would make sense?

As for the dict support in `track()` method; would you mind to open a separate issue, so we can discuss the solution and track the progress there? It would help us to keep the GH clean.

**Comment by muellerzr** [comment]
Sure!

Re: sub-commands, yeah noticed that last night as I was messing with some things. Not sure then because now you'd be mixing APIs in one, and one would expect `-h` to be for help rather than the host IP. So probably not, but iteration on the idea/discussion is still good 😄

**Comment by alberttorosyan** [comment]
> Sure!
> 
> Re: sub-commands, yeah noticed that last night as I was messing with some things. Not sure then because now you'd be mixing APIs in one, and one would expect `-h` to be for help rather than the host IP. So probably not, but iteration on the idea/discussion is still good 😄

@muellerzr thanks for the feedback! If no objections, will leave the things as they now (only `--help` for help messages) to keep API consistent, and we can close this issue while tracking progress of `dict`s logging under #2087.

**Comment by muellerzr** [comment]
Yep!
