### ISSUE TITLE
Unable to export chart figure on remote aim via ssh

### ISSUE THREAD

**Issue by mantle2048** [aimhubio/aim#2083]
## 🐛 Bug

I run `aim` on a remote server,
```
aim up --port 8891
```

and forward it to local port via ssh.
```
ssh -NL 8886:localhost:8891 PC
```

But I can't export the chart figure in `Metrics Explorer`.

The `Download` button is gray and cannot be clicked.

![image](https://user-images.githubusercontent.com/37854077/185583062-fcd5befc-ce40-4efd-a478-7ded6a7cf7f9.png)

However, I can export `csv` files in `Runs Explorer`  normally.

- Aim Version: 3.12.2
- Python version: 3.7.10
- pip version: 22.2.1
- OS: Ubuntu 18.04

**Comment by KaroMourad** [comment]
Thank you for reporting the issue🙏
Looking into it.

**Comment by KaroMourad** [comment]
Hey @mantle2048,

The fix for this issue has been shipped with v3.13.0
To upgrade please run ` pip install aim --upgrade`

**Comment by mantle2048** [comment]
Thanks a lot!
