### ISSUE TITLE
Aim installation fails in GitHub actions/miniconda context, if pip<=20.2.4, cython failure

### ISSUE THREAD

**Issue by hendriks73** [aimhubio/aim#2095]
## 🐛 Bug

When trying to install Aim from a GitHub Action, using miniconda and pip<=20.2.4, installation fails.

Partial output:

```
Installing pip dependencies: ...working... ::warning::Pip subprocess error:
WARNING: Missing build requirements in pyproject.toml for aim==3.11.1 from https://files.pythonhosted.org/packages/a6/98/9aeccb650aec68978f7cf2f04f324233180fbb7d8746fbd2bd328dfc53b0/aim-3.11.1.tar.gz#sha256=176923340a609210a842d3c4761c51d83f51b2e3799329445cc803eff09b067a (from -r /home/runner/work/aim_test/aim_test/condaenv.wm7ml876.requirements.txt (line 1)).
WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
```

and:

```
Error compiling Cython file:
------------------------------------------------------------
...
        self.container.commit(batch)

    def keys_eager(
            self,
            path: Union[AimObjectKey, AimObjectPath] = (),
    ) -> List[Union[AimObjectPath, AimObjectKey]]:
             ^
------------------------------------------------------------
aim/storage/containertreeview.py:110:13: Compiler crash in AnalyseDeclarationsTransform
```

Why pip 20.2.4? Because the *new* resolver introduced in pip 20.3 is really picky and leads to lots of version clashes between Aim and other packages we are using. So pip>=20.3 is unfortunately no option (please consider defining your dependencies less strictly if possible).

Perhaps Aim's `pyproject.toml` is sub-optimal in that no build backend is specified?

### To reproduce

Please see the demo repo https://github.com/hendriks73/aim_test

Note that, as soon as you change the pip dependency in `environment.yml` to 21 or higher, the issue disappears.

### Expected behavior

Aim is successfully installed.

### Environment

- Aim Version 3.11.1
- Python version 3.8.8
- pip version 20.2.4 (or earlier)
- OS Ubuntu 20.04
- This is under GitHub Actions

**Comment by alberttorosyan** [comment]
Hi @hendriks73! There's a known issue with the source installation #2072. We're working on this and plan to release the fix with the next patch release.
Meanwhile, the current release of Aim provides wheel packages generated for lower versions of pip. May I ask you to try the installation with latest aim release?

**Comment by hendriks73** [comment]
Thanks for the hint!
Yes, aim==3.13.0 seems to work.

I guess we can close this issue then.

**Comment by hendriks73** [comment]
Duplicate of https://github.com/aimhubio/aim/issues/2072

**Comment by gorarakelyan** [comment]
closing this issue as a duplicate. @hendriks73 will keep you updated on the original issue.
