### ISSUE TITLE
Handle deprecations in PyTorch Lightning 1.7 API

### ISSUE THREAD

**Issue by djwessel** [aimhubio/aim#2105]
## Proposed refactoring or deprecation

Change imports in `aim.sdk.adaptors.pytorch_lightning` to handle deprecations in PyTorch Lightning API.

* `pytorch_lightning.loggers.base.rank_zero_experiment` -> `pytorch_lightning.loggers.logger.rank_zero_experiment`
* `pytorch_lightning.loggers.base.LightningLoggerBase` -> `pytorch_lightning.loggers.logger.Logger`

### Motivation

Some of the API in PyTorch Lightning regarding custom loggers has been deprecated in versions 1.7. The imports should be adjusted accordingly.

**Comment by gorarakelyan** [comment]
@djwessel thanks for reporting. Will make sure to release the fix with the upcoming patch releases.
btw would be happy to help in case you want to contribute!

**Comment by djwessel** [comment]
@gorarakelyan Hey, I opened a PR with the fix as it was rather quick to do. Let me know if there is anything that needs to be fixed.

**Comment by gorarakelyan** [comment]
Hey @djwessel. The fix has been shipped with Aim 3.13.1 version! Congrats on the first contribution! 🚀
