### ISSUE TITLE
Specify -h HOST for aim up

### ISSUE THREAD

**Issue by hunan-rostomyan** [aimhubio/aim#212]
Would it be possible to add a host option to `aim up` in addition to the port one? I'd like to run the server on `0.0.0.0` instead of localhost, like this:

```
aim up -p 5000 -h 0.0.0.0
```

Maybe it would be possible to take advantage of [`create_host_config`](https://docker-py.readthedocs.io/en/stable/api.html) or something along those lines...

**Comment by gorarakelyan** [comment]
Hi @hunan-rostomyan ,

Docker uses `0.0.0.0` ip by default when binding ports, so UI should be accessible on `0.0.0.0` as well.
Please try out and check if it works.

**Comment by gorarakelyan** [comment]
The ability to specify host address became available in the newer version of aim(`>=2.0.16`).

Example:
`aim up -h 127.0.0.1` or `aim up --host 127.0.0.1`

Run the following command to upgrade to the latest stable aim version:
`pip3 install aim-cli --upgrade && aim upgrade`

**Comment by gorarakelyan** [comment]
I will mark this issue as resolved and close it.
