### ISSUE TITLE
Implement the standard GRPC health checking protocol for remote tracker

### ISSUE THREAD

**Issue by jiyuanq** [aimhubio/aim#2126]
## 🚀 Feature

Implement the standard grpc health checkpoint protocol: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

### Motivation

Currently when we deploy remote tracker on k8s, there's no way to do meaningful readiness and liveness probe.
The tcpSocket probe works but it's not a meaningful probe as mentioned here: https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/
This health checking protocol will enable us to run readiness probe and liveness probe on k8s with "grpc-health-probe" tool: https://github.com/grpc-ecosystem/grpc-health-probe

### Alternatives

An alternative is to expose an additional http endpoint for readiness and liveness probe on k8s

**Comment by mihran113** [comment]
Hey @jiyuanq! The standard health grpc health checking protocol is now enabled on remote tracking server. It's been shipped with `3.15.0` release. Let us know if it gets the job done :)

**Comment by gorarakelyan** [comment]
closing this issue, as the enhancement was shipped with v3.15.0
