### ISSUE TITLE
Aim is very slow since 3.12.0

### ISSUE THREAD

**Issue by Aonnghus** [aimhubio/aim#2158]
## 🐛 Bug

I observed a huge slow down when using Aim since updating to 3.12.0. I did not have this issue with previous 3.11.2.
Launching aim up takes a bit less than 1 minute.
Creating a run tracker through Python with `aim.Run` is very long (1 to 2 minutes).
Aim UI is very slow, for instance I cannot go to the Images tab, it keeps loading and then my browser tab crashes saying "Something went wrong".
I tried on both SSD and HDD.

### To reproduce

- Install Aim 3.12.0 or greater.
- Track metrics and images in the code.
- Launch Aim UI with `aim up`.
- Launch the code.

### Expected behavior

Starting Aim UI with `aim up` shouldn't take that long, and Aim UI itself shouldn't make my browser crash.

### Environment

- Aim Version: >=3.12.0
- Python version: tested on both 3.8.13 and 3.10.7
- pip version: 22.2.2
- OS: Ubuntu

**Comment by alberttorosyan** [comment]
Hi @Aonnghus!
Sorry to hear you experience issues with performance. Does this happen on later versions as well? How big the aim repo is (number of runs, metrics, image sequences, etc.)?
Any additional detail, such as request waterfall screenshot (in case of UI slowness) or sample scripts to generate some data, would be extremely helpful. 🙌

**Comment by Aonnghus** [comment]
Hello @alberttorosyan 
Yes, the same thing is happening with versions newer than 3.12.0. Actually, I noticed the issue on the latest version to date (3.13.1), and I downgraded Aim until the problem disappeared.
Initialization of  Aim repository also takes a long time.

The repo I used is very small, I only have 1 run composed of 7 metrics, 414 images were tracked (256x256 px). System logs and stdout logs were tracked too. Parameters is a dictionary of 30 items.
What is the request waterfall? Is it the output of `aim -v up`?

I also noticed that I cannot access Aim UI while training, I have to wait for the script to complete.

Example code:
```python
import logging

import aim
import numpy as np
from tqdm import tqdm

logging.basicConfig(format="%(levelname)s:%(message)s", level=logging.DEBUG)


def dummy_dict():
    return {k: str(k) for k in range(30)}


run = aim.Run(experiment="experiment", log_system_params=True)

run["parameters"] = dummy_dict()

lr = 1e-3

for epoch in tqdm(range(100)):
    logging.info(f"======== Epoch {epoch} ========")
    logging.info("==== Training ====")

    context = {"subset": "train"}

    images_train = [
        aim.Image(
            (np.random.random((256, 256)) * 255).astype("uint8"),
            format="png",
            optimize=True,
        )
    ] * 18

    if epoch % 5 == 0:
        run.track(images_train, name="input", step=epoch, context=context)
        run.track(images_train, name="recon", step=epoch, context=context)
        run.track(images_train, name="gt", step=epoch, context=context)

    loss = np.random.rand(1)
    psnr = np.random.rand(1)
    ssim = np.random.rand(1)

    run.track(loss, name="loss", context=context)
    run.track(psnr, name="PSNR", context=context)
    run.track(ssim, name="SSIM", context=context)
    run.track(lr, name="lr", context=context)

    logging.info(f"Loss: {loss}")
    logging.info(f"PSNR: {psnr}")
    logging.info(f"SSIM: {ssim}")
    logging.info(f"Lr: {lr}")

    logging.info("==== Validation ====")

    context = {"subset": "val"}

    images_val = [
        aim.Image(
            (np.random.random((256, 256)) * 255).astype("uint8"),
            format="png",
            optimize=True,
        )
    ] * 4

    if epoch % 5 == 0:
        run.track(images_val, name="input", step=epoch, context=context)
        run.track(images_val, name="output", step=epoch, context=context)
        run.track(images_val, name="gt", step=epoch, context=context)

    loss = np.random.rand(1)
    psnr = np.random.rand(1)
    ssim = np.random.rand(1)

    run.track(loss, name="loss", context=context)
    run.track(psnr, name="PSNR", context=context)
    run.track(ssim, name="SSIM", context=context)
    run.track(lr, name="lr", context=context)

    logging.info(f"Loss: {loss}")
    logging.info(f"PSNR: {psnr}")
    logging.info(f"SSIM: {ssim}")
    logging.info(f"Lr: {lr}")
```

**Comment by alberttorosyan** [comment]
@Aonnghus, I've tried the script above on a pretty modest Linux machine (t2.medium instance with 2 CPUs and 4GB RAM), it it took ~10 seconds to execute. How long does it take to run on your side?

**Comment by Aonnghus** [comment]
I tried on another machine, launching time was very short. This part might be hardware-related (even if the specs are largely enough to run Aim).
However, I still have an issue if I go to Aim UI's URL on 127.0.0.1 and try to gather images from the corresponding sidebar tab.
My query is `run.hash == "<hash>"` and I select everything from the blue button "+ Images". Sometimes images are displayed instantly, sometimes it crashes when I try to use "Group by", and other times it doesn't display anything and my browser hangs until the webpage crashes.

**Comment by gorarakelyan** [comment]
@Aonnghus could you please submit a separate issue with additional context wrt exploring tracked images? We will try to resolve it as soon as possible.

**Comment by Aonnghus** [comment]
A bit more details about my setup: I am connecting to a remote machine through SSH, where aim is installed in a virtual env. Home directory is mounted from another machine on the same network. My code is in the home directory, but the virtual env is on a local SSD. Aim repo is stored on that same SSD. 

With version 3.11.2, everything works smoothly with my current setup. I can even have Aim repo and the virtualenv both installed in the home directory (i.e. remotely mounted) without any impact on Aim's performance.
Since upgrading Aim to a superior version, as said before, `aim up` takes a long time to launch and whenever I create a task through the Python API, it also takes a while. Using the example code I put in an earlier comment reproduces this bug.

It seems to be an hardware-related issue, but I do not understand why everything works with 3.11.2 and not newer versions.

Regarding the UI problems, I'll submit another issue as proposed by @gorarakelyan

**Comment by mihran113** [comment]
hey @Aonnghus! Sorry for the late response. Taking into consideration the fact that the performance degradation was started from `v3.12.0`, our guess is that it might have to do something with the new locking mechanism we introduced (we started to use `SoftFileLock` instead of `FileLock` for some filesystems). We have released a `dev` version of aim which forces to use `FileLock`s only if `__AIM_FORCE_USE_FILELOCK__` environment variable is set. Could you please install it and test it out to see if everything works as expected?

```
pip install aim==3.14.0.dev1
export __AIM_FORCE_USE_FILELOCK__=1
```
Then just try out your scripts and `aim up` command to see if it works fine as was with earlier versions.

**Comment by Aonnghus** [comment]
Hello @mihran113. That was it! Forcing the use of FileLock solved my performance issues. Thank you so much!

**Comment by mihran113** [comment]
Hey @Aonnghus. Glad that helped! 
One more question: have you ever encountered warnings like this when using aim version > 3.11.2? 
```
Using soft file locks to avoid potential data corruption.
```

**Comment by Aonnghus** [comment]
Yes such warnings appeared in stdout

**Comment by mihran113** [comment]
> Yes such warnings appeared in stdout

Got it. Thanks! We'll include this change in the `v3.14.0` as well, as a workaround for now.
In the meanwhile we'll try to improve the filesystem identification mechanism, as clearly `FileLock`s can be used for a case that you've described, but we still opt to use `SoftFileLock`s.

**Comment by mihran113** [comment]
hey @Aonnghus. One more question regarding your setup, what protocol did you use to mount your home directory?

**Comment by Aonnghus** [comment]
`mount` command gives the following output concerning the home directory:
`<some IP>:<some remote directory> on /home type nfs rw,nosuid,nodev,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,local_lock=none,addr=<some IP>)`

**Comment by Aonnghus** [comment]
I just installed `v3.14.0`, but the issue persists. Has the workaround been implemented as part of this release?

**Comment by mahnerak** [comment]
@Aonnghus I have couple of steps that will help us confirm the bug and fix it:
1. Stop all the processes that may use `aim` in some way:
    * Training processes
    * Aim servers (launched with `aim up ...` or `aim-watcher ...`)
2. Run `find PATH/TO/.aim -name '*.softlock'`
    * Verify that there's `.aim/locks/index.softlock`
    * Please share with us the output if possible; you can make sure that it contains no sensitive information
3. Manually remove all those '*.softlock' files
4. Please confirm that the performance became much faster

**Comment by Aonnghus** [comment]
Hi @mahnerak! I did as you said, but couldn't find any `.aim/locks/index.softlock`. Instead, there is a `.aim/locks/run_index.softlock`.
Whole output of the `find` command is as follows:
```
.aim/seqs/locks/0fddf91743dd454c8aee0824.softlock
.aim/seqs/locks/7d55cba6860445d093ee3572.softlock
.aim/seqs/locks/89a5fc80da67429fbaf830f1.softlock
.aim/seqs/locks/3dd7de7d89674084962086a8.softlock
.aim/seqs/locks/2dcd001690dc46cfab353d28.softlock
.aim/seqs/locks/12fb082c78454126b3e789f9.softlock
.aim/seqs/locks/9a9a736e08b64006b0d45242.softlock
.aim/seqs/locks/8a33791939404e6488c7b475.softlock
.aim/seqs/locks/2913dbc36dec40d8bb6ee25a.softlock
.aim/locks/run_index.softlock
.aim/meta/locks/0fddf91743dd454c8aee0824.softlock
.aim/meta/locks/7d55cba6860445d093ee3572.softlock
.aim/meta/locks/89a5fc80da67429fbaf830f1.softlock
.aim/meta/locks/3dd7de7d89674084962086a8.softlock
.aim/meta/locks/2dcd001690dc46cfab353d28.softlock
.aim/meta/locks/12fb082c78454126b3e789f9.softlock
.aim/meta/locks/9a9a736e08b64006b0d45242.softlock
.aim/meta/locks/8a33791939404e6488c7b475.softlock
.aim/meta/locks/2913dbc36dec40d8bb6ee25a.softlock
```
I removed all those files, installed `v3.14.1` but the issue is still there

**Comment by Aonnghus** [comment]
I tried to move my `.aim` folder to a `ext4` partition with `.softlock` files removed. I no longer have the warning message, however launching `aim up --repo /ext4/path` is still very long (~25 seconds)

**Comment by alberttorosyan** [comment]
@Aonnghus, the `.repo_lock` seems to be one causing long uptimes. May I ask you to run the following script and check the runtime? If it's ~ 10 seconds, than `.repo_lock.softlock` is indeed the one causing this.

```python
from aim.sdk import Repo
repo = Repo.from_path('/ext4/path/')
```

**Comment by Aonnghus** [comment]
Any news on this issue?

**Comment by alberttorosyan** [comment]
Hey @Aonnghus! We are on the way to completely re-design the locking mechanism in Aim. The fix for the performance issue related to locks will be shipped along. We target to release the new version at the end of next week.

**Comment by Aonnghus** [comment]
I just installed v3.15.1, it seems that the issue is now resolved. I'll close this issue and reopen if I find again the same behaviour while using Aim.
