### ISSUE TITLE
Can't hover on a line chart when metrics with "nan" values are tracked

### ISSUE THREAD

**Issue by tmynn** [aimhubio/aim#2199]
## 🐛 Bug

When tracking "nan" values for a metric the corresponding line chart becomes inactive. The issue mostly occurs when live-update is on.

### To reproduce

1. Start tracking some metrics with "nan" values
2. Open Metrics Explorer
3. Turn on Live Update
4. Try to hover on the chart

### Expected behavior

To be able to hover on the chart and interact with it without issues.

### Environment

- Aim Version (v3.13.4)

**Comment by KaroMourad** [comment]
Have found the same issue in Scatter plot.
Fixed the issue with separate PR.
