### ISSUE TITLE
Integration with Optuna

### ISSUE THREAD

**Issue by GeorgePearse** [aimhubio/aim#2209]
## 🚀 Feature

Optuna is one of the most popular hyperparameter optimization (HPO) frameworks. Important that Aim properly separates trials for experiments while still providing a form of grouping for the full experiment. 

Must be able to work with multi-gpu training (e.g. a trial on each GPU)

### Motivation

One of the most valuable uses of an experiment tracker is quickly sifting through the many similar runs that result from HPO

**Comment by tmynn** [comment]
hey @GeorgePearse, great suggestion! I will take it over on the next week. Also will keep you in the loop, as I believe your experience with running trainings on Optuna will be a huge help in figuring out the right integration design and experience 🙌

**Comment by tmynn** [comment]
Hey @GeorgePearse I have a great news! The Optuna integration is now available 🤩. We have created a callback to keep track of the experiments. Please take a look at the integration doc here: https://aimstack.readthedocs.io/en/latest/quick_start/integrations.html#integration-with-optuna
And feel free to let me know if there is something that we might need to add. 🙌

**Comment by gorarakelyan** [comment]
Closing the issue, as the integration has been shipped with Aim v3.15.
