### ISSUE TITLE
Pytorch lightning logs disable progressbar tracking

### ISSUE THREAD

**Issue by vikigenius** [aimhubio/aim#2211]
When using the pytorch lightning integration the logs section is completely polluted with the progressbar. How do I avoid this?

![scrot_20220928_184420](https://user-images.githubusercontent.com/12724810/192901278-1fb14a52-e1ac-4bc7-8bf8-be338cd6280c.png)

**Comment by gorarakelyan** [comment]
@vikigenius this issue may occur when two (or multiple) progressbars are streamed to stdout. Is this the case? How many progressbars are displayed in the terminal?

**Comment by vikigenius** [comment]
How do you mean multiple? There are multiple progress bars in the sense that there is one for training and one for validation, there are also a few initially for downloading models etc.

**Comment by gorarakelyan** [comment]
@vikigenius sorry for a late reply. Could you please share more details on your setup (OS, PL version, python version, ..), so we could reproduce the bug?

**Comment by vikigenius** [comment]
@gorarakelyan  Ok So I am using 

python 3.10.4
pytorch-lightning 1.7.7
aim 3.14.1

Also additionally if this is relevant I am running my aim server on a completely different machine from the training instance.

**Comment by gorarakelyan** [comment]
@vikigenius thanks. will test it out and get back to you

**Comment by gorarakelyan** [comment]
@vikigenius seems PL displays two progress bars in parallel, which brakes the functionality of capturing logs from stdout. 

https://user-images.githubusercontent.com/13848158/198581771-45133843-cd8c-410b-83f5-e0740e6702a6.mov

(you can notice two progress bars displayed at each epoch's end)

will prioritize and resolve the issue.

**Comment by gorarakelyan** [comment]
@vikigenius the fix has been released with Aim v3.15. Could you please upgrade to the latest version and check if everything works as expected?

**Comment by gorarakelyan** [comment]
Closing this issue. feel free to reopen it if the issue appears again
