### ISSUE TITLE
AttributeError: 'TrackMetricsCallback' object has no attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by jguhlin** [aimhubio/aim#225]
Also having an issue with the keras tracking callback:

```Traceback (most recent call last):
  File "GeneFindingTestingTrainedTransformer.py", line 276, in <module>
    callbacks=[csvlog, AimTracker.metrics([aobj])])
  File "/home/josephguhlin/miniconda3/envs/keras/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py",
line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/josephguhlin/miniconda3/envs/keras/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py",
line 1074, in fit
    steps=data_handler.inferred_steps)
  File "/home/josephguhlin/miniconda3/envs/keras/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2
35, in __init__
    cb._implements_train_batch_hooks() for cb in self.callbacks)
  File "/home/josephguhlin/miniconda3/envs/keras/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 2
35, in <genexpr>
    cb._implements_train_batch_hooks() for cb in self.callbacks)
AttributeError: 'TrackMetricsCallback' object has no attribute '_implements_train_batch_hooks'```

**Comment by gorarakelyan** [comment]
What version of keras(or tensorflow) are you on?

**Comment by jguhlin** [comment]
TF 2.3.0, using keras from there.

**Comment by jguhlin** [comment]
I think I did have an old version of keras installed, a fresh conda env fixes it. I did have to pip install keras (which isn't the "official" way of installing it anymore, I think) -- but it seems to be working. Running now and will let you know.

**Comment by gorarakelyan** [comment]
Great. Support for the older versions will be added today or tomorrow, thanks for pointing that out.

**Comment by gorarakelyan** [comment]
Hi @jguhlin ,

Just to let you know, the new version of `Aim` is released which supports both ` keras` and `tf.keras`.

**Tested on:**
 - TensorFlow v2.3.0
 - TensorFlow v1.14.0
 - Keras v2.3.0 + TensorFlow v1.13.1 as a backend

You can find the documentation and examples [here](https://github.com/aimhubio/aim#tensorflow-and-keras).

We also simplified integration API a bit, now you can pass `aim.tensorflow.AimCallback()` to keras callbacks list instead of `AimTracker.metrics()`. _The old API is still supported and all changes are backward compatible._

**Comment by jguhlin** [comment]
@gorarakelyan Thanks, looks great. I'll upgrade once my analyses are finished running.

Quick question(happy to open a new issue too) -- Is there a way to export the results as CSV or something? Even if it's only just "loss" or "binary_accuracy" specified manually?

**Comment by gorarakelyan** [comment]
@jguhlin Great, glad to help!

Re CSV export: we already have that feature in our pipeline and will release it soon. 
I will close this issue, feel free to open a new one.

And thanks for the feedback. It really helps us to build the right tool!
