### ISSUE TITLE
Run.metrics() is broken

### ISSUE THREAD

**Issue by Castavo** [aimhubio/aim#2256]
## 🐛 Bug

The `Run.metrics()` method is unusable. I believe it is because in the method, `SingleRunSequenceCollection`is initialised without the `seq_cls` argument.

### To reproduce

I used this short script, to try to retrieve the values from a Run:

```python
from aim import Run
import time
run = Run(experiment="test_sandbox")

for i in range(10):
    time.sleep(0.1)
    run.track(i**2, "values", 2*i, context={"type": "square"})
    run.track(2*i, "values", 2*i, context={"type": "double"})

run.report_successful_finish()

for metric in run.metrics():
    print(metric.values.sparse_numpy())
```

I got the error message: 

```
TypeError                                 Traceback (most recent call last)
<ipython-input-9-ceb5f3bfe645> in <cell line: 12>()
     10 run.report_successful_finish()
     11 
---> 12 for metric in run.metrics():
     13     metric.values.sparse_numpy()

~/.conda/envs/env_torch/lib/python3.8/site-packages/aim/sdk/sequence_collection.py in iter(self)
    120             run_view = RunView(run, self.runs_proxy_cache, self._timezone_offset)
    121             seq_view = SequenceView(seq_name, ctx.to_dict(), run_view)
--> 122             match = self.query.check(**{'run': run_view, seq_var: seq_view})
    123             if not match:
    124                 continue

TypeError: check() keywords must be strings
```

### Expected behavior

I would have expected the snippet given in the method's documentation to be functionnal.

### Environment

- Aim Version : 3.14.1
- Python version : 3.8.12
- pip version : 22.0.4
- OS (e.g., Linux) : Linux

**Comment by gorarakelyan** [comment]
hey @Castavo thanks for reporting! @alberttorosyan could you pls take a look?

**Comment by alberttorosyan** [comment]
hey @Castavo ! the issues was indeed the `seq_cls` argument not being initialized. will push the branch with the fix shortly.

**Comment by gorarakelyan** [comment]
@Castavo the fix has been shipped. could you please upgrade to the latest version and check out if everything works as expected?

**Comment by Castavo** [comment]
It does ! I am very pleased, thank you.
