### ISSUE TITLE
Remote heartbeat-watcher resource cleanup fails

### ISSUE THREAD

**Issue by ofermend** [aimhubio/aim#2287]
## 🐛 Bug

When remote heartbeat watcher tries to cleanup dead client resources the following exception is thrown:
Similar to https://github.com/aimhubio/aim/issues/2021, but this time it's in https://github.com/aimhubio/aim/blob/main/aim/ext/transport/heartbeat.py#L158. 

### To reproduce

Create a remote run, force kill the process to trigger heartbeat watcher to cleanup resources. It's not super consistent but happens after a few of these:

`RuntimeError: dictionary changed size during iteration`

### Expected behavior

No exception thrown and resource correctly removed.

### Environment

* Aim Version: 3.13.4
* Python version: 3.8.10
* pip version: 21.3.1
* OS: Ubuntu 20.04

### Additional context

I believe it's a similar problem to the one highlighted in https://github.com/aimhubio/aim/blob/main/aim/ext/transport/heartbeat.py#L158, and the fix can be similar - making the instance list outside of the loop.

**Comment by alberttorosyan** [comment]
Hey @ofermend!
Thanks for reporting the issue. Looking into this.

**Comment by mihran113** [comment]
Hey @ofermend! This fix has been shipped with the latest release, could you please try it out and let us know if everything works as expected?

**Comment by ofermend** [comment]
Sure, will do. Thanks!

**Comment by gorarakelyan** [comment]
Closing this issue, as the fix was shipped. Feel free to reopen if the issue appears again.
