### ISSUE TITLE
Can't run aim-watcher FileNotFoundError: config_empty.json

### ISSUE THREAD

**Issue by arturspeiser** [aimhubio/aim#2288]
Using a fresh install I can run a server and access the UI remotely just fine but trying 'aim-watcher --repo . start' returns:

> FileNotFoundError: [Errno 2] No such file or directory: '/home/aspeiser/.local/lib/python3.9/site-packages/aim/ext/notifier/config_empty.json'

### Environment
- Aim Version (e.g., 3.14.1)
- Python version 3.9
- debian 11

**Comment by arturspeiser** [comment]
Thanks! The watcher is running now but something still seems to be amiss. `aim_run.report_progress(expect_next_in=60)`
breaks with: 

```
File /opt/conda/envs/torch_env1/lib/python3.9/site-packages/aim/sdk/run.py:786, in Run.report_progress(self, expect_next_in, block)
    775 """
    776 Report progress for the run. Report the expected time for the next progress report.
    777 
   (...)
    783     block: (:obj:`bool`, optional): If true, block the thread until the report is written to filesystem.
    784 """
    785 if self._checkins is None:
--> 786     raise ValueError('Progress reports are not enabled for this run')
    787 self._checkins._check_in(expect_next_in=expect_next_in, block=block)

ValueError: Progress reports are not enabled for this run
```

**Comment by alberttorosyan** [comment]
@arturspeiser are you using aim Remote Tracking?
Currently progress reporting is supported only for local storage.

**Comment by arturspeiser** [comment]
Yes, that explains it then. Given this issue (https://github.com/aimhubio/aim/issues/2270) I guess there is currently no good way to deal with crashed Runs that remain active?

**Comment by alberttorosyan** [comment]
@arturspeiser yes; the implementation for more robust locking mechanism is now in progress. If you see the following warning message:
```Using soft file locks to avoid potential data corruption```
this is indeed the reason.

**Comment by alberttorosyan** [comment]
@arturspeiser did you have a chance to test the fix? Can we mark the issue as resolved?

**Comment by arturspeiser** [comment]
Yes, can be closed, thanks again.
