### ISSUE TITLE
Question: mnemonic run id instead of alphanum

### ISSUE THREAD

**Issue by bsridatta** [aimhubio/aim#2291]
## ❓Question

Is there any plan to change the unique run id to more human readable name by default as W&B does?  Thanks!

From Weights and bias
> I didn't name my run. Where is the run name coming from?
If you do not explicitly name your run, a random run name will be assigned to the run to help identify the run in the UI. For instance, random run names will look like "pleasant-flower-4" or "misunderstood-glade-2".

**Comment by alberttorosyan** [comment]
Hey @bsridatta! Thanks for the question.
Run ID (hash) is used in many aspects of aim implementation (including storage). We tend to keep it as now, since it allows to implement certain techniques (relying on hash being random and uniform).
However, for the purposes you mentioned, `Run.name` property can be used. It defaults to `"Run: <Run.hash>"`, but can be set manually.

**Comment by bsridatta** [comment]
Thanks for the super quick response! Got it. 

I noticed that run could be named manually. One could simple use the python library that generates those names but you would want to ask check if ti already exists or just taken up by other run and so on. So was just curious. Thanks for the clarification.

**Comment by cceyda** [comment]
I was about to ask this exact thing. In my case I use the auto-generated run names while saving the model checkpoints. Having something human friendly helps. maybe a mix of human+hash: "pleasant-flower-435689"

**Comment by bsridatta** [comment]
@cceyda I think you could use something like https://github.com/beasteers/randomname to get a name, add random number as suffix, get another if already used for the existing runs. I think it should be straightforward to track if user has set a specific name instead of this. But there must be something I dont see. But true I for sure prefer something I can identify easily than a long hash
