### ISSUE TITLE
SSL Certificates generation

### ISSUE THREAD

**Issue by Natlem** [aimhubio/aim#2302]
## ❓Question
Hello there,

Is it possible to have a quick guide on how to generate and deploy SSL certs for (https://aimstack.readthedocs.io/en/latest/using/remote_tracking.html#ssl-support)
I think this would greatly help a lot of SSL newbies like me.

Thanks

**Comment by gorarakelyan** [comment]
@Natlem you can generate self-signed ssl certificates via openssl. See more details here: https://stackoverflow.com/questions/10175812/how-to-generate-a-self-signed-ssl-certificate-using-openssl

Please let me know if this helps.

**Comment by Natlem** [comment]
Hello @gorarakelyan,

Thanks for your replay. I tried to generate a certificate with the command provided in the link:
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -subj '/CN={DOMAIN_NAME}/subjectAltName=IP:{SERVER_IPV4}'

I have an error on the server side: 
E1028 13:12:42.106779379    2003 ssl_transport_security.cc:1847] No match found for server name: {SERVER_IPV4}

On the clients side:
failed to connect to all addresses; last error: UNKNOWN: Ssl handshake failed

**Comment by Natlem** [comment]
I managed to solve it. For those, who would have similar issue in the future, here how I did:
`
$ openssl genrsa -out server.key 2048`
`
$ openssl req -new -x509 -sha256 -key server.key \
              -out server.crt -days 3650 -subj '/CN={DOMAIN_NAME}'
`
