### ISSUE TITLE
Run hangs sometimes on close

### ISSUE THREAD

**Issue by vakker** [aimhubio/aim#2303]
## 🐛 Bug

In some cases closing the `Run` hangs on some file operations. 
E.g. if I run this it hangs on the `close`. 
```python
run = aim.Run(
    experiment="test",
    system_tracking_interval=None,
    capture_terminal_logs=False,
)

run.close()
```
This seems to be due to some file corruption in the `.aim` directory, which might be due to syncing data between servers in a bad way.

If I try to kill it then this is the stack trace:
```
Stack (most recent call first):
  File "/home/user/.pyenv/versions/3.9.7/lib/python3.9/weakref.py", line 591 in __call__
  File "/home/user/.pyenv/versions/spg-exp/lib/python3.9/site-packages/aim/sdk/run.py", line 108 in _close
  File "/home/user/.pyenv/versions/3.9.7/lib/python3.9/weakref.py", line 591 in __call__
  File "/home/user/workspace/callbacks.py", line 221 in log_trial_end
....
```

After I remove the `.aim` directory and start with a fresh one it's all good. However, I can't access my old logs any more.
I uploaded the problematic `.aim` dir to my Google Drive, I can send a link to it in an email or PM if needed for the reproduction.

### To reproduce

See above.

### Expected behavior

No hang.

### Environment

- Aim Version: 3.14.1
- Python version: 3.9.7
- pip version: 22.3
- OS (e.g., Linux): Ubuntu 20.04.4

**Comment by mihran113** [comment]
hey @vakker! Thanks a lot for the report. I would appreciate to have the link for `.aim` directory, cause it seems to be something specific. You can join our slack and DM me the link. (https://slack.aimstack.io/)

**Comment by mihran113** [comment]
> This seems to be due to some file corruption in the .aim directory, which might be due to syncing data between servers in a bad way.

Could you please provide more details about this part? How are you syncing data between servers?

**Comment by vakker** [comment]
@mihran113 sent you a DM on Slack.
Regarding the syncing, I'm using [Unison](https://github.com/bcpierce00/unison/). I see some data corruption when I have Aim running on one server and another one is logging to the same directory.

**Comment by mihran113** [comment]
@vakker had a look at the files. There's definitely a data corruption, which is causing the issue with `run.close()`. Can you please share a little more details about your setup? Do you just sync 2 directories, and on one the UI is running, and in the other some runs are logged? Did I get it correctly?

**Comment by vakker** [comment]
Yes, that's correct. 
On server 1 I run the `aim` UI on server 2 I have a training run that's logging to `.aim`.
I have a git repo (lets say `project`) and then I run Unison on server 1:
```
unison default project ssh://<server-ip>//home/user/workspace/project -prefer newer -repeat watch
```

The corruption might be because of Unison, or because of Aim, I'm not sure. 
However, there should be some way to handle corrupted data in a more robust way.

**Comment by mihran113** [comment]
Hey @vakker. Sorry for late response. Unfortunately the setup with `Unison` will result in corruptions if the `aim up` command is running. As from it's perspective the run is `dead`, cause there is no lock on it in the synced directory, so it'll try to finalize it automatically which will cause corruptions as it's still active actually. 
As an alternative I can suggest you to use aim remote tracking server to track the logs remotely to server 1 instead of syncing them.

**Comment by vakker** [comment]
Thanks for the response, that's fair. 
Is there a way to make `aim` more robust to these file corruptions? Currently if there's a single run that's corrupted, the whole database becomes unreadable, right?

**Comment by vakker** [comment]
@mihran113 cool, thanks for looking into this!
