### ISSUE TITLE
Searching for new field replaces previously selected fields

### ISSUE THREAD

**Issue by YodaEmbedding** [aimhubio/aim#2322]
## 🐛 Bug

Searching for new field replaces previously selected fields.

### To reproduce

1. Search for "run.active" and checkmark the box.
   <img width="441" alt="aim_choose_1" src="https://user-images.githubusercontent.com/721196/199941213-3363c6b3-9dc0-4be4-9f86-8d2f7f39dcfb.png">

2. Search for "run.e".
   <img width="443" alt="aim_choose_2" src="https://user-images.githubusercontent.com/721196/199941231-cc0088cf-17b0-4ea3-8339-0d05f6d5c072.png">

3. Select "run.experiment". Previously selected fields are now unselected!
   <img width="444" alt="aim_choose_3" src="https://user-images.githubusercontent.com/721196/199941248-bc45599e-7596-472e-8292-f2bcdd83ae44.png">

4. Final result.
   <img width="444" alt="aim_choose_4" src="https://user-images.githubusercontent.com/721196/199941269-c4bee06a-c7db-4d24-9a39-a14afdafdc4c.png">

### Expected behavior

Keep all items.

<img width="449" alt="aim_choose_expected" src="https://user-images.githubusercontent.com/721196/199945866-7ddcd48a-f744-4bb6-8e1c-f3c8404d0d7c.png">

### Environment

- Aim Version: 3.14.3
- Python version: 3.8
- pip version: 22.1
- OS: Linux
- Any other relevant information

### Additional context

N/A

**Comment by gorarakelyan** [comment]
@YodaEmbedding this is a critical issue. Does it happen only in Figures Explorers or everywhere across the UI?

**Comment by rubenaprikyan** [comment]
Hey @YodaEmbedding! thanks for reporting
looking into this

**Comment by rubenaprikyan** [comment]
Hey @YodaEmbedding! The fix was released with v3.14.4.
Could you please check it out and let me know if still have an issue with this?
