### ISSUE TITLE
Aim can't find docker

### ISSUE THREAD

**Issue by sw32-seo** [aimhubio/aim#234]
When I run `aim up` in conda environment, Aim can't find docker which is already installed. Could you please let me know how to resolve this?

**Comment by sw32-seo** [comment]
Sorry for disturbance. It was an permission problem.

**Comment by gorarakelyan** [comment]
No worries. Feel free to ask a question or report an issue anytime when something goes wrong.

**Comment by felixkreuk** [comment]
@sw32-seo I'm running into the same issue, can you please describe your solution?

**Comment by SGevorg** [comment]
@felixkreuk have you checked your user-groups?

**Comment by felixkreuk** [comment]
@SGevorg good call, thank you.

**Comment by SGevorg** [comment]
@felixkreuk we are going to move away from docker soon. Hopefully this is not a huge issue and you get started with Aim.
Please bear with us!

**Comment by felixkreuk** [comment]
@SGevorg cool, thanks! Yes, I think it's a good idea. Anything that requires root-access might be a deal-breaker for some people that work on IT-managed clusters.
