### ISSUE TITLE
When aim server is killed, the client crashes

### ISSUE THREAD

**Issue by ofermend** [aimhubio/aim#2342]
## 🐛 Bug

I'm running the aim server as a remote centralized server. The client communicates with the server fine, but when the server crashes (for whatever reason) my client application also crashes with the following error:

WARNING - aim.ext.transport.rpc_queue -   Remote Server is unavailable, please check network connection: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connection reset by peer"
	debug_error_string = "{"created":"@1667530917.209515465","description":"Error received from peer ipv4:34.232.33.105:53800","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Connec
tion reset by peer","grpc_status":14}"
>, attempt: 1

ERROR - grpc._channel -   Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 203, in consume_request_iterator
    request = next(request_iterator)
  File "/usr/local/lib/python3.8/dist-packages/aim/ext/transport/client.py", line 143, in message_stream_generator
    for chunk in stream:
  File "/usr/local/lib/python3.8/dist-packages/aim/ext/transport/message_utils.py", line 31, in pack_stream
    for key, val in tree:
ValueError: too many values to unpack (expected 2)

### To reproduce

Run aim server and aim client SDK; kill the server; see client crash with error above.

### Expected behavior

Client continues to execute. I would like to suggest this is the best behavior because the client may for example run a bit training job, and even if I don't have comms to Aim anymore, the client itself should not crash. 

### Environment

- Aim Version 3.13.4
- Python version 3.8.10
- pip version 21.3.1
- OS Ubuntu Linux

### Additional context

NA

**Comment by alberttorosyan** [comment]
@mihran113 could you please take a look. As far as I recall, the tracking queue on the client side should handle such cases (if the server is not available block once queue reaches specified size) 🤔

**Comment by mihran113** [comment]
Hey @ofermend. We've done a lot of changes regarding remote tracking server that have been shipped with `v3.15.0`, including also changes for error handling and etc. Could you please try out the latest version and let us know if the issue still persists?

**Comment by ofermend** [comment]
Thanks. Will try the new version soon and will let you know for sure.

**Comment by ofermend** [comment]
Confirming 3.15.1 is much better and I have not seen any issues so far. Thanks!!

**Comment by alberttorosyan** [comment]
@ofermend closing the issue as resolved.
