### ISSUE TITLE
Bring all history w/o sampling by cli convert wandb

### ISSUE THREAD

**Issue by hjoonjang** [aimhubio/aim#2347]
## Proposed refactoring or deprecation

(Not sure if it's okay with this category: Feature suggestion instead..?)
In `aim/cli/convert/processors/wandb.py`, https://github.com/aimhubio/aim/blob/8441a58ac1e39b8cd5a5b802794c9c944effdfd4/aim/cli/convert/processors/wandb.py#L45
we've been trying bringing **SAMPLED** history of existing wandb metric logs.
I would carefully propose to bring **ALL** history without sampling.

It seems gonna be easily implemented using `wandb_run.scan_history()` with a little mod rather than using `wandb_run.history()`.
The latter has default args `samples=500` to have roughly 500 records returned. ([ref](https://github.com/wandb/wandb/blob/e85ba97972308091d22f34e275cd58fea4b774dc/wandb/apis/public.py#L2027))

### Motivation

In #2067, an awesome feature had been added: wandb to aim log converter.
But I felt lossless log transfers would be much more preferrable than the implicit sampling.
And it seems pretty easy to implement by replacing a single line of code.

### Pitch

Though [`wandb_run.history()`](https://docs.wandb.ai/ref/python/public-api/run#history) gives *simpler and faster* results, but it's sampled to loss some information eventually.
I propose it to be lossless fetch, which is easy to implement as well.

### Additional context

I've already had remote branch with fix commits, but after checking contributing guidelines, I've got to come here first.

---

By the way, I have a remaining question:
- I'm gonna have to add `import pandas` in `aim/cli/convert/processors/wandb.py`, but there is no `pandas` requirements in this project yet.
- I found it anyhow requires `pandas` package when I simply run the scripts below:
    ```shell
    pip install aim wandb
    aim convert wandb --entity ... --project ...
    # Error: "Unable to load pandas, ..." (from wandb api, not from aim, though)
    pip install pandas
    # Now it's working
    ```
    - By `wandb` itself: https://github.com/wandb/wandb/blob/e85ba97972308091d22f34e275cd58fea4b774dc/wandb/apis/public.py#L2058-L2063
        - Seems `wandb` also has no requirements asking `pandas`
- So, should `pandas` be gracefully added in requirements of this project?

**Comment by gorarakelyan** [comment]
@hjoonjang thanks for the suggestion. It makes a lot of sense. I just left a comment wrt padnas integration under the submitted PR [here](https://github.com/aimhubio/aim/pull/2348#issuecomment-1315374113). Could you please take a look at it? 🙏

**Comment by gorarakelyan** [comment]
@tmynn tagging you here, so you are aware of this thread.
