### ISSUE TITLE
Fastapi and starlette version conflict with fiftyone

### ISSUE THREAD

**Issue by bsridatta** [aimhubio/aim#2367]
## 🐛 Bug

I am using fiftyone for data analysis along with aim. And there seems to be some conflicts with fastapi dependencies (starlette).
And I noticed in aim setup.py that max fastapi is set to 0.68 (from last year). It would be nice newer version of fastapi could be used.

Thanks!

Error on `aim up`:
  
ERROR:    Exception in ASGI application
```
File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/fastapi/routing.py", line 209, in app
    solved_result = await solve_dependencies(
  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 485, in solve_dependencies
    response = response or Response(
  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/starlette/responses.py", line 55, in __init__
    self.init_headers(headers)
  File "/home/dattab/.local/share/virtualenvs/seat_belt_detection-M8EBEog7/lib/python3.8/site-packages/starlette/responses.py", line 84, in init_headers
    and not (self.status_code < 200 or self.status_code in (204, 304))
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by gorarakelyan** [comment]
If I remember it right the upper limitation was set, as fastapi 0.69 (based on starlette 0.16) introduced some breaking changes. What was the exact reason @alberttorosyan ? It would be great to have deps versions as loose as possible.

**Comment by alberttorosyan** [comment]
the reason is the support of Python 3.6. we plan to drop it with aim `3.16` release, along with some limitations.

**Comment by hadim** [comment]
`fastpi` upper limit is currently set to `<0.68` while the latest version is 0.88. It makes it very hard to use `aim` within a stack that uses one of the latest versions of `fastapi`.

**Comment by gorarakelyan** [comment]
I think it is worth considering dropping python3.6 version and related limitations (incl fastapi upper boundary) with the next patch release. 
@alberttorosyan thoughts?

**Comment by hadim** [comment]
For what's worth the python ecosystem is moving away from python 3.6 since it has reached end of life one year ago: https://endoflife.date/python

Conda forge does not support it anymore. Also conda-forge is slowly moving away from python 3.7 nowadays since end of life will be reached in ~5 months.

**Comment by mihran113** [comment]
Hey @bsridatta! The upper version restriction for `fastapi` has been dropped with `v3.16.0` release.  Let us know if everything works as expected after the upgrade. :)

**Comment by gorarakelyan** [comment]
Closing the issue, as the fix has been shipped.
