### ISSUE TITLE
Integration with Ray Tune

### ISSUE THREAD

**Issue by ju2ez** [aimhubio/aim#2369]
## 🚀 Feature

Ray (tune) is a popular hyperparameter tuning library with strong focus on parallelization and multi-gpu training.

### Motivation

Adding a powerful metric tracker next to the (default) tensorboard tracker to ray would be very valuable. 

As far as I can tell adding a Callback for logging should do the job.

**Comment by gorarakelyan** [comment]
Thanks for the suggestion!

Seems we need to add a similar integration to this https://github.com/ray-project/ray/blob/master/python/ray/tune/logger/tensorboardx.py

@ju2ez have you already integrated Aim in your project with Ray Tune?

**Comment by ju2ez** [comment]
@gorarakelyan exactly, I think so too. 

Yes, I have a first working callback but it needs a bit of more work and I would need some support to integrate it properly to aim as I just started to look at this repo.

**Comment by gorarakelyan** [comment]
@ju2ez awesome! We would be happy to help with submitting the integration to Ray Tune. Please feel free to ask any question you have. 🙌 
Also could you share how the current version works? what does it track?

**Comment by ju2ez** [comment]
@gorarakelyan Thanks a lot.

So far I have the callback implemented and I am able to track numeric metrics. 
What's missing is the tracking of images audio, etc. 

In general, the version works great.

**Comment by gorarakelyan** [comment]
@ju2ez sorry for the late reply. Will go over it shortly. 🙌 

wrt tracking media: we mainly add a default logger/callback, which only tracks hparams and metrics. It is more straightforward compared to tracking media files, which format can vary for different use-cases. Tracking format, frequency, names, context, etc may depend on a specific usage scenario. 
So far community/users have been extending the default callbacks to track additional metadata specific for their use-cases.

So I will recommended submitting a default logger with only hparams and metrics tracking. And if needed we can iterate over it later on. Thoughts?

**Comment by ju2ez** [comment]
hey @gorarakelyan , no worries !

wrt tracking media => I see, I guess then we can leave it like it is now. HParams tracking and metric tracking works just fine. The only thing missing is unit tests for the metrics that are written.. I'm sure you have them already somewhere.. if you can give me a pointer I can implement them, otherwise you can also do it ofc. 

> So I will recommended submitting a default logger with only hparams and metrics tracking. And if needed we can iterate over it later on. Thoughts? 

=> Sounds like a great idea!

**Comment by gorarakelyan** [comment]
@ju2ez [here you can find](https://github.com/aimhubio/aim/blob/main/tests/sdk/test_run_write_container_data.py) unit tests for metrics and hparams tracking. But please note these tests are written via Aim low-level API. Which compared to the high-lvl API is subject to more frequent change. Thus, I think a more sustainable and forward compatible approach will be querying and retrieving tracked logs with high-lvl API. Here are some [examples](https://colab.research.google.com/drive/14rIAjpEyklf5fSMiRbyZs6iYG7IVibcI).

Pseudo example:
```py
# Init
run = aim.Run()

metrics_list = ["foo", "bar", "baz"]
steps_len = 100

# Tracking metrics
for metric in metrics_list:
    for step in range(steps_len):
        run.track(step, name=metric, step=step)

# Approach 1: get tracked data right from the run instance (to cover base cases)
for metric in aim_run.metrics():
    metric.values.sparse_numpy()
    # assertions
    assert(...)

# Approach 2: query from the whole repo (for more comprehensive testing if needed)
# Query metrics
query = "metric.name in ['foo', 'bar', 'baz']"
# Convert results into pandas dataframe
for run_metrics_col in repo.query_metrics(query).iter_runs():
    df = run_metrics_col.dataframe(only_last=True, include_run=False)
    # assertions
    assert(...)

**Comment by SGevorg** [comment]
This issue should probably be closed as the ray integration has been available for a good while.
