### ISSUE TITLE
UI hangon searching for runs

### ISSUE THREAD

**Issue by Natlem** [aimhubio/aim#2374]
## 🐛 Bug

Unable to display runs or any kind of information from Aim running on a remote server.
The /runs page is stuck on "Searching over runs..."  with "34 of 34 checked ------ 33 matched run(s)" 
There's an error in the console log: 

> encoder.ts:25 Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range

server-side aim ui errors:
> query failed, name 'metric' is not defined
> query failed, '>' not supported between instances of 'datetime.datetime' and 'str'   
> query failed, 'NoneType' object is not callable  

### Environment

- Aim Version: 3.14.3 
- OS: Linux

**Comment by mihran113** [comment]
Hey @Natlem! Could you please share what was the query that failed?

**Comment by Natlem** [comment]
I think this should be all. Thanks for the great support :)

**Comment by roubkar** [comment]
Hey @Natlem, the PR which resolves the issue related to characters encoding in Aim UI has been merged and will be released with the next version.
