### ISSUE TITLE
Wrong Python version requirement?

### ISSUE THREAD

**Issue by jaekyeom** [aimhubio/aim#239]
While `setup.py` specifies
```
REQUIRES_PYTHON = '>=3.5.2'
```
I think aim doesn't work with Python 3.5.2 because of [this part](https://github.com/aimhubio/aim/blob/56af4879915c2ae7a737e0838bd73fb67714f849/aim/sdk/session/session.py#L19).

**Comment by gorarakelyan** [comment]
Hi @jaekyeom ,

Yes, type hinting syntax for class attributes was added since Python v3.6. Thanks for the feedback. We will make sure to remove version inconsistencies with Python v3.5.

**Comment by gorarakelyan** [comment]
Closing this issue, since all incompatibilities with python >= 3.5.0 were [resolved](https://github.com/aimhubio/aim/pull/243)
