### ISSUE TITLE
Confusing query syntax

### ISSUE THREAD

**Issue by dsblank** [aimhubio/aim#2416]
## 📚 Documentation

I was confused by the query syntax `object["item1", "item2"]` but realized that this is probably the way that loading objects is optimized. 

I made a PR to expand on that a bit: #2410 

(BTW, you could probably have a lazy-loading object that did not load all attributes, and then you wouldn't need this non-Pythonic optimization.)

**Comment by gorarakelyan** [comment]
@dsblank just merged the PR. Congrats on the contribution! 🚀
