### ISSUE TITLE
Highlight all metric plots from the same run together in charts

### ISSUE THREAD

**Issue by jaekyeom** [aimhubio/aim#242]
It would be super helpful if highlighting one metric plot (e.g. mouse hovering on the plot) causes all the other metrics from that specific run in every chart to be highlighted, too!

I believe it is a common scenario to compare hyperparameter sets with more than one evaluation metrics at the same time.

Thank you.

**Comment by gorarakelyan** [comment]
Great idea, we will definitely add this feature. Thanks @jaekyeom for the feedback.

**Comment by gorarakelyan** [comment]
This feature was added in Aim UI v1.2.3 ([132](https://github.com/aimhubio/aimui/pull/132)).

To upgrade to the newer version please run `aim upgrade`.
