### ISSUE TITLE
GPU utilization is not tracked if querying power usage fails

### ISSUE THREAD

**Issue by timokau** [aimhubio/aim#2420]
## 🐛 Bug

I am running experiments on a machine with a GPU, yet no GPU metrics are tracked. It seems like this code is responsible:

https://github.com/aimhubio/aim/blob/480e063cde063897283bcd8adb221e9baa861637/aim/ext/resource/stat.py#L152-L186

When any part of the GPU stats collection fails, we just give up entirely and store no information. In my case querying the power usage seems not supported by nvml, it raises `nvml.NVMLError_NotSupported`. Querying utilization and memory usage works just fine though and it would be nice if we could track those stats anyway.

### To reproduce

I'm not sure how to reproduce this, since it depends on a setup where `nvml` fails to determine the GPU power usage.

### Expected behavior

Aim tracks all the information that it can query without exceptions.

### Environment

- Aim Version (e.g., 3.15.1)
- Python version 3.10.9
- pip version 22.0.3
- OS (e.g., Linux) Linux
- Any other relevant information

### Additional context

--

**Comment by alberttorosyan** [comment]
@timokau great point! Thanks for pointing this 🙌

**Comment by timokau** [comment]
You're very welcome :) See #2422 for a possible fix.
