### ISSUE TITLE
Add the "experiment description" column to the runs view

### ISSUE THREAD

**Issue by piojanu** [aimhubio/aim#2429]
## 🚀 Feature

You've recently added the experiment view. It groups the experiment runs and allows to add a.o. an experiment description. This is a great feature! However (😉), currently you can't see this description in any list. Please add e.g. the "experiment description" column to the runs.

### Motivation

Right now I add the description to the top run of the experiment instead to the experiment itself, so I can view this description when scrolling through the list of runs. It would be good to have this ability to see the description when using the new experiment level view and its features (description, notes, ...).

### Pitch

I want to be able to see the list of runs/experiments with their descriptions so I know right away what the experiment tested without going into its view.

### Alternatives

Maybe new "experiments list" with the experiments descriptions and other experiment-level statistics (presented currently each experiment's view) would be another solution. This way the experiments' descriptions wouldn't be repeated for each run of the experiment in the runs list.

**Comment by roubkar** [comment]
Hey @piojanu, thanks for reporting this. We'll keep you updated on the progress.

**Comment by arsengit** [comment]
Hey @piojanu, this feature has been shipped with v3.15.2
To upgrade please run `pip install aim --upgrade`

**Comment by piojanu** [comment]
Thanks! I'll give it a try after the New Year 👌🏼

**Comment by simonrouse9461** [comment]
@arsengit Thanks for shipping this feature!
I have a question regarding the experiment description. Is there a way to get/set the experiment description programmatically? I don't see anything about this in the doc. I also checked the source code. It seems that only the experiment name can be accessed and modified through the SDK. Did I miss something, or is this feature not available yet?

**Comment by arsengit** [comment]
@simonrouse9461 Yes, you can change the experiment description programmatically using the `run.props.experiment_obj.description = [description]` snippet. Alternatively, you can change it directly from the experiment's page on the web UI.

**Comment by simonrouse9461** [comment]
@arsengit Thanks for the information. I tried this approach. It works with a local Aim repo. However, if I use a remote aim server, it raises this error:
```
AttributeError: 'StructuredRunProxy' object has no attribute 'experiment_obj'
```

**Comment by simonrouse9461** [comment]
I also tried this:
```python
from aim.storage.structured.proxy import StructuredRunProxy
proxy = StructuredRunProxy(run.repo._client, run.hash, read_only=False)
proxy._rpc_client.run_instruction(run.hash, proxy._handler, 'experiment_obj', [])
```
but it seems that it's not able to handle props of non-native types:
```
TypeError: Unhandled non-native value `<ModelMappedExperiment id=7f68d77a-5f7d-4e58-b32a-0b34239f1338, name='test_experiment'>` of type `<class 'aim.storage.structured.sql_engine.entities.ModelMappedExperiment'>`.
```

**Comment by arsengit** [comment]
@simonrouse9461 Unfortunately, as you mentioned, the `experiment_obj` property is not yet supported in the `StructuredRunProxy` class for remote tracking.
