### ISSUE TITLE
LIKE operator on AimQL

### ISSUE THREAD

**Issue by otakbeku** [aimhubio/aim#2438]
## ❓Question

I'm having difficulties searching experiments containing one or two specific words. Is there any example of how I query results that contain exact words?

I intuitively use these two syntaxes but failed:

1. `run.experiment LIKE "exp%"`
2. `run.experiment.__contains__("exp%")`

**Comment by alberttorosyan** [comment]
@otakbeku I believe the following syntax is what you're looking for:
`"exp" in run.experiment`
The query in Aim is actually a python expression.

**Comment by otakbeku** [comment]
Ah it works! Thank you so much @alberttorosyan 

Gotta close this issue for now
