### ISSUE TITLE
Introduce `-y` option in aim CLI commands

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#2440]
## 🚀 Feature

Aim commands such as `aim init` prompt user for inputs, which are mainly confirmation prompts. Need to add a command flag that will automatically confirm the action.

### Motivation
Enable aim commands in non-interactive environments (shell scripts, etc.)

### Pitch
Add -y option similar to apt install to automatically confirm the action.

**Comment by emekaokoli19** [comment]
Hey @alberttorosyan could you please elaborate on this issue? From what I understand, this issue is to add `-y` option everywhere there is a `click.confirm` in the CLI commands.
