### ISSUE TITLE
`protobuf` version upper limit set to 4.0.0 

### ISSUE THREAD

**Issue by hadim** [aimhubio/aim#2455]
## 🚀 Feature

The current version of allowed `protobuf` is set to  `<4.0.0` which makes it hard to use `aim` in a stack with a more updated `protobuf` version.

Would that be possible to remove that constraint?

**Comment by gorarakelyan** [comment]
thanks @hadim, will look into it.
@mihran113 @alberttorosyan tagging you, so you are aware of this thread.

**Comment by mihran113** [comment]
There were some compatibility issues with `protobuf v4` that's why we've limited the upper version, will look into it to see what's possible to do about that.

**Comment by hadim** [comment]
Thanks guys.

FYI: I am currently trying to build the latest version on conda-forge: https://github.com/conda-forge/aim-feedstock/pull/14. It's a bit of work since it also requires a couple of other packages to be created or to update (see https://github.com/conda-forge/aim-feedstock/pull/14#issuecomment-1370097049).

Being able to lower the number of upper bound version for important deps (`protobuf` and `fastapi` for example) would be really great to be able to integrate smoothly `aim` in any existing stack.

**Comment by mihran113** [comment]
We'll remove the upper limits of `fastapi` with the `v3.16.0` of `aim`, as we're planning to drop the support for `python3.6`, will work on this too. :)

**Comment by mihran113** [comment]
Hey @hadim! The `protobuf`'s  upper limits and also `fastapi`'s as well has been dropped with the new `3.16.0` release.
