### ISSUE TITLE
`performance_tests` dir is installed

### ISSUE THREAD

**Issue by hadim** [aimhubio/aim#2469]
I spotted this while inspecting the content of the conda forge package at https://github.com/conda-forge/aim-feedstock/pull/14

The fix is probably as simple as replacing `packages = find_packages(exclude=('tests', 'aim.web.ui'))` by `packages = find_packages(exclude=('tests', 'performance_tests', 'aim.web.ui'))` in the `setup.py` file.

**Comment by gorarakelyan** [comment]
@hadim thanks for pointing this out.

**Comment by alberttorosyan** [comment]
The issue has been addressed here: https://github.com/aimhubio/aim/pull/2477/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R199
Merged and shipped with Aim 3.16.0 release
