### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by andychisholm** [aimhubio/aim#2472]
## 🚀 Feature

Would be great if aim was usable in python 3.11 environments.

### Motivation

This release packs a bunch of [performance improvements](https://docs.python.org/3.11/whatsnew/3.11.html) which are highly motivating for ML projects to upgrade. Dependency on aim will become as blocker as other [key packages](https://pyreadiness.org/3.11/) introduce support (e.g. now available in a [torch-nightly](https://github.com/pytorch/pytorch/issues/86566)).

```pip install aim``` in a 3.11 environment currently fails due to missing distribution for the upstream `aimrocks` package.

**Comment by alberttorosyan** [comment]
Good point, @andychisholm ! Will add the `aimrocks` packages for Python 3.11 🙌

**Comment by gorarakelyan** [comment]
Closing the issue, as the py 3.11 support has been added.
