### ISSUE TITLE
Showing only one metric in the charts and no legend on metric names

### ISSUE THREAD

**Issue by twni2016** [aimhubio/aim#2473]
## 🐛 Bug

When I add multiple metrics by clicking the +metrics button and then click the search button, I can only see the charts of one metric on the webpage. Moreover, the legend does not show the metric name of each chart. But the table below the charts shows the selected metric names and their values. 

### Expected behavior

Show each selected metric and label it in the legend. 

### Environment

- Aim Version: 3.15.2

**Comment by roubkar** [comment]
Hey @twni2016, could you please check whether you have applied grouping options in the "Chart" grouping popover?

This should enable the splitting of metrics into multiple line charts and will display the chart identifiers in the legend section.

<img width="545" alt="Screen Shot 2023-01-12 at 11 29 16" src="https://user-images.githubusercontent.com/9951653/212004508-d78bebbd-25bf-4329-a113-37fc74b30bad.png">

**Comment by twni2016** [comment]
Thank you for pointing it out. I forgot the command.
