### ISSUE TITLE
aimlflow: command not found

### ISSUE THREAD

**Issue by ositaunus** [aimhubio/aim#2494]
## 🐛 Bug

`aimlflow: command not found`

### To reproduce
`aimlflow sync --mlflow-tracking-uri=./mlruns --aim-repo=.`

### Expected behavior

https://medium.com/aimstack/exploring-mlflow-experiments-with-a-powerful-ui-238fa2acf89e

### Environment

- aim==3.15.2 | aim-ui==3.15.2 | aimlflow==1.0.0
- python==3.8
- pip==21.2.4
- Linux Mint 20.3

**Comment by mihran113** [comment]
Hey @ositaunus.
Could you please provide the output of the `pip show aim-mlflow` command?

**Comment by ositaunus** [comment]
`WARNING: Package(s) not found: aim-mlflow`

**Comment by mihran113** [comment]
Could you please uninstall the existing `aimlflow` package via 
`pip uninstall aimlflow`
 and then run 
`pip install aim-mlflow`?

There's actually a different package named `aimlflow` which doesn't have a connection with our `aimlflow` command, our package is named `aim-mlflow`, as can be seen in the medium post.

**Comment by ositaunus** [comment]
that was confusing. solved the prob. thank you.
