### ISSUE TITLE
Error running aim behind a proxy

### ISSUE THREAD

**Issue by subramaniam20jan** [aimhubio/aim#2509]
## 🐛 Bug

Trying to run aim behind a proxy and it doesnt seem to work as expected.

### To reproduce

Starting aim with the following command:

aim up --repo aim --dev --base-path /user/{user_name}/proxy/43800
Then accessed: https://{jupyter_server}/user/{user_name}/proxy/43800/

and I get a Not found 404 on the server.

If I try to access https://{jupyter_server}/user/{user_name}/proxy/43800/user/{user_name}/proxy/43800/ then I can see an error very similar to what is described here: https://github.com/aimhubio/aim/issues/1422 

This is very similar to what is described here: https://github.com/aimhubio/aim/pull/1366

Also tried setting and unsetting __AIM_PROXY_URL__ to  https://{jupyter_server}/. If this variable is set, it even shows the exact proxy path that I want to access it on with the base-path but result is no different.

### Expected behavior

https://{jupyter_server}/user/{user_name}/proxy/43800/ shows the page as described

### Environment

- Aim Version (e.g., 3.0.1): v3.15.2
- Python version: 3.9.15
- pip version
- OS (e.g., Linux): Linux
- Any other relevant information

### Additional context

None

**Comment by SGevorg** [comment]
Hi @subramaniam20jan is this the first time you are trying to run Aim within the Jupyter? 
this one keep coming back.
@mahnerak @mihran113 any ideas why this would be happening?

**Comment by subramaniam20jan** [comment]
Yes it is the first time I am running aim behind this proxy. But I will say I have an mlflow server running behind exactly the same setup and that works without any additional arguments being passed to the mlflow server startup.

**Comment by mihran113** [comment]
Hey @subramaniam20jan! Have you tried the solution described in the issues that you've linked? 
In your case that would be: 
`aim up --repo aim --base-path  /user/{user_name}/proxy/absolute/43800`

**Comment by subramaniam20jan** [comment]
> Hey @subramaniam20jan! Have you tried the solution described in the issues that you've linked? In your case that would be: `aim up --repo aim --base-path /user/{user_name}/proxy/absolute/43800`

Yep thats exactly what I tried and it doesnt seem to serve it as expected. It then throws the exact error that I get without base-path but while accessing https://{jupyter_server}/user/{user_name}/proxy/43800/user/{user_name}/proxy/43800/

**Comment by mihran113** [comment]
Hey @subramaniam20jan! Just to double check, did you have the `/proxy/absolute` in the `base_path`? as it's required to be there to be picked up by jupyter server proxy. In your examples provided I've seen only the `/proxy` not `/proxy/absolute`.

**Comment by subramaniam20jan** [comment]
To confirm, there is no `absolute` in my base_path. But I will also say that it works without the `absolute` in the path for my mlflow server on the jupyter server proxy that we are running.

**Comment by subramaniam20jan** [comment]
Further debugging: looks like I can get the static files under this url: https://{jupyter_server}/user/{{user}}/proxy/43800/static-files/static/js/main.js?version=7b5294f0c830d533fc50

But the first failure seems to be trying to retrieve elements under /hub prefix that is missing the user/{{user}}/proxy/43800.

eg:
https://{{jupyter_server}}/hub/static-files/vs/editor/editor.main.js
https:/{{jupyter_server}}/hub/static-files/assets/inter/fonts/Inter.ttf

But I am not sure where these files are being requested from.

**Comment by subramaniam20jan** [comment]
OK, managed to find exactly what the issue is and patch our solution as well. It was partly our setup that was confusing me as well.

We have a proxy that runs services under a prefix but drops the prefix when it hits the aim server.

So Aim was being served as www.xyz.com/aim -> http://0.0.0.0:43800/

This meant that as far as Aim server was concerned it was being served on root and returned html that tried to access things on root. But since the html runs on the client side, it had to be aware of the prefix.

But for the client side code to be aware of the prefix, I added the --base-path=aim and then the html had the prefix right but then aim server started expecting that it would be served on prefix as well which our reverse proxy was dropping.

Solution: I removed the base_path addition for the [server route path](https://github.com/aimhubio/aim/blob/6ec1512e4ba55fa783cfc922276388e3c86c9c76/aim/web/api/__init__.py), but kept it in the [html rendering](https://github.com/aimhubio/aim/blob/6ec1512e4ba55fa783cfc922276388e3c86c9c76/aim/web/api/__init__.py) and that started serving things perfectly as expected.

This is usually a good case to cover as well since it is fairly common for reverse proxies that drop prefix to run in front of servers as well. So I would recommend that there is an additional flag that can set the prefix only for the client side code but not add the prefix to the api's and retain the current functionality for reverse proxies that dont drop prefix as well.

**Comment by subramaniam20jan** [comment]
Another note, this would mean that the fastapi docs if available would lead to 404 on the openapi.json file still. That usually needs the root_path for the application to set to the prefix similar to how the static content would be served. Thats probably an independant bug that exists even in the existing case that you cover actually since you dont use the base_path variable to set the root_path when you instantiate the FastAPI application in the [init file](https://github.com/aimhubio/aim/blob/6ec1512e4ba55fa783cfc922276388e3c86c9c76/aim/web/api/__init__.py).

**Comment by subramaniam20jan** [comment]
> 

Last comment, just going to say this apparently worked on some of the setups that we had (which I assume used proxies that dont drop prefixes. I am sure I tried this but apparently not!
