### ISSUE TITLE
"hide lines" causes plot data/plot title mismatch

### ISSUE THREAD

**Issue by whlteXbread** [aimhubio/aim#2517]
## 🐛 Bug

when selecting a group in the metrics explorer (e.g. if grouping by `metric.name`), and then clicking the "hide lines" button, sometimes the plot data no longer matches the plot title

### To reproduce

1. open one or more runs in the metrics explorer with two or more metrics
2. select two or more metrics to show as plots
3. select the group associated with the first-listed metric
4. click "hide lines"

### Expected behavior

the first plot should disappear, and all plot titles/plot data should match

### Actual behavior

the data from the second plot moves to the first plot, and the plot title does not change. 

### Environment

- Aim Version 3.15.2
- Python version 3.10.8
- pip version 23.0
- macos monterey 12.6

### Additional context

happens in "advanced search mode" and normal search mode.

**Comment by KaroMourad** [comment]
Hey @whlteXbread , thanks for opening this issue.
Will add to our roadmap.
