### ISSUE TITLE
How to install docker for aim?

### ISSUE THREAD

**Issue by MultiPath** [aimhubio/aim#252]
Hi, I installed aim using pip and type ``aim up``, it returns me:

Oops! You don't have docker installed. Aim UI runs on docker. Please install docker

I have followed ``https://docs.docker.com/engine/install/ubuntu/`` to install docker engine on my machine. But the above errors are still there. What should I do for that?

**Comment by gorarakelyan** [comment]
Hi @MultiPath ,

Try to run `docker version` command to check if docker was properly installed. 

Also you probably need to add your user to docker user group if you haven't done it yet:
```
sudo usermod -aG docker $USER
sudo systemctl restart docker
```
Do not forget to reopen shell for configurations to take effect.

**Comment by MultiPath** [comment]
Thank you very much! I did not have too much knowledge with docker. After adding user group it works.
