### ISSUE TITLE
Display Name of Runs and Experiments in UI when coming from MLflow

### ISSUE THREAD

**Issue by ositaunus** [aimhubio/aim#2529]
## 🐛 Bug

The IDs are appearing instead of the names when converting mlflow experiments.

### To reproduce

![image](https://user-images.githubusercontent.com/123379753/216971098-423aada4-81dc-438f-8e1d-eade7f2d3916.png)

![image](https://user-images.githubusercontent.com/123379753/216970422-3d83b98a-fccc-448f-8925-0d6ccd97b476.png)

### Expected behavior

ID and Name should be presented in main UI when browsing experiments and in the runs explorer too

### Environment

    aim==3.15.2 | aim-ui==3.15.2 | aimlflow==1.0.0
    python==3.8
    pip==21.2.4
    Linux Mint 20.3

### Additional context

With names it is easier to explore results.

**Comment by mihran113** [comment]
Hey @ositaunus! Thanks a lot for the suggestion. Actually there's already an open PR for setting experiment names instead of ids, will add the run names as well :)

**Comment by mihran113** [comment]
Btw can I ask you to move this issue to `aimlflow` repo instead? As it's only related to `aimlflow` and not `aim`.
https://github.com/aimhubio/aimlflow

**Comment by ositaunus** [comment]
PR already open
