### ISSUE TITLE
Add run name to Metrics popover

### ISSUE THREAD

**Issue by froody** [aimhubio/aim#2564]
## 🚀 Feature

When hovering over a line in a plot in the metrics explorer, it would be nice to see the run name in the popover. Currently I see the X and Y labels/values and the "Group Config" which just repeats the metric name. I would much rather see details about the run (e.g. run name)
![Screenshot 2023-03-03 at 10 25 25 am](https://user-images.githubusercontent.com/241317/222586564-9ae5741b-cfb3-4c28-8a89-23d72394fbbf.png)

### Motivation

It's frustrating to have to click and then look down at the table below to see which run the line/point belongs to. I would much rather it be updated in the popover on mouseover like in wandb.

### Pitch

In the popover, show runs-pecific information, e.g. 
![Popover idea](https://user-images.githubusercontent.com/241317/222586475-12130a63-2c60-4718-8f09-2967b03cc780.jpg)

**Comment by roubkar** [comment]
Hey @froody, we have a chart tooltip content control popover from where you can add run name (and not only).
Will this resolve your issue?
<img width="1172" alt="Screen Shot 2023-03-03 at 12 32 16" src="https://user-images.githubusercontent.com/9951653/222671249-1692edda-6761-4f70-86eb-84dfa70c384f.png">

**Comment by froody** [comment]
Oh cool, I didn't see that. Yep that solves my problem. thanks!
