### ISSUE TITLE
Add HTML display for media/objects tracking

### ISSUE THREAD

**Issue by Natlem** [aimhubio/aim#2575]
## 🚀 Feature

Add a HTML display box for tracking media and object (similar to https://aimstack.readthedocs.io/en/latest/quick_start/supported_types.html#text-tracking-with-aim)

### Motivation

This would help the tracking of NLP algorithm which outputs texts that can be augmented visually with HTML elements.
Examples of this include : 
 - Visualization of Named Entity Recognition 
 - Visualization Part Of Speech Tagging 
 - etc.

The html can be usually generated with displacy ((https://spacy.io/usage/visualizers)

### Pitch

Add a HTML to the media bar, next to "Texts". Retain mostly the visual of existing "Texts" tracking except display HTML instead of raw text

### Alternatives

Another option is to add a checkbox for display HTML directly inside "Texts" tracking.

**Comment by Natlem** [comment]
I would be up to help with this if someone can point me to right direction

**Comment by roubkar** [comment]
Hey @Natlem, thanks for opening this feature request.
Would love to help you with your contribution.

There can also be an explorer for tracked HTML data, enabling filtering and grouping those values and comparing them across the runs.

**Comment by Natlem** [comment]
@roubkar, how do you want to proceed ?

**Comment by roubkar** [comment]
Hey @Natlem, to create a Text explorer we will need to do the following steps:
- Add a TextExplorer container page
- A Text visualization box component
- Add route config for displaying in the sidebar and navigation

Then we should add a visualization control that will enable switching between displaying plain text and embedded HTML.

For reference you can use the Figures Explorer source code:
- [FiguresExplorer container page](https://github.com/aimhubio/aim/blob/main/aim/web/ui/src/pages/FiguresExplorer/index.tsx)
- [Figures box component](https://github.com/aimhubio/aim/blob/main/aim/web/ui/src/modules/BaseExplorer/components/Figures/Figures.tsx)
- [Routes config file](https://github.com/aimhubio/aim/blob/main/aim/web/ui/src/routes/routes.tsx)

Feel free to reach out if there will be questions.

I also would like to invite you to join our community discord server where you can ask questions, get help from the team and the community, discuss MLOps-related topics and not only.
https://community.aimstack.io/

**Comment by roubkar** [comment]
Hey @Natlem, I just opened a PR for Text Explorer.
It also includes rendering your text as HTML.

A short demo:
https://user-images.githubusercontent.com/9951653/226196315-185e4902-c2b1-4dba-8582-7fc8e158ea31.mov

**Comment by roubkar** [comment]
Hey @Natlem, we recently shipped a new version that includes the Text Explorer.
To upgrade please run `pip install aim --upgrade`

**Comment by Natlem** [comment]
Great !!! Thanks a lot
