### ISSUE TITLE
Add more information to the hover box about the run

### ISSUE THREAD

**Issue by mrzv** [aimhubio/aim#2621]
## 🚀 Feature

Make it possible to add additional information about the run to the box that pops up on hover.

### Motivation

When showing many runs at once, it's helpful to know more about their parameters than what's used for grouping.

### Pitch

Add a dialog that allows to specify extra fields (`run.hparams.batch_size`, etc) to display in the hover box.

**Comment by KaroMourad** [comment]
Hey @mrzv, thank you for opening the issue. 

You can explore run related information by setting tooltip parameters (e.g `run.hparams.batch_size`) from `Tooltip fields` control in explorer controls section. 
Here is the [documentation](https://aimstack.readthedocs.io/en/latest/ui/pages/explorers.html#set-tooltip-parameters) for setting tooltip parameters.


https://user-images.githubusercontent.com/44981312/228002157-fb4f51d0-421f-4af0-b5b0-5309f060a962.mov

**Comment by mrzv** [comment]
Ah, brilliant. I completely missed this. Many thanks!
