### ISSUE TITLE
Add CephFS as an allowed file system type

### ISSUE THREAD

**Issue by jennifer12121** [aimhubio/aim#2622]
## 🚀 Feature

I would like to add CephFS as an allowed file system in the GLOBAL_FILE_LOCK_CAPABLE_FILESYSTEMS system check list. 

### Motivation

When deploying Aim to a system that uses CephFS, an error is thrown and soft locks are used on the files. In the GLOBAL_FILE_LOCK_CAPABLE_FILESYSTEMS class, there is a note saying that if the file system can use `fcntl` / `flock` then it could be added to the list. CephFS can use 'fcntl'/'flock'.

### Pitch

[On line 31 of the file system check](https://github.com/aimhubio/aim/blob/main/aim/storage/locking.py#L31), I would like to add 'ceph'.

**Comment by gorarakelyan** [comment]
hey @jennifer12121, thanks for submitting the issue.

Aim used to use AutoFileLock, which locked either via flock or soft file lock depending whether the FS supported flock. But we moved to DualLock recently. DualLock tries to lock both with unix file-locks and soft file-locks regardless the FS. So there should be no effect.

Could you please share the traceback and also the version of Aim you are using?

But in any way, adding CephFS to the whitelist makes sense. Would you like to contribute?

**Comment by jennifer12121** [comment]
Thank you for giving that feedback! I had been using a mirrored version of `3.14.1` where I had added in `ceph` as a file system. When I upgraded to `3.16.1` I also mirrored it and added in the file system change, so likely when the `DualLock` update occurred, I didn't see the change. 

I would like to contribute! I'll open a PR shortly. Thank you!

**Comment by jennifer12121** [comment]
Thank you! Everything is working as expected and there are no blockers.

**Comment by gorarakelyan** [comment]
@jennifer12121 merged the PR. thanks for your contribution 🙌

**Comment by SGevorg** [comment]
Closed the issue as it seems the PR is merged and working as expected
