### ISSUE TITLE
`Something went wrong` when opening figures explorer

### ISSUE THREAD

**Issue by n-gao** [aimhubio/aim#2627]
## 🐛 Bug

When trying to view figures, I get the error "Something went wrong".
![image](https://user-images.githubusercontent.com/9084670/228216360-d7bfc69f-c4f0-4812-b348-029a70719d43.png)

### Environment

- Aim Version 3.17.1
- Python version 3.9.13
- OS (e.g., Linux) Linux

### Additional context

In Chrome's inspector the following error is logged:
```
react-dom.production.min.js:216 TypeError: Cannot add property displayName, object is not extensible
    at Grouping.tsx:19:17
    at Array.map (<anonymous>)
    at Grouping.tsx:17:39
    at Object.useMemo (react-dom.production.min.js:172:115)
    at t.useMemo (react.production.min.js:23:113)
    at s (Grouping.tsx:16:31)
    at ro (react-dom.production.min.js:157:137)
    at Ho (react-dom.production.min.js:180:154)
    at zo (react-dom.production.min.js:178:169)
    at Lo (react-dom.production.min.js:177:178)
```

**Comment by roubkar** [comment]
Hey @n-gao, we're currently in the process of fixing this!

**Comment by KaroMourad** [comment]
Related: #2626

**Comment by KaroMourad** [comment]
Hey @n-gao , the issue has been fixed and released with Aim v3.17.2

**Comment by roubkar** [comment]
Hey @n-gao, could you confirm that this issue is resolved for you?

**Comment by n-gao** [comment]
This is solved and can be closed. Thanks!
