### ISSUE TITLE
Extend `aim.ext.tensorboard_tracker.run.Run` to also allow system stats, parameters, and stdout capture.

### ISSUE THREAD

**Issue by alansaul** [aimhubio/aim#2670]
## 🚀 Feature

Allow capturing of system parameters and terminal logs by the `aim.ext.tensorboard_tracker.run.Run`, as this is great feature shouldn't be only available to the default `Run`.

### Motivation

The new feature of allowing continuous syncing from `tensorboard` files to `aim` is really nice, but because `aim.ext.tensorboard_tracker.run.Run` inherits from `BasicRun` rather than `Run`, it misses out on the ability to log the standard out, system stats and system parameters. Since `aim.ext.tensorboard_tracker.run.Run` should be a possible replacement for `Run`, I don't see a reason why this behaviour shouldn't be allowed.

It has been highlighted in Discord by @mihran113:

> The reason behind inheriting from basic run is exactly to avoid terminal log tracking and system param tracking actually, cause we don’t want to add anything else rather than what’s tracked via tensorboard. Cause there can be times when live tracking is done from a different process, and catching that process’s terminal logs and system params won’t make any sense I guess. If you’re interested you can open a PR to address those points, cause adding the possibility to enable those won’t make any harm as well.

so I believe the *default* arguments should *not* do this extra logging, but still optionally allow this behaviour. 

### Pitch

Have `aim.ext.tensorboard_tracker.run.Run` inherit from `aim.sdk.run.Run` instead of `aim.sdk.run.BasicRun`, so that it can utilise it's extra capabilities.

### Alternatives

Instead of inheritance we could change the system resource tracking be a mixin?

**Comment by gorarakelyan** [comment]
@alansaul makes a lot of sense. Thanks for the contribution! 🚀 We will review and merge it to include in the next release.
