### ISSUE TITLE
New Session does not start at step 0 

### ISSUE THREAD

**Issue by bennevans** [aimhubio/aim#270]
I'm trying to track multiple experiments within a Jupyter notebook by reinitializing a session like so:
```
import aim                                                                    
session = aim.Session()                                                               
session.track(1, name='val')                                                          
session.track(2, name='val')                                                          
session.close()                                                                       

session = aim.Session()                                                               
session.track(3, name='val')                                                          
session.track(4, name='val')                                                          
session.close()  
```

The runs show correctly in the dashboard but for the second run, the metric starts showing at step 2 instead of 0. This prevents me from comparing two runs in the Explore tab as they are on different time scales. Is this the expected behaviour? If so, how can I track multiple runs within a single process?

Dashboard:
![Screenshot from 2020-11-13 13-42-17](https://user-images.githubusercontent.com/2406018/99109084-45c8df80-25b6-11eb-96ca-e9c4b535a8e7.png)

Run:
![Screenshot from 2020-11-13 13-43-31](https://user-images.githubusercontent.com/2406018/99109085-46617600-25b6-11eb-84fe-a80ef45e0a08.png)

Explore:
![Screenshot from 2020-11-13 13-49-14](https://user-images.githubusercontent.com/2406018/99109573-0bac0d80-25b7-11eb-9522-6bf635d11736.png)

**Comment by gorarakelyan** [comment]
Hi @bennevans ,

Thanks for opening the issue. We are looking into it.

**Comment by gorarakelyan** [comment]
@bennevans please upgrade Aim(to v2.0.27)  and rerun the training.
The issue should be gone.

**Comment by bennevans** [comment]
It works now thank you!
