### ISSUE TITLE
Dashboard shows log messages multiple times

### ISSUE THREAD

**Issue by Robert27** [aimhubio/aim#2702]
## 🐛 Bug

As soon as you log a message and view it on the dashboard, the newest message is duplicated every second.
When you refresh the page, it is gone and starts over again.

### To reproduce

1. Log a message using log_debug/info etc.
2.Vview it on the dashboard.

### Expected behavior

Displaying the log messages without the new message being displayed repeatedly.

### Environment

- Aim Version: 3.17.3
- Python version 3.9.16
- pip version 23.1.1
- OS MacOS 13.3.1
- Browsers: Safari / Firefox

### Additional context

https://user-images.githubusercontent.com/53063597/235601527-1589c919-b958-44a6-b815-7cd99f7a4f98.mov

**Comment by roubkar** [comment]
Hey @Robert27, thanks for reporting this, looking into it.

**Comment by Robert27** [comment]
Thanks for the quick fix :)
