### ISSUE TITLE
Restarting an experiment programmatically

### ISSUE THREAD

**Issue by lucidrains** [aimhubio/aim#272]
Hi and thanks for the great work here :D So I am using the Session api, and I was wondering if there is any way to programmatically restart the experiment. I was thinking perhaps something like

```python
sess = aim.Session(experiment = 'some_name')
sess.clear()
```

**Comment by SGevorg** [comment]
Hi @lucidrains, thanks for raising the issue. Could you share more details about the use case? What ideally would you be trying to achieve?

**Comment by lucidrains** [comment]
Sure! So I am integrating Aim into one of my GAN libraries https://github.com/lucidrains/stylegan2-pytorch Users may add or subtract images from their dataset and rerun their training, in which case they would pass a `--new` flag, and I'd like to be able to programmatically reset the experiment stats

**Comment by SGevorg** [comment]
I see, would resetting the experiment be a disk usage consideration (to save space)? Or just to organize things better? 
Why not to let each run be recorded?

**Comment by SGevorg** [comment]
From stylegan2-pytorch documentation if you don't provide `--new` flag, it is expected to resume the training right?
In that case if you start second training without the `--new` flag, do you expect the second run to continue to add to the existing metrics of the first run in Aim? As a result having one combined run in Aim?

**Comment by lucidrains** [comment]
@SGevorg I'm expecting users to specify another unique `--name {name}` if they want a new run, but if they want to clear and restart their current run, they provide a `--new`. the resume works fine with Aim already!

**Comment by lucidrains** [comment]
@SGevorg it's ok if you want to push back on this, i can always just come up with a unique experiment name for Aim on my end and associate it with each of my runs

**Comment by SGevorg** [comment]
@lucidrains  no pushback at all. Really trying to have a better grasp of the issue.

With each new training under the same experiment name, it will record a separate run with timestamp.
Here is a screenshot and a live [example](http://play.aimstack.io:43900/experiment/XLM-syntok-dynamic-full-titles-avg/latest). 
Any chance you may have not seen the `Runs:` section on the left? When the web page is shrunk, it disappears. But the runs are there.

This allows to organize training runs under meaningful names. Useless runs can be archived if needed.
![Screenshot 2020-11-15 at 03 23 06](https://user-images.githubusercontent.com/3179216/99158972-e96ada80-26f1-11eb-96a6-fda6b4125cbb.png)

**Comment by SGevorg** [comment]
Same runs are visible on dashboard too with 2 clicks (select the `experiment`, press `search`):
![Screenshot 2020-11-15 at 03 54 45](https://user-images.githubusercontent.com/3179216/99159546-abbc8080-26f6-11eb-8e29-a32eff9cb04d.png)

**Comment by lucidrains** [comment]
@SGevorg oh gotcha! I didn't know about this feature, still pretty new to Aim :^)

this may mean it is good enough! I can just push my users to organize it themselves

**Comment by SGevorg** [comment]
@lucidrains No worries at all.
Aim is designed to "take in" tons of experiments, organize them seamlessly, search them and compare them. Only need to know that experiment is a namespace for training runs.

We should do better job conveying this to the users! Thanks for raising the issue :)
