### ISSUE TITLE
Cannot use tags page in UI

### ISSUE THREAD

**Issue by Nuno-Mota** [aimhubio/aim#2760]
## 🐛 Bug

The `Tags` page isn't correctly displayed in the UI:
![image](https://github.com/aimhubio/aim/assets/17518612/436c110c-6dce-4b31-af95-607d904cb660)

### To reproduce

Unknown.

### Expected behavior

To be able to see all tags that have been used with different runs, like in the [docs](https://aimstack.readthedocs.io/en/v3.17.0/ui/pages/tags.html#tags-page).

### Environment

- Aim Version: 3.17.4
- Python version: 3.10.8
- pip version: 23.1.2
- OS: Archlinux

**Comment by arsengit** [comment]
Hey @Nuno-Mota, thanks for raising this issue 🙌. We will notify you once it has been resolved.

**Comment by Nuno-Mota** [comment]
Thank you @arsengit!
