### ISSUE TITLE
Error running aim up

### ISSUE THREAD

**Issue by walbermr** [aimhubio/aim#277]
Hello, I am facing this issues trying to get aim up and running:

> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 50, in image_exist
>     images = cls._get_docker_client().images.list()
> AttributeError: 'function' object has no attribute 'list'

I dug a little further, solving the issues below and found that `docker_client.containers` is an empty list. I am using a third-party code that uses aim, and I'm wondering if these issues are related to a different version used to create the logging files or if it is a docker issue.

Thanks in advance.

> 
> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 52, in image_exist
>     for t in i.attrs['RepoTags']:
> AttributeError: 'dict' object has no attribute 'attrs'
> 
> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 100, in get_container
>     containers = docker_client.containers.list(all=~running_only,
> AttributeError: 'function' object has no attribute 'list'
> 
> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 112, in kill
>     aim_containers = docker_client.containers.list(all=True, filters={
> AttributeError: 'function' object has no attribute 'list'
> 
> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 83, in up
>     container = docker_client.containers.run(image_name,
> AttributeError: 'function' object has no attribute 'run'
> 
> File "/conda/envs/torch/lib/python3.8/site-packages/aim/engine/container/container.py", line 83, in up
>     container = docker_client.containers(image_name,
> TypeError: containers() got an unexpected keyword argument 'name'
>

**Comment by gorarakelyan** [comment]
Hi @walbermr,

Can you please check version of docker SDK installed in your environment?

You can get the version number by running the following command inside your env:
`pip freeze | grep "docker"`

**Comment by walbermr** [comment]
docker==4.3.1
docker-py==1.10.6
docker-pycreds==0.4.0

**Comment by gorarakelyan** [comment]
You have `docker-py` installed in your env, and it seems when importing docker in Aim, it is imported from package `docker-py` instead of `docker`, which has upgraded and slightly different SDK, hence an exception is thrown.

Python package `docker-py` has been deprecated since 2016 in favor of` docker`.

You can either remove `docker-py` or create a new environment for aim and run `aim up` inside it.

**Comment by walbermr** [comment]
When docker-py is uninstalled, `aim up` says that docker is not installed, despite `docker run hello-world` runs without sudo. Worth note that as I run the test docker inside python, like in #275 , I have this error:

> AttributeError: module 'docker' has no attribute 'from_env'

**Comment by gorarakelyan** [comment]
I just tried to reproduce the issue and came across a weird behavior, but it worked nonetheless.

Reproduction steps:
 - Created an empty conda env;
 - Installed `docker-py` with `pip install docker-py`;
 - Installed aim with `pip install aim`;
 - Tried to run `aim up` -> got `AttributeError: 'function' object has no attribute 'list'` error;
 - Removed `docker-py` with `pip uninstall docker-py`;
 - * Also removed `docker-pycred` which came along with `docker-py`, not sure if it has any effect;
 - Tried to run `aim up` -> now aim says docker is not installed;
 - Removed package `docker` with `pip uninstall docker`;
 - Installed `docker` again `pip install docker==4.3.1`;
 - Run `aim up` and it worked!

**Comment by walbermr** [comment]
Earlier I tried to reinstall docker using `pip` as you said, but didn't worked. I had to remove docker from my system, redo the steps to add my user to docker group and install aim in a new env. Thank you for helping!
