### ISSUE TITLE
Visualization bug on "Tags" site in firefox 

### ISSUE THREAD

**Issue by finnjonaspeper** [aimhubio/aim#2878]
## 🐛 Bug
This bug only appears in Firefox. The "Tags" site contains no tags, even if i created some. It seems to be only a frontend issue because after increasing the height of the div the tags are visible. 
![grafik](https://github.com/aimhubio/aim/assets/131654304/c1fe1efb-9340-41c6-b02d-deaf4deb70ef)

### To reproduce
On self-hosted aim, navigate to Tags in the left sidebar. It shows a tag browser but no tags at all. 

### Expected behavior
I would expect to see my tags. 

### Environment
- Aim Version: 3.17.3
- Python version: 3.10.8
- pip version: 22.3.1 
- OS: CentOS Linux 7 (Core)
- Browser: Firefox 102.12.0esr (64-Bit) on Windows 

### Additional context
If changing the height of "html body div#root div.pageContainer div.mainContainer section.Tags.container div#wrapped-tabpanel-0.Tags__tabPanel div.MuiBox-root.jss5 div.Tags__TagList div.Tags__TagList__tagListBox" to _1000px_ all tags are visible as expected.

**Comment by KaiPressmar** [comment]
Same issue for me ...

Aim Version: 3.17.3
Python version: 3.10.8
pip version: 22.3.1
OS: CentOS Linux 7 (Core)
Browser: Firefox 102.12.0esr (64-Bit) on Windows

**Comment by roubkar** [comment]
Hey @finnjonaspeper and @KaiPressmar, thanks for reporting.
This issue has been fixed with `v3.17.5` release.
Could you please upgrade and see if this issue is resolved for you?

**Comment by finnjonaspeper** [comment]
Yeah, it works. We should have tried this before... Thanks a lot!
