### ISSUE TITLE
Broken demo on homepage

### ISSUE THREAD

**Issue by jmerle** [aimhubio/aim#2880]
Hey! I'm not sure whether "Typos and doc fixes" is the correct category for this issue, but I think it's the most fitting. I'm currently comparing MLOps platforms and noticed the first demo on [https://aimstack.io/](https://aimstack.io/) (the "Machine translation" one) links to [http://play.aimstack.io:10001/metrics?grouping=O-ey...](http://play.aimstack.io:10001/metrics?grouping=O-eyJjb2xvciI6WyJydW4ucGFyYW1zLmhwYXJhbXMubWF4X2siXSwic3Ryb2tlIjpbXSwiY2hhcnQiOlsibmFtZSIsImNvbnRleHQuc3Vic2V0Il0sInJldmVyc2VNb2RlIjp7ImNvbG9yIjpmYWxzZSwic3Ryb2tlIjpmYWxzZSwiY2hhcnQiOmZhbHNlfSwiaXNBcHBsaWVkIjp7ImNvbG9yIjp0cnVlLCJzdHJva2UiOnRydWUsImNoYXJ0Ijp0cnVlfSwicGVyc2lzdGVuY2UiOnsiY29sb3IiOmZhbHNlLCJzdHJva2UiOmZhbHNlfSwic2VlZCI6eyJjb2xvciI6MTAsInN0cm9rZSI6MTB9LCJwYWxldHRlSW5kZXgiOjB9&chart=O-eyJoaWdobGlnaHRNb2RlIjoyLCJpZ25vcmVPdXRsaWVycyI6dHJ1ZSwiem9vbSI6eyJhY3RpdmUiOmZhbHNlLCJtb2RlIjowLCJoaXN0b3J5IjpbXX0sImF4ZXNTY2FsZVR5cGUiOnsieEF4aXMiOiJsaW5lYXIiLCJ5QXhpcyI6ImxpbmVhciJ9LCJheGVzU2NhbGVSYW5nZSI6eyJ5QXhpcyI6e30sInhBeGlzIjp7fX0sInNtb290aGluZyI6eyJhbGdvcml0aG0iOiJFWFBPTkVOVElBTF9NT1ZJTkdfQVZFUkFHRSIsImZhY3RvciI6MCwiY3VydmVJbnRlcnBvbGF0aW9uIjoiY3VydmVMaW5lYXIiLCJpc0FwcGxpZWQiOmZhbHNlfSwiYWxpZ25tZW50Q29uZmlnIjp7Im1ldHJpYyI6IiIsInR5cGUiOiJzdGVwIn0sImRlbnNpdHlUeXBlIjo1MDAsImFnZ3JlZ2F0aW9uQ29uZmlnIjp7Im1ldGhvZHMiOnsiYXJlYSI6MSwibGluZSI6MH0sImlzQXBwbGllZCI6dHJ1ZSwiaXNFbmFibGVkIjp0cnVlfSwidG9vbHRpcCI6eyJhcHBlYXJhbmNlIjoiYXV0byIsImRpc3BsYXkiOnRydWUsInNlbGVjdGVkRmllbGRzIjpbXSwiY29udGVudCI6eyJydW5IYXNoIjoiZGEzZDFlNyIsIm5hbWUiOiJiZXN0X2xvc3MiLCJjb250ZXh0Ijp7InN1YnNldCI6InZhbCJ9LCJtZWRpYUNvbnRlbnQiOnt9LCJncm91cENvbmZpZyI6eyJjb2xvciI6eyJydW4uaHBhcmFtcy5tYXhfayI6MSwicnVuLmRhdGFzZXQucHJlcHJvYyI6IlhMTS1zeW50b2stZ3JlZWR5LWZldy1hdmcifSwiY2hhcnQiOnsibWV0cmljLm5hbWUiOiJiZXN0X2xvc3MiLCJtZXRyaWMuY29udGV4dC5zdWJzZXQiOiJ2YWwifX0sInBhcmFtcyI6e319LCJzZWxlY3RlZFBhcmFtcyI6W119LCJmb2N1c2VkU3RhdGUiOnsia2V5IjoiVDk4cHhKODNhcVJ1TjdNQzlRNEp2ZGtqS01vR0J4Q3lvZEVNRGhNVkVBNjhlVTVrb2V5QzdaVWVLd0M2aGg4Qzc4RDd5SGd6OENXd0VZVW5HZGNrWGJEYUxuMnI5NjF6ZmoyOTdBaG5Nb2tnZG9OUiIsInhWYWx1ZSI6MjEsInlWYWx1ZSI6My40NzM5OTk5NzcxLCJhY3RpdmUiOnRydWUsImNoYXJ0SW5kZXgiOjB9fQ&select=O-eyJvcHRpb25zIjpbeyJsYWJlbCI6ImJlc3RfbG9zcyIsImdyb3VwIjoiYmVzdF9sb3NzIiwiY29sb3IiOiIjMDM5NEI0IiwidmFsdWUiOnsib3B0aW9uX25hbWUiOiJiZXN0X2xvc3MiLCJjb250ZXh0IjpudWxsfSwia2V5IjoiTy1leUp0WlhSeWFXTk9ZVzFsSWpvaVltVnpkRjlzYjNOeklpd2lZMjl1ZEdWNGRFNWhiV1VpT2lJaWZRIn0seyJsYWJlbCI6ImJsZXUiLCJncm91cCI6ImJsZXUiLCJjb2xvciI6IiNFODg1M0QiLCJ2YWx1ZSI6eyJvcHRpb25fbmFtZSI6ImJsZXUiLCJjb250ZXh0IjpudWxsfSwia2V5IjoiTy1leUp0WlhSeWFXTk9ZVzFsSWpvaVlteGxkU0lzSW1OdmJuUmxlSFJPWVcxbElqb2lJbjAifV0sInF1ZXJ5IjoicnVuLmhwYXJhbXMubGVhcm5pbmdfcmF0ZSA-IDAuMDAwMDEiLCJhZHZhbmNlZE1vZGUiOmZhbHNlLCJhZHZhbmNlZFF1ZXJ5IjoicnVuLmhwYXJhbXMubGVhcm5pbmdfcmF0ZSA-IDAuMDAwMDEgYW5kICgobWV0cmljLm5hbWUgPT0gXCJibGV1XCIpIG9yIChtZXRyaWMubmFtZSA9PSBcImJlc3RfbG9zc1wiKSBvciAobWV0cmljLm5hbWUgPT0gXCJic3pcIiBhbmQgbWV0cmljLmNvbnRleHQuc3Vic2V0ID09IFwidHJhaW5cIikpIn0), which shows a dashboard with an "Incorrect Query" message and a SQLAlchemy error:
![](https://github.com/aimhubio/aim/assets/14951909/f15ed847-9a81-4045-b655-3aa98d3394e5)

I'm not sure what the correct link should be, but I'm pretty sure this isn't it.

**Comment by mihran113** [comment]
Hey @jmerle! Thank a lot for the report. 
You can check it out again, should be working fine now.

**Comment by jmerle** [comment]
Yep, works now, thank you!
