### ISSUE TITLE
How to manage runs with custom output directories

### ISSUE THREAD

**Issue by pipme** [aimhubio/aim#2939]
## ❓Question
Hi, `aim` looks great and I am just starting to explore it. One question is how to integrate it with `hydra`'s [output/working directory](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/), especially when deleting runs in `aim`.

One usually uses a custom output directory for saving extra stuff, e.g. pickled objects. I guess I can save the directory path to `aim.Run` object but I am not sure how to conveniently delete that output directory too when deleting runs in aim UI. 

Or is there another recommended way of dealing with a custom output directory?

Thanks!

**Comment by gorarakelyan** [comment]
@pipme we have an Aim artifacts tracking in the roadmap. Which should do the job. I guess currently you can use a python script which both deletes given runs and corresponding directories (path saved as a run param).

**Comment by pipme** [comment]
OK good to know thanks!
