### ISSUE TITLE
Unable to install on windows

### ISSUE THREAD

**Issue by grizzlybearg** [aimhubio/aim#2965]
## 🐛 Bug

I'm currently unable to install aim on windows. Find below the output

### Environment

- Aim Version (e.g., 3.0.1)
- Python version - 3.11
- pip version 23.3.1
- OS -Windows
- Any other relevant information

### Additional context
Here's the output:
`PS C:\Users\user> pip3 install aim
Defaulting to user installation because normal site-packages is not writeable
Collecting aim
  Using cached aim-3.17.5.tar.gz (1.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Collecting setuptools
        Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
        Using cached setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
      Collecting cython==3.0.0a11
        Using cached Cython-3.0.0a11-py2.py3-none-any.whl (1.1 MB)
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.4.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by xquyvu** [comment]
I have the same issue. There's an open issue here https://github.com/aimhubio/aim/issues/2064 about not being able to install `aim` on windows and looks like support isn't going to come any time soon :(
