### ISSUE TITLE
Change plots from linear to log scale

### ISSUE THREAD

**Issue by TommasoBendinelli** [aimhubio/aim#297]
Hello, 
It is possible to change how graphs are plotted switching from linear to log scale?

Best,
Tommaso

**Comment by gorarakelyan** [comment]
Hi @TommasoBendinelli ,

Currently only linear scaling is available, but we will make sure to implement log scaling as soon as possible.
Also, it would be awesome if you could share how often you use this feature and what other scales could be useful.

Thanks for the feedback.

**Comment by TommasoBendinelli** [comment]
Thank you for the response. I use this feature quite a lot, both in the x and y axis

**Comment by gorarakelyan** [comment]
Awesome, thank you!
