### ISSUE TITLE
LOG.old files

### ISSUE THREAD

**Issue by roman-vygon** [aimhubio/aim#3060]
## ❓Question
I am using an [aimlflow](https://github.com/aimhubio/aimlflow) watcher to sync aim with mlflow every minute and I found out that the repository size get's quite big (1gb for a run with ~2e5 logged metrics) because of an abundance of LOG.old files inside the meta/chunks/run_id folder.
Are these necessary, can I remove them or prevent them from being stored?

**Comment by roman-vygon** [comment]
Found some more in seqs/chunks that each weight 1gb, deleted them, search speed went up from 3runs\s to instant.

**Comment by mihran113** [comment]
Hey @roman-vygon! Thanks for the report. 
It's pretty safe to delete those `LOG.old` files. 
What about preventing them from being stored: you can't do it by yourself, as those are determined by the `rocksdb` container settings, we'll patch that in one of the upcoming releases.
