### ISSUE TITLE
Archive bug.

### ISSUE THREAD

**Issue by GeoffreyChen777** [aimhubio/aim#314]
Thanks for your awesome product!

I found that archived runs reappear after a while.

I'm using the latest version (2.1.5).

Is there any debug log that I can provide to you? How to find these logs?

**Comment by SGevorg** [comment]
Hi @GeoffreyChen777 do they appear back on the experiments page or the dashboard?

**Comment by GeoffreyChen777** [comment]
@SGevorg Both.

**Comment by GeoffreyChen777** [comment]
After reading the code about archive function,
https://github.com/aimhubio/aim/blob/ac133883db6ca8255d5e1a5bb498a604b386d28b/aim/engine/repo/repo.py#L895
I think I know what's going on.

Actually, there is no bug of archive function.

Archive state is saved in the `config.json`, but this file is overwrite by my sync scripts.

Because I run my experiments on a cluster, I cannot start the aim UI on this cluster (no docker and no permission to install). So I need to run a sync script on my own machine to fetch the `.aim` folder on the cluster and start the aim ui on my local machine.

It would be better to support remote storage (mentioned here #315 ). I believe many researchers run experiments on clusters.

Anyway, thanks for your awesome product! 😃 

I think this issue can be closed if no further discussion.

**Comment by gorarakelyan** [comment]
Hi @GeoffreyChen777 ,

Thanks for the details. I will keep you updated on progress of remote server feature development. 
We also consider removing docker dependency to make Aim easier to install and to avoid overhead.

**Comment by gorarakelyan** [comment]
@GeoffreyChen777 would love to invite you to join [Aim slack community](http://slack.aimstack.io/) to stay up to date with changes.
