### ISSUE TITLE
Ability to overwrite/manage runs and experiments from SDK

### ISSUE THREAD

**Issue by Sennevs** [aimhubio/aim#319]
Sometimes, especially for testing purposes, I want to run a multitude of experiments/runs without having to manually delete the runs/experiments from the previous test script. Is there a way to manager runs and experiments from the SDK for this purpose?

**Comment by gloryVine** [comment]
This is also my question.

**Comment by gorarakelyan** [comment]
@gloryVine currently most of the time is focused on shipping Aim v3 which besides core improvements(performance, scalability, updated UI) includes highly flexible and comprehensive SDK that enables full management of experiments and logged metadata.

**Comment by alberttorosyan** [comment]
Hey all! The runs hard delete feature has been shipped with `v3.4.0`
Here are UI screenshots:

- `Explorer` pages batch archive/delete:

<img width="558" alt="Screen Shot 2022-01-25 at 10 48 21" src="https://user-images.githubusercontent.com/32957250/150926266-01d583fb-6ce6-4e1a-9eae-e8e031a99e49.png">

- Single run archive/delete from `Settings` tab

<img width="1222" alt="Screen Shot 2022-01-25 at 10 49 55" src="https://user-images.githubusercontent.com/32957250/150926244-c18542f9-5e35-4428-9811-13733102e1b5.png">

And below is the runs delete CLI example:
`aim runs --repo ./aim_repo rm 508fdddc9e27434996f44070 4b2046133c934977bcb60fd4`

**Comment by gloryVine** [comment]
That is great @alberttorosyan. Just tested it and it's working. Thanks a lot!
