### ISSUE TITLE
Subplot in explore page can not show all the data points.

### ISSUE THREAD

**Issue by GeoffreyChen777** [aimhubio/aim#320]
In the metrics tab of experiment details page. I got 3 data points of one subplot:

![image](https://user-images.githubusercontent.com/14183213/107469351-8b407d00-6ba4-11eb-82cc-c4c910907f0d.png)

However, in the explore page, there is only two data point. The last one is missing.

![image](https://user-images.githubusercontent.com/14183213/107469443-b1feb380-6ba4-11eb-97da-38972596b922.png)

Aim version: v2.1.5
AimUI version: v1.3.5

**Comment by roubkar** [comment]
Hey @GeoffreyChen777, thanks for submitting this issue.
Can you please check points count in X-axis properties popup and tell whether increasing points count fixes the issue?


<img width="437" alt="Screen Shot 2021-02-10 at 09 48 44" src="https://user-images.githubusercontent.com/9951653/107470656-2e819a00-6b85-11eb-8f86-cf6742678bab.png">

**Comment by GeoffreyChen777** [comment]
Still missing.

![image](https://user-images.githubusercontent.com/14183213/107471457-1cfdb980-6ba8-11eb-9624-9dae31d5a161.png)

**Comment by gorarakelyan** [comment]
@GeoffreyChen777 could you please upgrade to the newer version? The issue should be gone.

**Comment by gorarakelyan** [comment]
You can upgrade by running `aim upgrade` from cli.

**Comment by GeoffreyChen777** [comment]
hi @gorarakelyan , the new version solves this issue. Thanks!
