### ISSUE TITLE
Axes labels on individual run's metrics

### ISSUE THREAD

**Issue by tanaymeh** [aimhubio/aim#3263]
## ❓Question
I am using AIMLogger with PyTorch Lightning and I am wondering how can I get X and Y axis labels on an individual run's metrics page.

In the screenshot attached below, you can see the metric is called loss but there are no labels indicating what each axis represents.

<img width="1637" alt="Screenshot 2024-12-03 at 09 53 47" src="https://github.com/user-attachments/assets/5a59240e-a183-41c3-95f9-776d02971663">

Is this even possible via some setting?

**Comment by mihran113** [comment]
Hey @tanaymeh. Unfortunately it's not possible to do in the individual run's page. 
Although the axis are fixed in this case. X axis is representing the steps, and the Y: values. 
If you want more details, you can navigate to metrics explorer page, and query the individual run via `run.hash`
