### ISSUE TITLE
System metrics, particularly GPU usage?

### ISSUE THREAD

**Issue by turian** [aimhubio/aim#327]
Aim looks like a wonderful tool.

I am curious if it supports logging system metrics, most importantly GPU usage. (wandb does that, for example)

It's very important for profiling GPU experiments to make sure the GPU utilization is high.

**Comment by gorarakelyan** [comment]
Hi @turian ,

The feature is not implemented yet. Is it a blocker for you to use Aim? 

If you would like to contribute this feature to the project join [Aim community on Slack](https://slack.aimstack.io/), would love to help you with that.

**Comment by turian** [comment]
This would be a very important feature for us to adopt Aim, yes.

(Also, I agree with the [reddit commentator](https://www.reddit.com/r/MachineLearning/comments/lbp5st/n_aim_135_is_out_take_a_look_at_the_new_features/glvxqjn/?utm_source=reddit&utm_medium=web2x&context=3) that feature requests and issues should be discussed on github, not slack.)

**Comment by SGevorg** [comment]
@turian re issues on github: 
Spot on! There has been many feature requests on private channels on Slack. We have recorded most of them. 

Within the next week those features will be brought to here as this is the most optimal place to discuss them. 

Something we have also realized over time and are going to make the changes.

**Comment by SGevorg** [comment]
@turian re system metrics:
We will prioritize this issue for the next week.

**Comment by gorarakelyan** [comment]
Hi @turian ,

This feature is available in the latest release. To upgrade please run `pip install aim --upgrade && aim upgrade` and restart the UI.
