### ISSUE TITLE
Warning (artifact name is not specified) when tracking multiple metrics.

### ISSUE THREAD

**Issue by gormat** [aimhubio/aim#329]
This part of the code throws warnings and tracks only the last metric.

```
            aim_session.track(m1_l1_loss, name='m1_l1_loss', epoch=step)
            aim_session.track(m2_l1_loss, name='m2_l1_loss', epoch=step)
            aim_session.track(m2_l2_loss, name='m2_l2_loss', epoch=step)
            aim_session.track(avg_loss, name='loss', epoch=step)
```

> Something went wrong in `_track_body`: artifact name is not specified

**Comment by felixkreuk** [comment]
@gormat did you solve that issue?

**Comment by gorarakelyan** [comment]
Hi @felixkreuk , this issue was due to passing tensors instead of python primitives(int, float).
If you are using pytorch try to pass `m1_l1_loss.item()` instead of `m1_l1_loss` for example.

**Comment by SGevorg** [comment]
We also have this issue to fix that python primitives vs tf, pytorch types problem https://github.com/aimhubio/aim/issues/342 .

@felixkreuk it's a good first issue if you'd like to contribute.

**Comment by felixkreuk** [comment]
Hmm, then I think there is also an issue with logging hparams when they are stored in a hydra dictionary.

**Comment by gorarakelyan** [comment]
Currently `Session.set_params()` method only accepts pure python dictionaries. Hence, hparams should be converted into python dict before passing to the session.

**Comment by felixkreuk** [comment]
Got it, I will try that, thanks!

**Comment by SGevorg** [comment]
@gorarakelyan do you think we should open an issue for Hydra compatibility? or general hydra integration?

**Comment by gorarakelyan** [comment]
Yea, good call. Will open an issue now.

**Comment by gorarakelyan** [comment]
Opened issue regarding hydra support #404

**Comment by gormat** [comment]
@felixkreuk 

I solved it by replacing the torch variables with numbers. 
`m1_l1_loss ` to ` to m1_l1_loss.item()` and so on.

**Comment by gorarakelyan** [comment]
The issue is resolved in the latest stable release. Now `m1_l1_loss` can be tracked without the need to be converted to a python float beforehand.
