### ISSUE TITLE
Add chart smoothening on the Explore screen

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#343]
Aim does not have ability to smoothen the metrics.
This would allow for better comparison of the experiments.

**Comment by roubkar** [comment]
Here is the PR which enables ability to apply smoothing on line charts: https://github.com/aimhubio/aimui/pull/232

The PR includes implementation of two different smoothing methods: 
Exponential Moving Average and Central Moving Average

![Screen Shot 2021-03-23 at 17 06 06](https://user-images.githubusercontent.com/9951653/112150941-1710e480-8bfa-11eb-852b-c8a98750e475.png)
