### ISSUE TITLE
Ability to display runs parameters diff in context table

### ISSUE THREAD

**Issue by roubkar** [aimhubio/aim#362]
Show table parameters diff: hide only those parameters columns which values are all the same

**Comment by roubkar** [comment]
@gorarakelyan can you please check the new UI for manage columns action buttons?

![Screen Shot 2021-03-15 at 16 03 15](https://user-images.githubusercontent.com/9951653/111150825-02a06c80-85a8-11eb-9a86-4eab9f1909d4.png)

**Comment by gorarakelyan** [comment]
@roubkar looks great
