### ISSUE TITLE
Ability to name each run instead of Session:timestamp

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#377]
Issue by haritsahm on Slack:
Currently Aim runs are named automatically by a timestamp.
It would be great to be able to name issues by custom names also via Session API.

**Comment by SGevorg** [comment]
After the conversation with the community about this feature, we realized that the [Session](https://github.com/aimhubio/aim#session) API for the run needs to be reconsidered.
It accepts run hash only (even though the API says `run` instead of maybe `run_hash`), which is weird as how do you define or differentiate regular names such as `my-run-013` with a hash?
I think limiting an api to "accept only run hash" doesn't make much sense.
@gorarakelyan

**Comment by gorarakelyan** [comment]
closing, as this is available in the current version
