### ISSUE TITLE
Show the standard deviation for aggregation

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#381]
Issue by samvelyan:
Currently Aim displays min/max for aggregated metrics, it would be useful to also show the standard deviation as an operation for aggregation

**Comment by roubkar** [comment]
@gorarakelyan what values should be displayed in `Value` column groups' header cell when std dev aggregation mode is on?

**Comment by gorarakelyan** [comment]
@roubkar I guess min/max(mean ± std.dev) of the aggregated area

**Comment by roubkar** [comment]
<img width="442" alt="Screen Shot 2021-03-25 at 12 56 18" src="https://user-images.githubusercontent.com/9951653/112446468-aa1c5c80-8d69-11eb-845a-1bd81f0f8f24.png">
