### ISSUE TITLE
Problem with BigInt Infinity error in group config hash to color function

### ISSUE THREAD

**Issue by roubkar** [aimhubio/aim#395]
AimUI crushes when group config contains many fields and color persistence mode is on.

**Details**
AimUI crushes while grouping by color with all fields except `learning_rate` when color persistence mode is on.

<img width="450" alt="Screen Shot 2021-03-22 at 18 47 18" src="https://user-images.githubusercontent.com/9951653/112008571-09e2ef80-8b3f-11eb-91c8-93aea934264c.png">
<img width="1073" alt="Screen Shot 2021-03-22 at 18 47 55" src="https://user-images.githubusercontent.com/9951653/112008658-1f581980-8b3f-11eb-8981-4089f409c6b4.png">

**Comment by SGevorg** [comment]
What would `many fields` mean in this context? could you add examples to the description or the comment section that breaks the UI?

**Comment by roubkar** [comment]
@SGevorg sure I will improve the description with more detailed information.

**Comment by roubkar** [comment]
Here is the PR which resolves this issue: https://github.com/aimhubio/aimui/pull/233
