### ISSUE TITLE
Aim doesn't launch

### ISSUE THREAD

**Issue by aprikyan** [aimhubio/aim#402]
Hi!

As the title says, Aim doesn't launch for some reason. My tf.keras code looks like this:

```from aim.tensorflow import AimCallback
from aim import Session

# some code

history = model.fit(training_generator,
              validation_data=valid_generator,
              epochs=100,
              callbacks=[
                  AimCallback(session=Session(experiment='test_tf_keras_cb')),
                  save_best_model_callback,
                  tf_board_callback,
                  cp_callback
              ],
              verbose=1)
```

The training process seems to go as expected, the epochs begin and end, and there's no message/error/warning from Aim. But when I run Aim commands in the terminal (`aim up`, `aim version`, `aim upgrade`), it kind of freezes: there's no output for more than an hour. Pressing Ctrl+C aborts the command as usual. Other callbacks such as that of wandb work.

I have tried:

- Running `aim up` before and during the code execution
- Uninstalling and reinstalling Aim with `pip install aim`
- Replacing `aim.tensorflow` with `aim.keras`, and removing other callbacks

The code is run on Python 3.6.6, in PyCharm 2020.3.3 Professional, Windows 10, on CPU, with Docker Desktop installed, and here is a screenshot from Task Manager.

![image](https://user-images.githubusercontent.com/15716599/112482200-3a21cc80-8d91-11eb-9356-559a7d5b6246.png)

Is there something I've missed? 🙂

**Comment by SGevorg** [comment]
Hi @aprikyan there is an issue with windows for the library - we haven't investigated yet.
A weird behavior. Could you share more logs on what you see on your terminal?

**Comment by aprikyan** [comment]
There's nothing from Aim in the outputs, only tensorflow and wandb logs.

```2021-03-30 18:05:20.653304: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-30 18:05:20.653494: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
wandb: Currently logged in as: ... (use `wandb login --relogin` to force relogin)
2021-03-30 18:05:29.730130: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-30 18:05:29.730320: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

wandb: Tracking run with wandb version 0.10.23
wandb: Syncing run charmed-tree-48
wandb:  View project at https://wandb.ai/...
wandb:  View run at https://wandb.ai/...
wandb: Run data is saved locally in C:\Users\...
wandb: Run `wandb offline` to turn off syncing.

Epoch 1/25
125/125 [==============================] - ETA: 0s - loss: 1.7306 - acc: 0.2828 - f1_m: 0.0230 - precision_m: 0.3141 - recall_m: 0.0121
Epoch 2/25
125/125 [==============================] - ETA: 0s - loss: 1.6575 - acc: 0.3297 - f1_m: 0.0808 - precision_m: 0.5347 - recall_m: 0.0440
```

And so on, until the training ends successfully after 25 epochs.

**Comment by aprikyan** [comment]
This could be helpful too. It looks like Aim registers logs for each run in the .aim directory like this:
```
.aim
│
└───test_tf_keras_cb
    │
    └───d07a118-92ad-11eb-9a6d-1831bfba6804
        │  config.json
        │
        └───objects
            │  meta.json
            │
            └───map
            │   │  dictionary.txt
            │
            └───aimrecords_storage
                │
                └───acc
                    │  bucket_offsets.bin
                    │  current_bucket.bin
                    │  data_chunk_00000.bin
                    │  metadata.json
                    │  record_offsets.bin
                    │
                    └───indices
                        │
                        └───3BNVQjBZ68x9kvpey
                        │   │  index_offsets.bin
                        │
                        └───7VEAAo43RxBXvs
                            │  index_offsets.bin
```

There are dozens of folders (for each run I think) like this in .aim/test_tf_keras_cb with fancy names, and also an empty folder named "index".

**Comment by gorarakelyan** [comment]
Thanks for the details @aprikyan! 

The repo structure is exactly like this. It seems artifacts(metrics, params) are logged properly. I wonder why Aim gets stuck in windows then. Kinda weird behavior. Will troubleshoot it soon. Thanks for your help 😊

**Comment by gorarakelyan** [comment]
Closing the issue due to inactivity.
