### ISSUE TITLE
Ability to resume an experiment

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#403]
An issue from this thread on Reddit: https://www.reddit.com/r/MachineLearning/comments/mc8y1f/n_aim_220_is_out_hugging_face_integration_and/gs64oao/?utm_source=reddit&utm_medium=web2x&context=3

When finetuning models (especially expensive experiments) researchers would want to resume experiments from a certain checkpoint.

**Comment by SGevorg** [comment]
@gorarakelyan I think this perfectly fits the lineage of experiments idea we have talked about countless of times.

1. you run an experiment, save lots of checkpoints
2. you can access them all at once on the UI
3. can start a new one off of a checkpoint based on metrics / numbers

This could dramatically improve the resources cost / training time no?

**Comment by gorarakelyan** [comment]
This feature is available on Aim v3
