### ISSUE TITLE
Track the standard io of the experiment

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aim#405]
An issue off of this Reddit thread:
https://www.reddit.com/r/MachineLearning/comments/mc8y1f/n_aim_220_is_out_hugging_face_integration_and/gs5j74g/?utm_source=reddit&utm_medium=web2x&context=3

Add ability to log the standard out.

**Comment by ashutoshsaboo** [comment]
I just ran into the same issue and was wondering why the run failed (had to go grep through all the complex logs to figure out eventually), quoting from above reddit thread: 
> I would suggest also tracking the standard io of the experiment. It often helps when debugging crashed runs.

Is this still being considered? Any "soonish" plans to ship this? @SGevorg 

Ideally would like these stdout/stderr etc to be in a separate tab under the run single page or if not a separate table atleast, with functionality to search/filter the logs etc from UI.

**Comment by gorarakelyan** [comment]
closing, as stadout/err logs capturing has been shipped with 3.10 version
