### ISSUE TITLE
Enhance column settings menu

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#410]
Currently only pinning options are available in table column menu.
It would be great to provide more options such as:
 - column hiding
 - reorder: move to right/left, start/end
 - sort by

**Comment by roubkar** [comment]
@gorarakelyan any thoughts regarding `move to start/end` text?
Also I'm thinking about adding these options to all panes.

<img width="343" alt="Screen Shot 2021-03-30 at 12 17 12" src="https://user-images.githubusercontent.com/9951653/112956788-dd882e00-9151-11eb-8126-fbc7435ab608.png">

**Comment by roubkar** [comment]
Also I'd like to improve action popup list UI with this PR.

<img width="327" alt="Screen Shot 2021-03-30 at 16 27 56" src="https://user-images.githubusercontent.com/9951653/112988441-e63e2b80-9174-11eb-9f15-0d4bebb471a6.png">
<img width="304" alt="Screen Shot 2021-03-30 at 16 28 30" src="https://user-images.githubusercontent.com/9951653/112988504-fa822880-9174-11eb-80f6-eee107c16eb5.png">

**Comment by gorarakelyan** [comment]
Looks awesome

**Comment by gorarakelyan** [comment]
re "adding options to all panes": yea, I think all the columns should have these options

**Comment by roubkar** [comment]
if there are 5 columns pinned to left wouldn't it be helpful to have these actions available from column?

**Comment by gorarakelyan** [comment]
Really don't know, probably it will. If so we should rename options to `move to pane start/end`.

**Comment by roubkar** [comment]
@gorarakelyan should be fixed now, check please

**Comment by gorarakelyan** [comment]
Great, will do it now

**Comment by gorarakelyan** [comment]
Works fine now 👍
