### ISSUE TITLE
Display popover with run information when selecting ParPlot point

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#411]
Currently selected run and point information of line charts are displayed inside a popover. It would be great to implement popover for parallel coordinates plot as well.

**Comment by roubkar** [comment]
Almost finished working on popover, thoughts?

<img width="1081" alt="Screen Shot 2021-04-02 at 01 43 53" src="https://user-images.githubusercontent.com/9951653/113357332-e563f000-9354-11eb-89a6-0695820aabbe.png">

<img width="326" alt="Screen Shot 2021-04-02 at 01 41 07" src="https://user-images.githubusercontent.com/9951653/113357127-81412c00-9354-11eb-864b-39223bc60f89.png">
<img width="332" alt="Screen Shot 2021-04-02 at 01 41 39" src="https://user-images.githubusercontent.com/9951653/113357169-9453fc00-9354-11eb-8a39-414c1f286107.png">

**Comment by gorarakelyan** [comment]
Looks great
