### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by vopani** [aimhubio/aim#415]
The docs [hyperlink](https://github.com/aimhubio/aim#contents) from website and aimboard directs to `#contents` which seems to have been removed since [this](https://github.com/aimhubio/aim/commit/5d160fd2809bf03e12c4dd384f47e87cefdaf1d1) commit.

**Comment by SGevorg** [comment]
Good spot @vopani, @gorarakelyan could you update AimStack?

**Comment by gorarakelyan** [comment]
@vopani thanks for reporting, will check it now
