### ISSUE TITLE
Integration with Keras Tuner

### ISSUE THREAD

**Issue by HoltSpalding** [aimhubio/aim#422]
Hi, I was wondering if this integrated with the tf Keras hyperparameter tuner and ,if so, are there any examples you could point me to? Thank you, great project.

**Comment by gorarakelyan** [comment]
Hi @HoltSpalding ,

Currently integrations with keras, tf.keras are implemented. Aim doesn't have explicit integration with Keras Tuner yet. I will make sure to keep you updated on the progress and would love to help you in case of you are willing to contribute.

**Comment by HoltSpalding** [comment]
> Hi @HoltSpalding ,
> 
> Currently integrations with keras, tf.keras are implemented. Aim doesn't have explicit integration with Keras Tuner yet. I will make sure to keep you updated on the progress and would love to help you in case of you are willing to contribute.

Yes keep me in the loop. I notice the tuner integrates with Neptune and Tensorboard with this pypi package: https://pypi.org/project/kerastuner-tensorboard-logger/ which might worth looking at. I'm testing to see what happens now if I  use an AimCallback while running the tuner.

**Comment by gorarakelyan** [comment]
I will have a look. Thanks for the details 😊

**Comment by karan2801** [comment]
@gorarakelyan Please assign me this task as I am willing to take this up. TIA!

**Comment by gorarakelyan** [comment]
@HoltSpalding integration with keras-tuner has been shipped with Aim v3.13.0! 
Here are the docs: https://aimstack.readthedocs.io/en/latest/quick_start/integrations.html#integration-with-keras-tuner

**Comment by gorarakelyan** [comment]
Closing this issue, as it is resolved. @HoltSpalding if it is not working as expected or there are more suggestions, please feel free to submit a new issue.
