### ISSUE TITLE
Custom step size

### ISSUE THREAD

**Issue by psinger** [aimhubio/aim#432]
I would like to use a custom step size when tracking metrics. Currently it seems I can only provide an epoch and in the dashboard the step size is always an incremental range with step-size 1.

Would this be already possible to do?

**Comment by gorarakelyan** [comment]
Hi @psinger, 

Try to set `step=<custom step>` in the track function,
 e.g. `session.track(loss_val, name="loss", step=custom_step)`.

**Comment by psinger** [comment]
Thanks! I somehow thought `epoch` is the only way to control it...
