### ISSUE TITLE
Show the position of the cursor on the y-axis

### ISSUE THREAD

**Issue by Khazhak** [aimhubio/aim#434]
Show the position of the cursor on the y-axis as a dot or an arrow.

**Comment by roubkar** [comment]
@Khazhak, @gorarakelyan does this look helpful?

<img width="1057" alt="Screen Shot 2021-04-14 at 00 23 08" src="https://user-images.githubusercontent.com/9951653/114616164-994f6e80-9cb7-11eb-9ce8-f5f8251ff0d6.png">

**Comment by gorarakelyan** [comment]
looks good to me, 
what about setting our primary blue as a background color of the pointers?

**Comment by roubkar** [comment]
![Screen Shot 2021-04-14 at 11 22 24](https://user-images.githubusercontent.com/9951653/114670082-b2860880-9d13-11eb-8a97-91654ba70150.png)

**Comment by Khazhak** [comment]
Looks great to me.

**Comment by roubkar** [comment]
Added horizontal hover line as well.

![Screen Shot 2021-04-15 at 11 52 11](https://user-images.githubusercontent.com/9951653/114833811-06aaee80-9de1-11eb-8079-d9e594f8f74f.png)
