### ISSUE TITLE
"Available fields" field is misleading.

### ISSUE THREAD

**Issue by Khazhak** [aimhubio/aim#448]
**Problem**
When there are multiple experiments, but only some were chosen to be displayed, "Available fields" suggests choosing all metrics from all experiments(not the ones present in the chosen experiment(s)). So the metric is available, but not really.

**Comment by roubkar** [comment]
Hey Khazhak,

Thanks for raising this.
I wonder what do you mean by `chosen experiment(s)`?
Maybe some screenshots also would help.

**Comment by Khazhak** [comment]
Suppose we have 2 experiments, "experiment_1" and "experiment_2". We tracked 2 metrics in "experiment_1", but only one of them in "experiment_2". When you choose "experiment_2" from the dashboard to be explored, the metric that is present in "experiment_1", but absent in the experiment we chose to be explored ("experiment_2") will appear as an available metric to choose too.
Did I explain myself properly @roubkar?

**Comment by roubkar** [comment]
Now I see.

Actually currently the search is designed in the way of choosing metrics and then adding some additional filter to the query which can also include experiment name.

Maybe this is something to consider for rethinking of search design, what do you think @gorarakelyan?

**Comment by gorarakelyan** [comment]
Yea, was also thinking about that. 
I guess there is considerable room for improvement of:
 - select/search design
 - transition of views(metric explorer <-> parplot <-> other views e.g. images, distributions etc)

**Comment by gorarakelyan** [comment]
closing the issue, as the select form was entirely redesigned in Aim v3.
