### ISSUE TITLE
Virtualize table columns

### ISSUE THREAD

**Issue by gorarakelyan** [aimhubio/aim#456]
Optimize table mid pane to not render those columns which are out of the user's viewport.

**Comment by roubkar** [comment]
The current implementation of table column virtualization has space for improvements.
Now dummy columns are being rendered without any content (no cells are rendered) outside of the viewport, this improves the performance. However, when there are many dummy columns, the UI still freezes on some interactions.

Reopening this issue to implement a better virtualization mechanism to improve UI rendering performance.
