### ISSUE TITLE
Common repo over internet

### ISSUE THREAD

**Issue by fedeizzo** [aimhubio/aim#459]
Hi, thanks for your work.

## Summary
I would like to have the ability to define an "online repo" that tracks different experiments and related runs from different machines

## Context
I work for an organization where several research projects are followed at the same time, often the problems for which we develop models are related to the same area (timeseries, computer vision, etc.). For this reason it can be useful to have a centralized repository hosted on a cloud machine where all aim runs are stored, so if I know that a colleague has tried a model X on a specific task I can see which hparams (and related performances) they tried.

At the moment we mainly use a cluster for our train phases, in this cluster it is not possible to run an instance of the aim dashboard.

## Homemade solution
One possible homemade solution is a simple script that does these things:

1. runs the model. During the run aim tracks down metrics and hparams within a local repo
2. After the run is complete, the script compresses the experiment / run and sends it to a cloud machine
3. an end-point made with flask or similar libraries receives the compressed file and after extracting it copies all the content in an "online repository" (another aim repository)
4. the endpoint finally updates the config.json inside the root folder .aim in order to update the aim metadata

This solution has 2 main problems:

* if you decide to update how aim stores data I have to rewrite the functioning of my endpoint
* if two of my colleagues decide to use the same experiment name for two different runs on different cluster nodes, the online repository, during the copy operation, will detect a conflict

**Comment by gorarakelyan** [comment]
Hi @fedeizzo,

Thanks for sharing the details! This feature is related to the issue #386(support of remote/centralized storage). Please take a look at it and check if [the proposed solution](https://github.com/aimhubio/aim/issues/386#issuecomment-819901450) resolves your problem. I will make sure to keep you up to date with the progress.

Plus, currently our team is working on a [feature](https://github.com/aimhubio/aim/pull/455) that provides an ability of running Aim dashboard without docker requirement. Which, I guess, is the main reason that prevents running Aim dashboard in your cluster. Once it is finished, we most probably will start the development of remote storage support, which is one of the most requested features.

**Comment by fedeizzo** [comment]
@gorarakelyan thanks for your reply. The proposed solution would be awesome. Do you accept PR for this particular feature?

**Comment by gorarakelyan** [comment]
@fedeizzo sure, that would be awesome! 
Happy to help if you have any questions.

**Comment by fedeizzo** [comment]
@gorarakelyan I wrote down a possible solution inside #386 issue.

**Comment by gorarakelyan** [comment]
Closing duplicate issue
