### ISSUE TITLE
Add fast.ai integration

### ISSUE THREAD

**Issue by Khazhak** [aimhubio/aim#462]
Fastai is a great library, would be great to have an integration with it.

**Comment by karan2801** [comment]
@gorarakelyan Please assign me this task as I am willing to work on this. TIA!

**Comment by karan2801** [comment]
@gorarakelyan Please assign me this task as I am willing to work on this. TIA!

**Comment by vishalghor** [comment]
Hi @karan2801 I wanted to use aim with fast-ai for distributed training. Is there an update on this new feature from aim?

**Comment by gorarakelyan** [comment]
@vishalghor this issue is put on-hold. however if you are willing to contribute, I will be more than happy to help you.

**Comment by vishalghor** [comment]
@gorarakelyan I will try to take a look at it and get it working with fastai in a way similar to pytorch-lightning but I think the fastai community might be able to do a much better job than me for it

**Comment by gorarakelyan** [comment]
@vishalghor that would be awesome. Adding a base logger (like hparams and metrics tracking) is a good start I guess. It can be iterated on towards deeper integration later on. Thoughts?

**Comment by gorarakelyan** [comment]
@karan2801 @vishalghor closing this issue as the integration with fastai has been shipped!
