### ISSUE TITLE
Missing integration examples

### ISSUE THREAD

**Issue by Khazhak** [aimhubio/aim#464]
We are currently missing integration examples with xgboost, fairseq and fastai.

**Comment by gorarakelyan** [comment]
Let's include integration examples into integration implementation PRs. 
e.g. XGBoost integration example can be included in #454 PR, fastai into #463 PR

**Comment by SGevorg** [comment]
Agree with @gorarakelyan it makes sense to include the examples as part of the PR for the integration.

**Comment by Khazhak** [comment]
Sure. I guess this issue can be closed.
