### ISSUE TITLE
Allow track values list instead of single value.

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#784]
- Allow tracking of a list of homogeneous objects (i.e. `float` values). The resulting tracked sequence is a record list, where each record is list by itself. 
- Add support for getting sequence with entire lists, seqnence for the given index and for the given slice.
- Lists might have different sizes.

Example:

```
# track
run.track([0], ...)
run.track([1, 2, 3], ...)
run.track([4, 5, 6], ...)
run.track([8, 9], ...)

# resulting sequence for index 0 --> [0, 1, 4, 8]
# resulting sequence for index 2 --> [None, 3, 6, None]
# resulting sequence for slice [:2] --> [[0, None], [1, 2], [4, 5], [8, 9]]
```

**Comment by krstp** [comment]
It is not clear from the text what should be tracked… such as ability to track stand-alone list such as `[0]`? But then I don’t understand the resulting sequence piece of: `index 0 --> [0, 1, 4, 8]` ?

**Comment by alberttorosyan** [comment]
@krstp thanks for the comment.
This enhancement request is just describing a basic idea without specifying much details on how it should be implemented. This has ben actually implemented in the scope of enforcing homogeneous sequences (#861), but somehow got lost in the backlog :/ 

The idea behind this feature was to be able to track lists of homogeneous objects during single step. The example above is for scalar values, but this really makes sense for example, when we track sets of images. Now, back to your question; when lists are tracked, we effectively have 2 dimensions for selecting individual values: tracking step and list index within each tracked list. Since SDK provides interface to get sequence data sliced by step, it makes sense to assume the same for the tracked item index as well.
