### ISSUE TITLE
Status of aimrocks

### ISSUE THREAD

**Issue by ofek** [aimhubio/aim#795]
Hello! Are there plans for making `aimrocks` source code public? https://pypi.org/project/aimrocks/

**Comment by gorarakelyan** [comment]
hi @ofek, I just made it public - https://github.com/aimhubio/aimrocks

**Comment by ofek** [comment]
@gorarakelyan Thank you very much! I just opened 2 issues there, feel free to close this and move discussion to those.

**Comment by gorarakelyan** [comment]
@ofek Awesome!
