### ISSUE TITLE
Runs Value Color Scale

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#893]
Please bring back the column color scale from Aim v2 (in the runs page).

**Comment by fakeProgrammer0** [comment]
The lack of support for this feature prevents me to upgrade aim to the v3 version. Applying color gradients to values with different scales really helps me a lot when comparing results of multiple runs as well as tuning hyperparameters of different scales.

**Comment by roubkar** [comment]
Hey @fakeProgrammer0, thanks for sharing your use case.
I will keep you updated with the progress on this one.

**Comment by VkoHov** [comment]
@MohdElgaar this feature was released with v3.8.0, please try it out and let me know if it works as expected.
