### ISSUE TITLE
Run Title Instead of Hash

### ISSUE THREAD

**Issue by MohdElgaar** [aimhubio/aim#896]
I think the run name should be a more descriptive one than hash. It could be date and time, like in Aim v2. Also, I don't think runs are currently being sorted by most recent. Is there not supposed to be a dropdown list for sort-by?

![image](https://user-images.githubusercontent.com/22674819/138217216-0f5acbcf-feeb-4fe3-95ab-b9bb714de4ae.png)

**Comment by gorarakelyan** [comment]
Closing the issue due to inactivity.
