### ISSUE TITLE
Poor query performance when long sequences are logged

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#930]
## 🐛 Bug

When tracking long sequences (> 1 mln. steps) with Aim `Run.track()` method, metrics query performance degrades, regardless the number of requested points. This comes from the fact that entire sequence is read into memory and then sliced according to the number of points requested.

### Expected behavior

Metric sequences query performance should not depend on the number of logged steps, but rather on the number of requested steps. I.e. instead of `O(N)` it should be `O(N')` where `N` is the number of total logged points, and `N'` is the number of steps requested to visualize.

### Environment

- Aim Version 3.0.0+
- Python version: 3.6+
- OS: Linux/MacOS

### Additional context

The most viable solution would be to use random sampling of indices and random acess  instead of forward pass iterator over sequence.

**Comment by gorarakelyan** [comment]
marking as a duplicate, track the future progress on #1685
