### ISSUE TITLE
Could not find a version that satisfies the requirement aimrocks==0.0.7

### ISSUE THREAD

**Issue by imneonizer** [aimhubio/aim#933]
## 🐛 Bug

Unable to install `aim`

### To reproduce

````
pip install aim==3.0.1
````

### Environment

- Aim Version 3.0.1
- Python version 3.8.5
- OS Ubuntu 18.04

### Additional context
````
Collecting aim
  Using cached aim-3.0.1.tar.gz (7.7 MB)
Collecting aimrecords==0.0.7
  Using cached aimrecords-0.0.7-py2.py3-none-any.whl (28 kB)
ERROR: Could not find a version that satisfies the requirement aimrocks==0.0.7 (from aim) (from versions: 0.0.6rc2, 0.0.6rc4, 0.0.6rc5, 0.0.6, 0.0.9)
ERROR: No matching distribution found for aimrocks==0.0.7 (from aim)
````

**Comment by phonokoye** [comment]
I don't know if this is the right place for this. I am experiencing this same issue.

## How to reproduce
> `pip install aimrocks==0.5.*`
ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
ERROR: No matching distribution found for aimrocks==0.5.*

## Environment
pip 25.1.1
Python 3.10.5
Windows 10
