### ISSUE TITLE
Add basic scatter-plot

### ISSUE THREAD

**Issue by KaroMourad** [aimhubio/aim#959]
## 🚀 Feature

The ability to have basic Scatter Plot

### Motivation

To be able to align metric last value data with hyperparameter

### Pitch

When training with Aim, I would like to be able to see the relationship, correlations, and clustering effects between metric last value data with hyperparameter.

### Additional context

![simple-scatter](https://user-images.githubusercontent.com/44981312/140048876-43240883-3bf6-4172-b142-7e98c625a0c3.png)

![simple-scatter-2](https://user-images.githubusercontent.com/44981312/140048909-7e121441-96ae-4ce9-9dcd-2dc440fff121.png)

**Comment by KaroMourad** [comment]
Duplicate of [#491](https://github.com/aimhubio/aim/issues/491)

**Comment by sjakkampudi** [comment]
I'm not sure how hard this is, but I'd like to request the ability to add a lowess trendline to the scatter plot. Probably even a normal line connecting points as well.
