### ISSUE TITLE
Fix aim packaging pipeline for python 3.10 macos

### ISSUE THREAD

**Issue by alberttorosyan** [aimhubio/aim#989]
Currently aim build fails on Github actions packaging pipeline for macos & python 3.10.
<img width="1402" alt="Screen Shot 2021-11-09 at 12 47 57" src="https://user-images.githubusercontent.com/32957250/140892316-58beb440-7a78-4550-a12a-e6a658633202.png">

**Comment by gorarakelyan** [comment]
@alberttorosyan this seems to be fixed, no?

**Comment by alberttorosyan** [comment]
@gorarakelyan yes. the reason was there were no package available for `RestrictedPython` satisfying our requirements. Now they added one for python 3.10. Closing the issue.
