### ISSUE TITLE
Security vulnerabilty

### ISSUE THREAD

**Issue by haby0** [aimhubio/aim#999]
What would be the right contact to report a security vulnerabilty? thanks!

**Comment by gorarakelyan** [comment]
@haby0 feel free to report any issues here.

**Comment by SGevorg** [comment]
@haby0 how about you join our slack channel and let's discuss there ?

**Comment by SGevorg** [comment]
@haby0  here is the link https://slack.aimstack.io/

Thanks for the contribution :).

**Comment by gorarakelyan** [comment]
Resolved in Aim v3.1.0
